CREATE PROCEDURE FETCH_AWARD_REPORT_TRACKING_FOR_REMINDERS()
BEGIN

    DECLARE LI_NOTIFICATION_ID INT ;
    DECLARE LS_REMINDERS_BEFORE_DUE_DATE VARCHAR(100) ;
    DECLARE LI_OVERDUE_FREQUENCY INT;
    DECLARE LS_DUE_DATE_CONDITION TEXT DEFAULT '';
    DECLARE LS_WHERE_CLAUSE TEXT DEFAULT '';
    DECLARE LS_SQL TEXT;
    DECLARE LS_REMAINING_TEXT VARCHAR(100);
    DECLARE LI_CURRENT_DAYS INT;
    DECLARE LI_COMMA_POS INT;
    DECLARE LD_CUTOFF_DATE DATE;

    SET LI_NOTIFICATION_ID = 2206;
    SET LS_REMINDERS_BEFORE_DUE_DATE = '7,14';
    SET LI_OVERDUE_FREQUENCY = 7;
    SET LD_CUTOFF_DATE = '2025-12-15';

    -- Build due date condition from comma-separated string
    IF LS_REMINDERS_BEFORE_DUE_DATE != '' AND LS_REMINDERS_BEFORE_DUE_DATE IS NOT NULL THEN
        SET LS_DUE_DATE_CONDITION = '(';
        SET LS_REMAINING_TEXT = LS_REMINDERS_BEFORE_DUE_DATE;
        SET LI_COMMA_POS = LOCATE(',', LS_REMAINING_TEXT);
        
        WHILE LI_COMMA_POS > 0 DO
            SET LI_CURRENT_DAYS = CAST(SUBSTRING(LS_REMAINING_TEXT, 1, LI_COMMA_POS - 1) AS UNSIGNED);
            
            IF LS_DUE_DATE_CONDITION != '(' THEN
                SET LS_DUE_DATE_CONDITION = CONCAT(LS_DUE_DATE_CONDITION, ' OR ');
            END IF;
            
            SET LS_DUE_DATE_CONDITION = CONCAT(LS_DUE_DATE_CONDITION, 
                't1.DUE_DATE = DATE_ADD(CURDATE(), INTERVAL ', LI_CURRENT_DAYS, ' DAY)');
            
            SET LS_REMAINING_TEXT = SUBSTRING(LS_REMAINING_TEXT, LI_COMMA_POS + 1);
            SET LI_COMMA_POS = LOCATE(',', LS_REMAINING_TEXT);
        END WHILE;
        
        -- Handle last value (no comma after it)
        IF LS_REMAINING_TEXT != '' THEN
            SET LI_CURRENT_DAYS = CAST(LS_REMAINING_TEXT AS UNSIGNED);
            
            IF LS_DUE_DATE_CONDITION != '(' THEN
                SET LS_DUE_DATE_CONDITION = CONCAT(LS_DUE_DATE_CONDITION, ' OR ');
            END IF;
            
            SET LS_DUE_DATE_CONDITION = CONCAT(LS_DUE_DATE_CONDITION, 
                't1.DUE_DATE = DATE_ADD(CURDATE(), INTERVAL ', LI_CURRENT_DAYS, ' DAY)');
        END IF;
        
        SET LS_DUE_DATE_CONDITION = CONCAT(LS_DUE_DATE_CONDITION, ')');
    END IF;
    
    -- Build WHERE clause
    IF (LS_DUE_DATE_CONDITION != '' AND LI_OVERDUE_FREQUENCY IS NOT NULL AND LI_OVERDUE_FREQUENCY > 0) THEN
        -- Both before-due-date and overdue reminders
        -- SET LS_WHERE_CLAUSE = CONCAT('AND (', LS_DUE_DATE_CONDITION, ' ',
        --   'OR (t1.DUE_DATE < CURDATE() AND DATEDIFF(t1.DUE_DATE, CURDATE()) % ', 
        --    LI_OVERDUE_FREQUENCY, ' = 0))');
        SET LS_WHERE_CLAUSE = CONCAT('AND t1.DUE_DATE >= ''', LD_CUTOFF_DATE, ''' ','AND (', LS_DUE_DATE_CONDITION, ' ',
            'OR (t1.DUE_DATE < CURDATE() AND DATEDIFF(CURDATE(), t1.DUE_DATE) % ', 
            LI_OVERDUE_FREQUENCY, ' = 0))'
            );
    ELSEIF LS_DUE_DATE_CONDITION != '' THEN
        -- Only before-due-date reminders
        -- SET LS_WHERE_CLAUSE = CONCAT('AND ', LS_DUE_DATE_CONDITION);
        SET LS_WHERE_CLAUSE = CONCAT('AND t1.DUE_DATE >= ''', LD_CUTOFF_DATE, ''' ','AND ', LS_DUE_DATE_CONDITION
            );
    ELSEIF LI_OVERDUE_FREQUENCY IS NOT NULL AND LI_OVERDUE_FREQUENCY > 0 THEN
        -- Only overdue reminders
        SET LS_WHERE_CLAUSE = CONCAT('AND (t1.DUE_DATE < CURDATE() AND DATEDIFF(t1.DUE_DATE, CURDATE()) % ', 
            LI_OVERDUE_FREQUENCY, ' = 0)');
    END IF;
    
    -- If both conditions are empty/null, return empty result set
    IF LS_WHERE_CLAUSE = '' THEN
        SELECT
			NULL AS NOTIFICATION_ID,
            NULL AS AWARD_REPORT_TRACKING_ID,
            NULL AS AWARD_REPORT_TERMS_ID,
            NULL AS REPORT_CLASS_CODE,
            NULL AS REPORT_CODE,
            NULL AS DUE_DATE,
            NULL AS REPORT_TRACKING_DUE_DATE,
            NULL AS DAYS_TO_DUE_DATE,
            NULL AS AWARD_ID
        WHERE 1 = 0;
    ELSE
        -- Build and execute the main query
        SET LS_SQL = CONCAT(
            'SELECT ',
             LI_NOTIFICATION_ID, ' as NOTIFICATION_ID, ',
            't1.AWARD_REPORT_TRACKING_ID, ',
            't1.AWARD_REPORT_TERMS_ID, ',
            't6.REPORT_CLASS_CODE as REPORT_CLASS_CODE, ',
            't7.REPORT_CODE as REPORT_CODE, ',
            't5.DUE_DATE as DUE_DATE, ',
            't1.DUE_DATE as REPORT_TRACKING_DUE_DATE, ',
            'DATEDIFF(t1.DUE_DATE, CURDATE()) as DAYS_TO_DUE_DATE, ',
            't1.AWARD_ID as AWARD_ID ',
            'FROM AWARD_REPORT_TRACKING t1 ',
            'INNER JOIN AWARD t2 ON t2.AWARD_ID = t1.AWARD_ID ',
            'LEFT JOIN AWARD_REPORT_TRACKING_FILE t3 ON t3.AWARD_REPORT_TRACKING_ID = t1.AWARD_REPORT_TRACKING_ID ',
            'LEFT JOIN AWARD_PROGRESS_REPORT t4 ON t4.PROGRESS_REPORT_ID = t1.PROGRESS_REPORT_ID ',
            'LEFT JOIN AWARD_REPORT_TERMS t5 ON t5.AWARD_REPORT_TERMS_ID = t1.AWARD_REPORT_TERMS_ID ',
            'LEFT JOIN REPORT_CLASS t6 ON t6.REPORT_CLASS_CODE = t5.REPORT_CLASS_CODE ',
            'LEFT JOIN REPORT t7 ON t7.REPORT_CODE = t5.REPORT_CODE ',
            'WHERE t2.STATUS_CODE = 1 AND',
            '(t2.AWARD_SEQUENCE_STATUS = ''ACTIVE'' OR (t2.AWARD_DOCUMENT_TYPE_CODE = 1 AND t2.AWARD_SEQUENCE_STATUS = ''PENDING'')) ',
            'AND (t1.PROGRESS_REPORT_ID IS NULL OR (t1.PROGRESS_REPORT_ID IS NOT NULL AND t4.PROGRESS_REPORT_STATUS_CODE = 1)) ',
            'AND t3.AWARD_REPORT_TRACKING_FILE_ID IS NULL ',
            LS_WHERE_CLAUSE
        );
        
        -- Execute dynamic SQL using prepared statement
        SET @sql_query = LS_SQL;
        PREPARE stmt FROM @sql_query;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
    
END
