CREATE PROCEDURE `DELETE_AGREEMENT_RECORD`(AV_AGREEMENT_REQUEST_ID varchar(20))
BEGIN

DECLARE LS_NEGOTIATION_ID decimal(22,0);

SET SQL_SAFE_UPDATES =0;
DELETE FROM AGREEMENT_FINANCIAL_DETAIL WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID;

DELETE FROM AGREEMENT_NOTE_ATTACHMENT WHERE AGREEMENT_NOTE_ID IN (SELECT AGREEMENT_NOTE_ID FROM AGREEMENT_NOTE WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID);

DELETE FROM AGREEMENT_NOTE WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID;

DELETE FROM AGREEMENT_KEYWORDS WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID;

DELETE FROM AGREEMENT_SPECIAL_REVIEW WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID;

DELETE FROM AGREEMENT_CLAUSES WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID;

DELETE FROM CUSTOM_DATA WHERE (MODULE_ITEM_KEY = AV_AGREEMENT_REQUEST_ID AND MODULE_ITEM_CODE = 13);

DELETE FROM AGREEMENT_PEOPLE WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID;

DELETE FROM AGREEMENT_SPONSOR_CONTACT WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID;
DELETE FROM AGREEMENT_SPONSOR WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID;

DELETE FROM AGREEMENT_ATTACHMENT_FILE WHERE AGREEMENT_ATTACHMENT_FILE_ID IN 
       (SELECT AGREEMENT_ATTACHMENT_FILE_ID FROM AGREEMENT_ATTACHMENT WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID);
       
DELETE FROM AGREEMENT_ATTACHMENT WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID;

SELECT @LS_NEGOTIATION_ID := NEGOTIATION_ID FROM NEGOTIATION_ASSOCIATION WHERE ASSOCIATED_PROJECT_ID = AV_AGREEMENT_REQUEST_ID;
DELETE FROM NEGOTIATION_ATTACHMENT WHERE NEGOTIATION_ID IN (SELECT @LS_NEGOTIATION_ID);
DELETE FROM NEGOTIATION_ACTIVITY WHERE NEGOTIATION_ID IN (SELECT @LS_NEGOTIATION_ID);
DELETE FROM NEGOTIATION_LOCATION WHERE NEGOTIATION_ID IN (SELECT @LS_NEGOTIATION_ID);
DELETE FROM NEGOTIATION_ASSOCIATION WHERE ASSOCIATED_PROJECT_ID = AV_AGREEMENT_REQUEST_ID;
DELETE FROM NEGOTIATION WHERE NEGOTIATION_ID IN (SELECT @LS_NEGOTIATION_ID);

DELETE FROM PRE_REVIEW_ATTACHMENT_FILE WHERE FILE_DATA_ID IN ( SELECT FILE_DATA_ID FROM PRE_REVIEW_ATTACHMENT WHERE PRE_REVIEW_COMMENT_ID IN ( SELECT  PRE_REVIEW_COMMENT_ID FROM PRE_REVIEW_COMMENT WHERE PRE_REVIEW_ID IN ( SELECT  PRE_REVIEW_ID FROM PRE_REVIEW WHERE MODULE_ITEM_KEY = AV_AGREEMENT_REQUEST_ID )));
DELETE FROM PRE_REVIEW_ATTACHMENT WHERE PRE_REVIEW_COMMENT_ID IN (SELECT  PRE_REVIEW_COMMENT_ID FROM PRE_REVIEW_COMMENT WHERE PRE_REVIEW_ID IN (SELECT  PRE_REVIEW_ID FROM PRE_REVIEW WHERE MODULE_ITEM_KEY = AV_AGREEMENT_REQUEST_ID));
DELETE FROM PRE_REVIEW_COMMENT WHERE PRE_REVIEW_ID IN (SELECT  PRE_REVIEW_ID FROM PRE_REVIEW WHERE MODULE_ITEM_KEY = AV_AGREEMENT_REQUEST_ID);
DELETE FROM SUPPORT_REQUEST_NOTIFICATION  WHERE PRE_REVIEW_ID IN (SELECT  PRE_REVIEW_ID FROM PRE_REVIEW WHERE MODULE_ITEM_KEY = AV_AGREEMENT_REQUEST_ID);
DELETE FROM PRE_REVIEW WHERE MODULE_ITEM_KEY = AV_AGREEMENT_REQUEST_ID;

DELETE FROM AGREEMENT_ACTION_LOG WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID;

DELETE FROM AGREEMENT_ASSOCIATION_LINK WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID;

DELETE FROM INBOX WHERE MODULE_ITEM_KEY = AV_AGREEMENT_REQUEST_ID;

DELETE FROM QUEST_ANSWER_ATTACHMENT WHERE QUESTIONNAIRE_ANSWER_ID IN (SELECT QUESTIONNAIRE_ANSWER_ID FROM QUEST_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID IN (SELECT QUESTIONNAIRE_ANS_HEADER_ID FROM QUEST_ANSWER_HEADER WHERE (MODULE_ITEM_KEY = AV_AGREEMENT_REQUEST_ID AND MODULE_ITEM_CODE = 13)) );
DELETE FROM QUEST_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID IN (SELECT QUESTIONNAIRE_ANS_HEADER_ID FROM QUEST_ANSWER_HEADER WHERE (MODULE_ITEM_KEY = AV_AGREEMENT_REQUEST_ID AND MODULE_ITEM_CODE = 13));
DELETE FROM QUEST_ANSWER_HEADER WHERE (MODULE_ITEM_KEY = AV_AGREEMENT_REQUEST_ID AND MODULE_ITEM_CODE = 13);
DELETE FROM AGREEMENT_HEADER WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID;

DELETE FROM ASSOC_SR WHERE MODULE_ITEM_ID IN (SELECT AGREEMENT_ID FROM ASSOC_AGREEMENT WHERE AGREEMENT_ID=AV_AGREEMENT_REQUEST_ID) AND ASSOC_TYPE ='REVERSE'AND MODULE_CODE =13;
DELETE FROM ASSOC_AGREEMENT WHERE AGREEMENT_ID = AV_AGREEMENT_REQUEST_ID;
DELETE FROM ASSOC_AGREEMENT WHERE MODULE_ITEM_ID = AV_AGREEMENT_REQUEST_ID AND ASSOC_TYPE ='REVERSE' AND MODULE_CODE =13;
SET SQL_SAFE_UPDATES =1;
END
