DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO table_exists
    FROM user_tables
    WHERE table_name = 'MIT_INT_STAGE_SR';
    
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE "MIT_INT_STAGE_SR" 
            ("MODULE_CODE" NUMBER, 
            "MODULE_ITEM_KEY" NUMBER, 
            "PI_NAME" VARCHAR2(90 BYTE), 
            "LEAD_UNIT_NUMBER" VARCHAR2(8 BYTE), 
            "LEAD_UNIT_NAME" VARCHAR2(200 BYTE), 
            "SUBJECT" VARCHAR2(1000 BYTE), 
            "STATUS_CODE" NUMBER(3,0), 
            "STATUS" VARCHAR2(200 BYTE), 
            "REPORTER_NAME" VARCHAR2(90 BYTE), 
            "PRIORITY_ID" NUMBER, 
            "PRIORITY" VARCHAR2(200 BYTE), 
            "CATEGORY_CODE" NUMBER(3,0), 
            "CATEGORY" VARCHAR2(500 BYTE), 
            "TYPE_CODE" NUMBER(3,0), 
            "TYPE" VARCHAR2(500 BYTE), 
            "FIRST_FED_TIMESTAMP" DATE, 
            "LAST_FED_TIMESTAMP" DATE, 
            "UPDATE_BY" VARCHAR2(90 BYTE), 
            "UPDATE_TIMESTAMP" DATE, 
            "DESCRIPTION" CLOB, 
            "AA_PERSON_FULL_NAME" VARCHAR2(90 BYTE), 
            CONSTRAINT "PK_MIT_INT_STAGE_SR" PRIMARY KEY ("MODULE_ITEM_KEY")
            )';
    END IF;
END;
/

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO table_exists
    FROM user_tables
    WHERE table_name = 'SR_CONNECT_CONFIG';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE SR_CONNECT_CONFIG 
            (SR_CONFIG_ID NUMBER(10,0), 
            SUBJECT VARCHAR2(1000), 
            PRIORITY_ID NUMBER(10,0), 
            CATEGORY_CODE VARCHAR2(3), 
            TYPE_CODE VARCHAR2(3),
            DESCRIPTION CLOB, 
            CREATE_USER VARCHAR2(60), 
            CREATE_TIMESTAMP DATE DEFAULT SYSDATE, 
            UPDATE_BY VARCHAR2(40), 
            UPDATE_TIMESTAMP DATE, 
            ASSOC_CONFIG_CODE VARCHAR2(3), 
            RELATION_TYPE_CODE VARCHAR2(3), 
            FETCH_LIMIT_FOR_SYNC NUMBER DEFAULT 100 NOT NULL, 
            STATUS_CODE VARCHAR2(10), 
            PRIMARY KEY (SR_CONFIG_ID)
            )';
    END IF;
END;
/

MERGE INTO SR_CONNECT_CONFIG T
USING (SELECT 1 AS SR_CONFIG_ID FROM DUAL) S
ON (T.SR_CONFIG_ID = S.SR_CONFIG_ID)
WHEN NOT MATCHED THEN
  INSERT (
    SR_CONFIG_ID, SUBJECT, PRIORITY_ID, CATEGORY_CODE, TYPE_CODE, DESCRIPTION,
    CREATE_USER, CREATE_TIMESTAMP, UPDATE_BY, UPDATE_TIMESTAMP,
    ASSOC_CONFIG_CODE, RELATION_TYPE_CODE, FETCH_LIMIT_FOR_SYNC, STATUS_CODE
  )
  VALUES (
    1, 'New Award Received', 1, '13', '1',
    'New Award Received. This ticket is generated from Fibi-Agreement : ',
    'admin', SYSDATE, 'admin', SYSDATE,
    '4', '4', 10000, '1'
  );


ALTER TABLE MITKC_ELASTIC_INDEX
ADD (
    OBLIGATED_TOTAL              NUMBER(12,2) NULL,
    ANTICIPATED_TOTAL_AMOUNT     NUMBER(12,2) NULL,
    OBLIGATION_EXPIRATION_DATE   DATE         NULL,
    OBLIGATION_START_DATE        DATE         NULL,
    IP_TOT_PROJ_COST             NUMBER(12,2) NULL
);

-- Delete Script for MITKC_ELASTIC_INDEX
DELETE from MITKC_ELASTIC_INDEX@FIBISO_LINK
where module_code in(1,2,3)

-- Insert Script for MITKC_ELASTIC_INDEX(Development Proposal)
INSERT INTO MITKC_ELASTIC_INDEX@FIBISO_LINK(
MODULE_CODE, MODULE_ITEM_KEY, DOCUMENT_NUMBER, TITLE, LEAD_UNIT_NAME, LEAD_UNIT_NUMBER, STATUS, STATUS_CODE, SPONSOR_CODE, SPONSOR_NAME,
PERSON_ID, PI_NAME, LOAD_TIMESTAMP, START_DATE, END_DATE, CONTRACT_ADMIN_PERSON_ID, PRIME_SPONSOR_CODE)
SELECT
3,
EPS_PROPOSAL.PROPOSAL_NUMBER,
EPS_PROPOSAL.DOCUMENT_NUMBER,
EPS_PROPOSAL.TITLE,
UNIT.UNIT_NAME AS LEAD_UNIT,
EPS_PROPOSAL.OWNED_BY_UNIT AS LEAD_UNIT_NUMBER,
PROPOSAL_STATE.DESCRIPTION AS STATUS,
EPS_PROPOSAL.STATUS_CODE,
EPS_PROPOSAL.SPONSOR_CODE,
SPONSOR.SPONSOR_NAME AS SPONSOR,
T1.PERSON_ID,
T1.FULL_NAME,
SYSDATE,
EPS_PROPOSAL.REQUESTED_START_DATE_INITIAL,
EPS_PROPOSAL.REQUESTED_END_DATE_INITIAL,
T2.PERSON_ID AS CONTRACT_ADMIN_PERSON_ID,
EPS_PROPOSAL.PRIME_SPONSOR_CODE
FROM EPS_PROPOSAL
INNER JOIN UNIT ON UNIT.UNIT_NUMBER = EPS_PROPOSAL.OWNED_BY_UNIT
LEFT OUTER JOIN SPONSOR ON SPONSOR.SPONSOR_CODE = EPS_PROPOSAL.SPONSOR_CODE
INNER JOIN PROPOSAL_STATE ON PROPOSAL_STATE.STATE_TYPE_CODE = EPS_PROPOSAL.STATUS_CODE
LEFT OUTER JOIN EPS_PROP_PERSON T1 ON EPS_PROPOSAL.PROPOSAL_NUMBER = T1.PROPOSAL_NUMBER and t1.PROP_PERSON_ROLE_ID = 'PI'
LEFT OUTER JOIN UNIT_ADMINISTRATOR T2 ON T2.UNIT_NUMBER = EPS_PROPOSAL.OWNED_BY_UNIT and T2.UNIT_ADMINISTRATOR_TYPE_CODE = '2'

-- Insert Script for MITKC_ELASTIC_INDEX(Award)
INSERT INTO MITKC_ELASTIC_INDEX@FIBISO_LINK(
MODULE_CODE, MODULE_ITEM_KEY, DOCUMENT_NUMBER, PERSON_ID, PI_NAME, ACCOUNT_NUMBER, LEAD_UNIT_NUMBER, LEAD_UNIT_NAME, TITLE, 
SPONSOR_CODE, SPONSOR_NAME, SPONSOR_AWARD_ID, LOAD_TIMESTAMP, STATUS, status_code, MODULE_ITEM_ID, START_DATE, END_DATE, OBLIGATED_TOTAL, 
ANTICIPATED_TOTAL_AMOUNT, OBLIGATION_START_DATE, OBLIGATION_EXPIRATION_DATE, CONTRACT_ADMIN_PERSON_ID, PRIME_SPONSOR_CODE)
SELECT
1 as MODULE_CODE,
t1.AWARD_NUMBER as MODULE_ITEM_KEY,
t1.DOCUMENT_NUMBER,
t3.PERSON_ID,
t3.FULL_NAME AS PI_NAME,
nvl(t1.ACCOUNT_NUMBER,' ') ACCOUNT_NUMBER,
t1.LEAD_UNIT_NUMBER,
T2.UNIT_NAME as LEAD_UNIT_NAME,
t1.TITLE,
t4.SPONSOR_CODE,
t4.SPONSOR_NAME,
t1.SPONSOR_AWARD_NUMBER,
SYSDATE,
T8.DESCRIPTION as STATUS,
T1.status_code,
t1.award_id,
t1.AWARD_EFFECTIVE_DATE,
t5.final_expiration_date,
t5.AMOUNT_OBLIGATED_TO_DATE,
t5.ANTICIPATED_TOTAL_AMOUNT,
t5.CURRENT_FUND_EFFECTIVE_DATE,
t5.OBLIGATION_EXPIRATION_DATE,
T7.PERSON_ID AS CONTRACT_ADMIN_PERSON_ID,
T1.PRIME_SPONSOR_CODE
FROM AWARD t1
INNER JOIN UNIT t2 on T1.LEAD_UNIT_NUMBER = T2.UNIT_NUMBER
LEFT OUTER JOIN AWARD_PERSONS t3 ON t1.AWARD_ID = t3.AWARD_ID AND CONTACT_ROLE_CODE = 'PI'
LEFT OUTER JOIN SPONSOR t4 ON t1.SPONSOR_CODE = t4.SPONSOR_CODE
LEFT OUTER JOIN UNIT_ADMINISTRATOR T7 ON T7.UNIT_NUMBER = T1.LEAD_UNIT_NUMBER and T7.UNIT_ADMINISTRATOR_TYPE_CODE = '2'
inner join award_amount_info t5 on t1.award_id = t5.award_id
LEFT OUTER JOIN AWARD_STATUS T8 on t1.STATUS_CODE = T8.STATUS_CODE
WHERE T1.AWARD_SEQUENCE_STATUS = 'ACTIVE'
AND T5.AWARD_AMOUNT_INFO_ID IN (SELECT MAX(AWARD_AMOUNT_INFO_ID) FROM award_amount_info t6 WHERE t6.award_id = t5.award_id)

-- Insert Script for MITKC_ELASTIC_INDEX(Institute Proposal)
INSERT INTO MITKC_ELASTIC_INDEX@FIBISO_LINK(
MODULE_CODE, MODULE_ITEM_KEY, DOCUMENT_NUMBER, PERSON_ID, PI_NAME, ACCOUNT_NUMBER, LEAD_UNIT_NUMBER, LEAD_UNIT_NAME, TITLE, SPONSOR_CODE,
SPONSOR_NAME, LOAD_TIMESTAMP, STATUS, status_code, START_DATE, END_DATE, CONTRACT_ADMIN_PERSON_ID, PRIME_SPONSOR_CODE, IP_TOT_PROJ_COST)
SELECT
2 as MODULE_CODE,
t1.PROPOSAL_NUMBER as MODULE_ITEM_KEY,
t1.DOCUMENT_NUMBER,
t3.PERSON_ID,
t3.FULL_NAME AS PI_NAME,
NULL as ACCOUNT_NUMBER,
t1.LEAD_UNIT_NUMBER,
T2.UNIT_NAME as LEAD_UNIT_NAME,
t1.TITLE,
t4.SPONSOR_CODE,
t4.SPONSOR_NAME,
SYSDATE ,
T6.DESCRIPTION as STATUS,
T1.status_code,
t1.REQUESTED_START_DATE_INITIAL,
t1.REQUESTED_END_DATE_INITIAL,
T5.PERSON_ID AS CONTRACT_ADMIN_PERSON_ID,
T1.PRIME_SPONSOR_CODE,
T1.TOTAL_DIRECT_COST_TOTAL+ T1.TOTAL_INDIRECT_COST_TOTAL as total_cost
FROM PROPOSAL t1
INNER JOIN UNIT t2 on T1.LEAD_UNIT_NUMBER = T2.UNIT_NUMBER
LEFT OUTER JOIN PROPOSAL_PERSONS t3 ON t1.PROPOSAL_ID = t3.PROPOSAL_ID AND CONTACT_ROLE_CODE = 'PI'
LEFT OUTER JOIN SPONSOR t4 ON t1.SPONSOR_CODE = t4.SPONSOR_CODE
LEFT OUTER JOIN UNIT_ADMINISTRATOR T5 ON T5.UNIT_NUMBER = T1.LEAD_UNIT_NUMBER and T5.UNIT_ADMINISTRATOR_TYPE_CODE = '2'
LEFT OUTER JOIN PROPOSAL_STATUS T6 ON T1.STATUS_CODE = T6.PROPOSAL_STATUS_CODE
WHERE T1.PROPOSAL_SEQUENCE_STATUS = 'ACTIVE'
