CREATE PROCEDURE `GET_PROPOSAL_DASHBOARD_V1`(
    IN AV_FILTER_JSON JSON,
    IN AV_DISPLAY_LIST JSON,
    IN AV_PERSON_ID VARCHAR(40),
    IN AV_OFFSET INT(10),
    IN AV_LIMIT INT(10),
    IN AV_TAB_TYPE VARCHAR(30),
    IN AV_IS_COUNT BOOLEAN,
    IN AV_SORT_TYPE VARCHAR(500)
)
BEGIN

    -- Declare variables
    DECLARE LS_DYN_SQL LONGTEXT;
    DECLARE LS_FILTER_CONDITION LONGTEXT;
    DECLARE LS_OFFSET INT(11);
    DECLARE IS_UNIT_ADMIN INT(11);
    
    -- Custom data element variables
    DECLARE LI_CUSTOM_DATA_ELEMENTS_ID INT(11);
    DECLARE LI_DATA_TYPE INT(11);
    DECLARE LS_CUST_LABEL VARCHAR(255);
    DECLARE LI_CUST_ORDER INT(11);
    DECLARE LS_IS_MULTI_SELECT_LOOKUP VARCHAR(1);
    DECLARE LS_CUSTOM_CRT VARCHAR(255);
    DECLARE LS_CUST_CRT_VALUE TEXT;
    DECLARE CUSTOM_CRT_QUERY TEXT;
    DECLARE LS_CUSTOM_COL VARCHAR(255);
    DECLARE LS_CUSTOM_DATA_ELEMENT VARCHAR(255);
    DECLARE LS_CUST_COL TEXT;
    DECLARE LS_CUSTOM_DATA_JOIN_SEL TEXT;
    DECLARE NOT_FOUND INT DEFAULT 0;
    DECLARE old_depth INT;

    -- Cursor for custom data elements
    DECLARE CUSTOM_DATA_ELEMENTS_IDS CURSOR FOR
      SELECT CDE.CUSTOM_DATA_ELEMENTS_ID, CDE.DATA_TYPE, CDE.COLUMN_LABEL, CDEU.ORDER_NUMBER, CDE.IS_MULTI_SELECT_LOOKUP
      FROM CUSTOM_DATA_ELEMENTS CDE
      INNER JOIN CUSTOM_DATA_ELEMENT_USAGE CDEU ON CDEU.CUSTOM_DATA_ELEMENTS_ID = CDE.CUSTOM_DATA_ELEMENTS_ID
      WHERE CDEU.MODULE_CODE = 20 AND CDE.IS_ACTIVE = 'Y' AND CDEU.IS_REQ_ADVANCE_SEARCH = 'Y';
          
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;

    SET LS_FILTER_CONDITION = '';
    SET LS_CUSTOM_DATA_JOIN_SEL = '';
    SET LS_DYN_SQL = '';
    SET @CUST_CRITERIA_MAP = JSON_OBJECT();
    SET @CUST_COL_MAP = JSON_OBJECT();
    SET @AV_FILTER_JSON = AV_FILTER_JSON;
    SET @AV_DISPLAY_LIST = AV_DISPLAY_LIST;
    SET SESSION time_zone = '+00:00';
    SET old_depth = @@SESSION.optimizer_search_depth;
    SET SESSION optimizer_search_depth = 11;

    -- Process custom data elements
    OPEN CUSTOM_DATA_ELEMENTS_IDS;
    CUSTOM_DATA_ELEMENTS_LOOP: LOOP
        SET NOT_FOUND = 0;
        FETCH CUSTOM_DATA_ELEMENTS_IDS INTO LI_CUSTOM_DATA_ELEMENTS_ID, LI_DATA_TYPE, LS_CUST_LABEL, LI_CUST_ORDER, LS_IS_MULTI_SELECT_LOOKUP;
        
        IF NOT_FOUND = 1 THEN
            LEAVE CUSTOM_DATA_ELEMENTS_LOOP;
        END IF;

        -- Build custom field names
        SET LS_CUSTOM_CRT = CONCAT('CRT_SR_CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID);
        SET LS_CUSTOM_DATA_ELEMENT = CONCAT('CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID);
        SET LS_CUST_CRT_VALUE = JSON_UNQUOTE(JSON_EXTRACT(AV_FILTER_JSON, CONCAT('$.', LS_CUSTOM_CRT)));
        
       SET LS_CUSTOM_DATA_JOIN_SEL = CONCAT(
            LS_CUSTOM_DATA_JOIN_SEL,
            CASE 
               WHEN LI_DATA_TYPE = 4 OR (LI_DATA_TYPE IN (8,9) AND LS_IS_MULTI_SELECT_LOOKUP = 'Y') THEN 
				CONCAT(
					'JSON_ARRAYAGG(JSON_OBJECT(''CUSTOM_ANSWER'', CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID, 
					')) AS CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID
				)
                WHEN LI_DATA_TYPE = 3 THEN
				CONCAT('(UNIX_TIMESTAMP( CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID, '))*1000 AS CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID)
                ELSE 
                    CONCAT('CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID)
            END,
            ','
        );

        -- Build custom criteria query
        IF LS_CUST_CRT_VALUE IS NOT NULL THEN
            SET CUSTOM_CRT_QUERY = NULL;
            IF LI_DATA_TYPE IN (3) THEN
                SET CUSTOM_CRT_QUERY = CONCAT('(', LS_CUSTOM_DATA_ELEMENT, ' = (UNIX_TIMESTAMP(''', LS_CUST_CRT_VALUE, ''')*1000))');
            ELSEIF LI_DATA_TYPE IN (1,10) THEN
                SET CUSTOM_CRT_QUERY = CONCAT('(', LS_CUSTOM_DATA_ELEMENT, ' LIKE ''%', LS_CUST_CRT_VALUE, '%'')');
            ELSEIF LI_DATA_TYPE IN (4,6,8,9) THEN
                IF LS_IS_MULTI_SELECT_LOOKUP = 'Y' THEN
                    SET CUSTOM_CRT_QUERY = CONCAT('(JSON_CONTAINS(''', LS_CUST_CRT_VALUE, ''', JSON_QUOTE(', LS_CUSTOM_DATA_ELEMENT, '))  )');
                ELSE
					SET CUSTOM_CRT_QUERY = CONCAT('(JSON_CONTAINS(''', LS_CUST_CRT_VALUE, ''', JSON_QUOTE(', LS_CUSTOM_DATA_ELEMENT, '))  )');
                END IF;
            ELSE
				IF LI_DATA_TYPE IN (7, 5)THEN
                 SET LS_CUST_CRT_VALUE = JSON_UNQUOTE(JSON_EXTRACT(LS_CUST_CRT_VALUE, '$[0]'));
                END IF;
                
                SET CUSTOM_CRT_QUERY = CONCAT('(', LS_CUSTOM_DATA_ELEMENT, ' = ''', LS_CUST_CRT_VALUE, ''')');
            END IF;
            
            IF CUSTOM_CRT_QUERY IS NOT NULL THEN
                SET @CUST_CRITERIA_MAP = JSON_INSERT(@CUST_CRITERIA_MAP, CONCAT('$.', LS_CUSTOM_CRT), CUSTOM_CRT_QUERY);
            END IF;
        END IF;
        
        -- Handle custom column display
        SET LS_CUSTOM_COL = CONCAT('COL_SR_CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID);

        IF JSON_CONTAINS(AV_DISPLAY_LIST, JSON_QUOTE(LS_CUSTOM_COL)) = 1 THEN
            SET @CUST_COL_MAP = JSON_INSERT(@CUST_COL_MAP, CONCAT('$.', LS_CUSTOM_COL), CONCAT('CD.', CONCAT('CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID)));
        END IF;
  
    END LOOP CUSTOM_DATA_ELEMENTS_LOOP;
    CLOSE CUSTOM_DATA_ELEMENTS_IDS;
 -- PREPARE CUSTOM DATA QUERY: END
 SET LS_CUSTOM_DATA_JOIN_SEL = TRIM(TRAILING ',' FROM LS_CUSTOM_DATA_JOIN_SEL);


 -- PREPARE CTE QUERY: START
    SET @DYNAMIC_CTE = CONCAT('WITH ACCESS_TMP 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 
                            )),
							ACCESS_TMP_PROPOSAL_GM 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') AND T1.ROLE_ID=''100'' 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') AND T1.ROLE_ID=''100''
                            ))
							');
 -- PREPARE CTE QUERY: END

SET @KEY_PERSONS_CTE ='PROPOSAL_KEY_PERSONS_JSON AS (
                                SELECT PP.PROPOSAL_ID,
					JSON_ARRAYAGG(
						JSON_OBJECT(
							''FIRST_NAME'', COALESCE(P.FIRST_NAME, R.FIRST_NAME),
							''LAST_NAME'', COALESCE(P.LAST_NAME, R.LAST_NAME),
							''FULL_NAME'', COALESCE(P.FULL_NAME, CONCAT(R.FIRST_NAME, '' '', R.LAST_NAME)),
							''ROLE_NAME'', PR.DESCRIPTION,
							''PERCENTAGE_OF_EFFORT'', PP.PERCENTAGE_OF_EFFORT
						)
					) AS KEY_PERSONS
				FROM EPS_PROPOSAL_PERSONS PP
				LEFT JOIN PERSON P ON P.PERSON_ID = PP.PERSON_ID
				LEFT JOIN ROLODEX R ON R.ROLODEX_ID = PP.ROLODEX_ID
				INNER JOIN EPS_PROP_PERSON_ROLE PR ON PR.PROP_PERSON_ROLE_ID = PP.PROP_PERSON_ROLE_ID
				GROUP BY PP.PROPOSAL_ID
                            )';

SET @KEY_PERSONS_ROLES_CTE ='PROPOSAL_KEY_PERSONS_ROLES_JSON AS (
                                SELECT PP.PROPOSAL_ID,
					JSON_ARRAYAGG(
						JSON_OBJECT(
							''ROLE_NAME'', PR.DESCRIPTION
						)
					) AS KEY_PERSONS_ROLES
				FROM EPS_PROPOSAL_PERSONS PP
				LEFT JOIN PERSON P ON P.PERSON_ID = PP.PERSON_ID
				LEFT JOIN ROLODEX R ON R.ROLODEX_ID = PP.ROLODEX_ID
				INNER JOIN EPS_PROP_PERSON_ROLE PR ON PR.PROP_PERSON_ROLE_ID = PP.PROP_PERSON_ROLE_ID
				GROUP BY PP.PROPOSAL_ID
                            )';

SET @PROPOSAL_SPECIAL_REVIEW_CTE = 'PROPOSAL_SPECIAL_REVIEW_JSON AS (
                        SELECT PROPOSAL_ID,
                            JSON_ARRAYAGG(
                                JSON_OBJECT(''PROTOCOL_NUMBER'', PROTOCOL_NUMBER)
                            ) AS SPECIAL_REVIEWS
                        FROM EPS_PROPOSAL_SPECIAL_REVIEW
                        GROUP BY PROPOSAL_ID
                        )';
						
SET @PROPOSAL_RESEARCH_AREAS_CTE = 'PROPOSAL_RESEARCH_AREAS_JSON AS (
    SELECT ARA.PROPOSAL_ID,
        JSON_ARRAYAGG(
            JSON_OBJECT(
                ''AREA'', RA.DESCRIPTION,
                ''SUB_AREA'', RSA.DESCRIPTION
            )
        ) AS RESEARCH_AREAS
    FROM EPS_PROPOSAL_RESRCH_AREAS ARA
    LEFT JOIN RESEARCH_TYPE_AREA RA ON RA.RESRCH_TYPE_AREA_CODE = ARA.RESRCH_TYPE_AREA_CODE
    LEFT JOIN RESEARCH_TYPE_SUB_AREA RSA ON RSA.RESRCH_TYPE_SUB_AREA_CODE = ARA.RESRCH_TYPE_SUB_AREA_CODE
    GROUP BY ARA.PROPOSAL_ID
)';

   SET @KEY_WORD_CTE = 'PROPOSAL_KEYWORDS_JSON AS (
                            SELECT DISTINCT AK.PROPOSAL_ID,
                                JSON_ARRAYAGG(
                                    JSON_OBJECT(''KEYWORD'', COALESCE(SK.DESCRIPTION, AK.KEYWORD))
                                ) AS KEYWORDS
                            FROM EPS_PROPOSAL_KEYWORDS AK
                            LEFT JOIN SCIENCE_KEYWORD SK ON SK.SCIENCE_KEYWORD_CODE = AK.SCIENCE_KEYWORD_CODE
                            GROUP BY AK.PROPOSAL_ID
                        )';
	
SET @PRE_REVIEW_CTE = 'PROPOSAL_PREREVIEW_JSON AS (
    SELECT
        PRT.MODULE_ITEM_KEY,
        JSON_ARRAYAGG(JSON_OBJECT(''DESCRIPTION'', PR.DESCRIPTION)) AS PRE_REVIEWS
    FROM (
        SELECT PRT2.MODULE_ITEM_KEY, PRT2.PRE_REVIEW_SECTION_TYPE_CODE
        FROM pre_review PRT2
        WHERE PRT2.MODULE_ITEM_CODE = 3 and PRE_REVIEW_STATUS_CODE IS NOT NULL 
    ) PRT
    LEFT JOIN pre_review_section_type PR ON PR.PRE_REVIEW_SECTION_TYPE_CODE = PRT.PRE_REVIEW_SECTION_TYPE_CODE
    GROUP BY PRT.MODULE_ITEM_KEY
)';

SET @PROPOSAL_PROJECT_TEAM_CTE = 'PROPOSAL_PROJECT_TEAM_JSON AS (
    SELECT APT.PROPOSAL_ID,
        JSON_ARRAYAGG(
            JSON_OBJECT(
                ''FULL_NAME'', APT.FULL_NAME,
                ''ROLE_NAME'', APT.PROJECT_ROLE,
                ''PERCENTAGE_CHARGED'', APT.PERCENTAGE_CHARGED,
                ''START_DATE'', (UNIX_TIMESTAMP(APT.START_DATE)*1000),
                ''END_DATE'', (UNIX_TIMESTAMP(APT.END_DATE)*1000)
            )
        ) AS PROJECT_TEAM
    FROM EPS_PROPOSAL_PROJECT_TEAM APT
    GROUP BY APT.PROPOSAL_ID
)';

SET @PROPOSAL_ORGANIZATION_CTE = 'PROPOSAL_ORGANIZATION_JSON AS (
    SELECT PORG.PROPOSAL_ID,
        JSON_ARRAYAGG(
            JSON_OBJECT(
                ''ORGANIZATION_NAME'', IFNULL(ORG.ORGANIZATION_NAME, ORG1.ORGANIZATION_NAME),
                ''ORGANIZATION_ID'', IFNULL(PORG.ORGANIZATION_ID, ORG1.ORGANIZATION_ID),
                ''ORGANIZATION_TYPE'', IFNULL(OT.DESCRIPTION,'''')
            )
        ) AS ORGANIZATION
    FROM EPS_PROPOSAL_ORGANIZATION PORG
	LEFT JOIN ORGANIZATION ORG ON ORG.ORGANIZATION_ID = PORG.ORGANIZATION_ID    
    LEFT JOIN ROLODEX RR ON RR.ROLODEX_ID = PORG.ROLODEX_ID
    LEFT JOIN ORGANIZATION ORG1 ON ORG1.ORGANIZATION_ID = RR.ORGANIZATION    
    LEFT JOIN ORGANIZATION_TYPE OT ON OT.ORGANIZATION_TYPE_CODE = PORG.ORGANIZATION_TYPE_CODE
    GROUP BY PORG.PROPOSAL_ID
) ,
PROPOSAL_ORGANIZATION_FILTER AS (
    SELECT PORG.PROPOSAL_ID,
    IFNULL(ORG.ORGANIZATION_NAME, ORG1.ORGANIZATION_NAME)AS ORGANIZATION
    FROM EPS_PROPOSAL_ORGANIZATION PORG
    LEFT JOIN ORGANIZATION ORG ON ORG.ORGANIZATION_ID = PORG.ORGANIZATION_ID    
    LEFT JOIN ROLODEX RR ON RR.ROLODEX_ID = PORG.ROLODEX_ID
    LEFT JOIN ORGANIZATION ORG1 ON ORG1.ORGANIZATION_ID = RR.ORGANIZATION
    GROUP BY PORG.PROPOSAL_ID,PORG.ORGANIZATION_ID,PORG.ROLODEX_ID
)
';

SET @IP_STATUS_CTE = 'IP_STATUS_JSON AS (
    SELECT PAD.DEV_PROPOSAL_ID,
        GROUP_CONCAT(DISTINCT T52.DESCRIPTION SEPARATOR '', '') AS IP_STATUS
    FROM PROPOSAL_ADMIN_DETAILS PAD
    LEFT JOIN PROPOSAL T51 ON T51.PROPOSAL_ID = PAD.INST_PROPOSAL_ID
    LEFT JOIN PROPOSAL_STATUS T52 ON T52.STATUS_CODE = T51.STATUS_CODE
    WHERE T51.PROPOSAL_SEQUENCE_STATUS = ''ACTIVE''
    GROUP BY PAD.DEV_PROPOSAL_ID
)';


  SET @GRANT_CALL_CTE = 'GRANT_CALL_JSON AS (
    SELECT P.PROPOSAL_ID,
        JSON_ARRAYAGG(
            JSON_OBJECT(
                ''GRANT_HEADER_ID'', GCH.GRANT_HEADER_ID,
                ''ABBREVIATION'', GCH.ABBREVIATION,
                ''GRANT_CALL_NAME'', GCH.NAME
            )
        ) AS GRANT_CALL
    FROM EPS_PROPOSAL P
    INNER JOIN GRANT_CALL_HEADER GCH ON GCH.GRANT_HEADER_ID = P.GRANT_HEADER_ID
    WHERE P.GRANT_HEADER_ID IS NOT NULL
    GROUP BY P.PROPOSAL_ID
)';

 SET @CTE_MAP = JSON_OBJECT(
    'CTE_PROPOSAL_SPECIAL_REVIEW', @PROPOSAL_SPECIAL_REVIEW_CTE,
    'CTE_KEY_PERSONS', @KEY_PERSONS_CTE,
    'CTE_PROPOSAL_RESEARCH_AREAS', @PROPOSAL_RESEARCH_AREAS_CTE,
	'CTE_POSAL_PROJECT_TEAM', @PROPOSAL_PROJECT_TEAM_CTE,
	'CTE_KEYWORD_CTE', @KEY_WORD_CTE,
    'ORGANIZATION_CTE',@PROPOSAL_ORGANIZATION_CTE,
    'CTE_IP_STATUS',@IP_STATUS_CTE,
	'REVIEW_CTE',@PRE_REVIEW_CTE,
    'CTE_GRANT_CALL', @GRANT_CALL_CTE,
    'CTE_KEY_PERSONS_ROLES',@KEY_PERSONS_ROLES_CTE
    );

    SET @CTE_KEY_MAP = JSON_ARRAY(
    JSON_OBJECT('CTE_PROPOSAL_SPECIAL_REVIEW', JSON_ARRAY('COL_DEV_PROPOSAL_SPL_REVIEW_PROTOCOL','CRT_DEV_PROPOSAL_SPL_REVIEW_PROTOCOL')),
    JSON_OBJECT('CTE_KEY_PERSONS', JSON_ARRAY('COL_DEV_PROPOSAL_KEY_PERSONS','CRT_DEV_PROPSAL_KEY_PERSONS')),
    JSON_OBJECT('CTE_PROPOSAL_RESEARCH_AREAS', JSON_ARRAY('COL_DEV_PROPOSAL_RESEARCH_AREAS','CRT_DEV_PROPOSAL_RESEARCH_AREAS')),
	JSON_OBJECT('CTE_POSAL_PROJECT_TEAM', JSON_ARRAY('COL_DEV_PROPOSAL_PROJECT_TEAM','CRT_DEV_PROPOSAL_PROJECT_TEAM')),
	JSON_OBJECT('CTE_KEYWORD_CTE', JSON_ARRAY('COL_DEV_PROPOSAL_KEYWORD', 'CRT_DEV_PROPOSAL_KEYWORD')),
    JSON_OBJECT('ORGANIZATION_CTE', JSON_ARRAY('CRT_DEV_PROPOSAL_ORGANIZATION', 'COL_DEV_PROPOSAL_ORGANIZATION')),
    JSON_OBJECT('CTE_IP_STATUS', JSON_ARRAY('COL_DEV_IP_STATUS', 'CRT_DEV_IP_STATUS')),
    JSON_OBJECT('CTE_GRANT_CALL', JSON_ARRAY('COL_DEV_PROP_GRANT_CALL_ABBREVATION')),
    JSON_OBJECT('CTE_KEY_PERSONS_ROLES', JSON_ARRAY('CRT_DEV_PROPOSAL_KEY_PERSON_ROLES'))
    );

SET @DYNAMIC_CTE = CONCAT(@DYNAMIC_CTE, COALESCE(FN_PREPARE_DASHBOARD_JOINS(@AV_DISPLAY_LIST,  @AV_FILTER_JSON, @CTE_KEY_MAP, @CTE_MAP, 'CTE'),''));

-- PREPARE COLUMN QUERY: START

    IF AV_IS_COUNT = FALSE THEN
        SET @QUERY_MAP = JSON_OBJECT(
			'proposalId','T1.PROPOSAL_ID',
			'statusCode','T1.STATUS_CODE',
			'unitNumber','T1.HOME_UNIT_NUMBER',
			'HEADER_ID','T1.PROPOSAL_ID',
            'COL_DEV_PROPOSAL_ID', 'T1.PROPOSAL_ID',
			'COL_DEV_PROPOSAL_TITLE', 'T1.TITLE',
            'COL_DEV_PROPOSAL_TYPE', 'EPT.DESCRIPTION',
            'COL_DEV_PROP_AWARD_TYPE', 'T30.DESCRIPTION',
			'COL_DEV_PROP_GRANT_CALL_ABBREVATION', '(GCJ.GRANT_CALL)',
            'COL_DEV_PROP_HOME_UNIT_NAME', 'T1.HOME_UNIT_NAME',
            'COL_DEV_PROP_SPONSOR', 'T31.DISPLAY_NAME',
            'COL_DEV_PROP_PRIME_SPONSOR', 'T20.DISPLAY_NAME',
			'COL_DEV_PROPOSAL_PI','(PROPOSAL_PI.PI_NAMES)',
			'COL_DEV_PROP_FUNDING_SCHEME','FS.DESCRIPTION',
            'COL_DEV_PROPOSAL_START_DATE', '(UNIX_TIMESTAMP(T1.START_DATE)*1000)',
            'COL_DEV_PROPOSAL_END_DATE', '(UNIX_TIMESTAMP(T1.END_DATE)*1000)',
            'COL_DEV_PROP_INTERNAL_DEADLINE_DATE', '(UNIX_TIMESTAMP(T1.INTERNAL_DEADLINE_DATE)*1000)',
            'COL_DEV_PROP_SPONSOR_DEADLINE_DATE', '(UNIX_TIMESTAMP(T1.SPONSOR_DEADLINE_DATE)*1000)',
            'COL_DEV_PROP_STATUS', 'PS.DESCRIPTION',
            'COL_MASTER_PROPOSAL', 'T1.BASE_PROPOSAL_NUMBER',
            'COL_DEV_PROPOSAL_MASTER_AWARD', 'T1.AWARD_NUMBER',
			'COL_DEV_PROPOSAL_KEY_PERSONS','(KP.KEY_PERSONS)',
            'COL_EXTERNAL_FUNDING_AGENCY_ID', 'T1.EXTERNAL_FUNDING_AGENCY_ID',
			'COL_DEV_PROPO_PROGRAM_ANNOUNCEMENT_NUMBER', 'T1.PROGRAM_ANNOUNCEMENT_NUMBER',
			'COL_DEV_PROP_CFDA_NUMBER', 'T1.CFDA_NUMBER',
            'COL_DEV_PROPO_GRANT_CALL_TITLE', 'GC.NAME',
			'COL_DEV_PROPOSAL_GRANT_CALL_UNIT','GC.HOME_UNIT_NAME',
			'COL_GRANT_CALL_SPONSOR','GCS.SPONSOR_NAME',
			'COL_DEV_PROPOSAL_CATEGORY','AT.DESCRIPTION',
			'COL_DEV_PROPOSAL_SPL_REVIEW_PROTOCOL','(ASR.SPECIAL_REVIEWS)',
			'COL_DEV_PROPOSAL_RESEARCH_AREAS', '(RAR.RESEARCH_AREAS)',
			'COL_DEV_PROPOSAL_PROJECT_TEAM', '(PT.PROJECT_TEAM)',
			'COL_DEV_PROPOSAL_KEYWORD','(K.KEYWORDS)',
			'COL_DEV_PROPOSAL_ORGANIZATION','(PO.ORGANIZATION)',
            'COL_DEV_IP_STATUS', '(IPS.IP_STATUS)',
            'UPDATE_TIMESTAMP', 'T1.UPDATE_TIMESTAMP'
        );
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST,'$','HEADER_ID');  
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST,'$','proposalId');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST,'$','statusCode');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST,'$','unitNumber');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST,'$','UPDATE_TIMESTAMP');

        SELECT JSON_MERGE_PATCH(@QUERY_MAP, @CUST_COL_MAP) INTO @QUERY_MAP;

        -- Build display mapping from requested columns
		
        SET @DISPLAY_MAP = (
            SELECT JSON_OBJECTAGG(jk.k, JSON_UNQUOTE(JSON_EXTRACT(@QUERY_MAP, CONCAT('$.', jk.k))))
            FROM JSON_TABLE(AV_DISPLAY_LIST, '$[*]' COLUMNS (k VARCHAR(100) PATH '$')) AS jk
            WHERE JSON_EXTRACT(@QUERY_MAP, CONCAT('$.', jk.k)) IS NOT NULL
        );
        
        SELECT FN_PREPARE_DASHBOARD_SELECT(@DISPLAY_MAP) INTO @SELECT_STM;
        SELECT FN_PREPARE_DASHBOARD_JSON(@DISPLAY_MAP) INTO @DISPLAY;

    END IF;
-- PREPARE COLUMN QUERY: END

-- PREPARE JOIN QUERY: START

	SET @CUSTOM_DATA_JOIN = CONCAT('LEFT JOIN (SELECT PROPOSAL_ID,',LS_CUSTOM_DATA_JOIN_SEL,' FROM SR_CUSTOM_DATA_RT GROUP BY PROPOSAL_ID) CD ON CD.PROPOSAL_ID = T1.PROPOSAL_ID');

    SET @JOIN_QUERY_MAP = JSON_OBJECT(
    'JOIN_CUSTOM_DATA',@CUSTOM_DATA_JOIN,
    'JOIN_AWARD_TYPE','LEFT JOIN AWARD_TYPE T30 ON T30.AWARD_TYPE_CODE = T1.AWARD_TYPE_CODE',
	'JOIN_SPONSOR','LEFT JOIN SPONSOR T31 ON T31.SPONSOR_CODE = T1.SPONSOR_CODE',
	'JOIN_PRIME_SPONSOR','LEFT JOIN SPONSOR T20 ON T20.SPONSOR_CODE = T1.PRIME_SPONSOR_CODE',
	'JOIN_PROPOSAL_TYPE','LEFT JOIN eps_proposal_type EPT ON T1.TYPE_CODE = EPT.TYPE_CODE',
    'JOIN_PROPOSAL_KEY_PERSONS',' LEFT JOIN PROPOSAL_KEY_PERSONS_JSON KP ON T1.PROPOSAL_ID = KP.PROPOSAL_ID',
	'JOIN_PROPOSAL_PI','LEFT JOIN (SELECT PROPOSAL_ID, GROUP_CONCAT(FULL_NAME SEPARATOR '' | '') AS PI_NAMES FROM EPS_PROPOSAL_PERSONS WHERE PROP_PERSON_ROLE_ID = 3 GROUP BY PROPOSAL_ID) PROPOSAL_PI ON PROPOSAL_PI.PROPOSAL_ID = T1.PROPOSAL_ID',
    'JOIN_STATUS',' LEFT JOIN eps_proposal_status PS ON T1.STATUS_CODE = PS.STATUS_CODE',
	'JOIN_GRANT_CALL',' LEFT JOIN GRANT_CALL_HEADER GC ON GC.GRANT_HEADER_ID = T1.GRANT_HEADER_ID',
	'JOIN_GRANT_SPONSOR',' LEFT JOIN SPONSOR GCS ON GCS.SPONSOR_CODE = GC.SPONSOR_CODE',
    'JOIN_MASTER_PROPOSAL', 'LEFT JOIN PROPOSAL IP ON IP.PROPOSAL_NUMBER = T1.BASE_PROPOSAL_NUMBER',
	'JOIN_PROPOSAL_CATEGORY', 'LEFT JOIN ACTIVITY_TYPE AT ON AT.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE',
	'JOIN_PROPOSAL_SPL_REVIEW', 'LEFT JOIN PROPOSAL_SPECIAL_REVIEW_JSON ASR ON T1.PROPOSAL_ID = ASR.PROPOSAL_ID',
	'JOIN_PROPOSAL_RESEARCH_AREAS', 'LEFT JOIN PROPOSAL_RESEARCH_AREAS_JSON RAR ON T1.PROPOSAL_ID = RAR.PROPOSAL_ID',
	'JOIN_PROPOSAL_PROJECT_TEAM', 'LEFT JOIN PROPOSAL_PROJECT_TEAM_JSON PT ON T1.PROPOSAL_ID = PT.PROPOSAL_ID',
	'JOIN_GRANT_FUNDING_SCHEME','LEFT JOIN SPONSOR_FUNDING_SCHEME SFS ON SFS.FUNDING_SCHEME_ID = GC.FUNDING_SCHEME_ID LEFT JOIN FUNDING_SCHEME FS ON FS.FUNDING_SCHEME_CODE = SFS.FUNDING_SCHEME_CODE',
	'JOIN_PROPOSAL_KEYWORDS', 'LEFT JOIN PROPOSAL_KEYWORDS_JSON K ON T1.PROPOSAL_ID = K.PROPOSAL_ID',
	'JOIN_PROPOSAL_ORGANIZATION', 'LEFT JOIN PROPOSAL_ORGANIZATION_JSON PO ON PO.PROPOSAL_ID = T1.PROPOSAL_ID',
    'JOIN_IP_STATUS', 'LEFT JOIN IP_STATUS_JSON IPS ON T1.PROPOSAL_ID = IPS.DEV_PROPOSAL_ID',
    'JOIN_GRANT_CALL_JSON', 'LEFT JOIN GRANT_CALL_JSON GCJ ON T1.PROPOSAL_ID = GCJ.PROPOSAL_ID'
    );
    SET @JOIN_KEY_MAP = JSON_ARRAY(
    JSON_OBJECT('JOIN_CUSTOM_DATA', JSON_ARRAY('CUST_ELEMENTS_ID')),
    JSON_OBJECT('JOIN_AWARD_TYPE', JSON_ARRAY('COL_DEV_PROP_AWARD_TYPE','CRT_DEV_PROP_AWARD_TYPE')),
    JSON_OBJECT('JOIN_SPONSOR', JSON_ARRAY('COL_DEV_PROP_SPONSOR','CRT_DEV_PROP_SPONSOR')),
    JSON_OBJECT('JOIN_PROPOSAL_PI', JSON_ARRAY('CRT_DEV_PROPOSAL_PI','COL_DEV_PROPOSAL_PI')),
    JSON_OBJECT('JOIN_PRIME_SPONSOR', JSON_ARRAY('COL_DEV_PROP_PRIME_SPONSOR','CRT_DEV_PROP_PRIME_SPONSOR')),
    JSON_OBJECT('JOIN_GRANT_CALL', JSON_ARRAY('COL_DEV_PROP_GRANT_CALL_ABBREVATION','COL_DEV_PROPOSAL_GRANT_CALL_UNIT','COL_GRANT_CALL_UNIT','COL_DEV_PROPO_GRANT_CALL_TITLE','CRT_DEV_PROPOSAL_GRANT_CALL_UNIT','CRT_DEV_PROP_GRANT_CALL_ABBREVATION')),
    JSON_OBJECT('JOIN_STATUS', JSON_ARRAY('COL_DEV_PROP_STATUS','CRT_DEV_PROPOSAL_STATUS')),
    JSON_OBJECT('JOIN_MASTER_PROPOSAL', JSON_ARRAY('COL_MASTER_PROPOSAL','CRT_MASTER_PROPOSAL')),
    JSON_OBJECT('JOIN_PROPOSAL_KEY_PERSONS', JSON_ARRAY('COL_DEV_PROPOSAL_KEY_PERSONS','CRT_DEV_PROPSAL_KEY_PERSONS')),
    JSON_OBJECT('JOIN_PROPOSAL_TYPE', JSON_ARRAY('COL_DEV_PROPOSAL_TYPE','CRT_DEV_PROPOSAL_TYPE')),
	JSON_OBJECT('JOIN_PROPOSAL_CATEGORY', JSON_ARRAY('COL_DEV_PROPOSAL_CATEGORY','CRT_DEV_PROPOSAL_CATEGORY')),
	JSON_OBJECT('JOIN_PROPOSAL_SPL_REVIEW', JSON_ARRAY('COL_DEV_PROPOSAL_SPL_REVIEW_PROTOCOL', 'CRT_DEV_PROPOSAL_SPL_REVIEW_PROTOCOL')),
	JSON_OBJECT('JOIN_PROPOSAL_RESEARCH_AREAS', JSON_ARRAY('COL_DEV_PROPOSAL_RESEARCH_AREAS', 'CRT_DEV_PROPOSAL_RESEARCH_AREAS')),
	JSON_OBJECT('JOIN_PROPOSAL_PROJECT_TEAM', JSON_ARRAY('COL_DEV_PROPOSAL_PROJECT_TEAM', 'CRT_DEV_PROPOSAL_PROJECT_TEAM')),
	JSON_OBJECT('JOIN_GRANT_FUNDING_SCHEME', JSON_ARRAY('COL_DEV_PROP_FUNDING_SCHEME', 'CRT_DEV_PROP_FUNDING_SCHEME')),
	JSON_OBJECT('JOIN_PROPOSAL_KEYWORDS', JSON_ARRAY('COL_DEV_PROPOSAL_KEYWORD','CRT_DEV_PROPOSAL_KEYWORD')),
	JSON_OBJECT('JOIN_PROPOSAL_ORGANIZATION', JSON_ARRAY('COL_DEV_PROPOSAL_ORGANIZATION','CRT_DEV_PROPOSAL_ORGANIZATION')),
    JSON_OBJECT('JOIN_IP_STATUS', JSON_ARRAY('COL_DEV_IP_STATUS','CRT_DEV_IP_STATUS')),
    JSON_OBJECT('JOIN_GRANT_CALL_JSON', JSON_ARRAY('COL_DEV_PROP_GRANT_CALL_ABBREVATION'))
    );

  SELECT FN_PREPARE_DASHBOARD_JOINS(@AV_DISPLAY_LIST, @AV_FILTER_JSON, @JOIN_KEY_MAP, @JOIN_QUERY_MAP,'JOIN') INTO @JOIN_QUERY;
-- PREPARE JOIN QUERY: END

-- PREPARE TAB QUERY: START

  SET @TAB_QUERY_MAP = JSON_OBJECT(
        'MY_PROPOSALS', CONCAT(' T8.PERSON_ID = ''',AV_PERSON_ID,''' AND T8.PROP_PERSON_ROLE_ID = 3'),
		'MY_REVIEW_PENDING_PROPOSAL',CONCAT(' ((T10.REVIEWER_PERSON_ID = ''',AV_PERSON_ID,'''  AND T10.PRE_REVIEW_STATUS_CODE = ''1'' AND 
                T10.PRE_REVIEW_TYPE_CODE = ''1'' AND T10.MODULE_ITEM_CODE = 3)
                        OR (T11.REVIEW_STATUS_CODE = 1 AND T11.REVIEWER_PERSON_ID = ''',AV_PERSON_ID,''' )
                        OR (T12.IS_WORKFLOW_ACTIVE = ''Y'' AND T13.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''  AND  
                        T13.APPROVAL_STATUS = ''W''))
                        OR (T3.PERSON_ID = ''',AV_PERSON_ID,''' AND T1.STATUS_CODE IN(38))' ),
						
        'REVIEW_COMPLETED_PROPOSALS', CONCAT(' (T1.STATUS_CODE IN(28,31,18,21,11) AND T1.HOME_UNIT_NUMBER IN
                        ((SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
                        UNION
                        (SELECT DISTINCT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND UNIT_ADMINISTRATOR_TYPE_CODE = 3))) ' ),
        'ALL_PROPOSALS', CONCAT(' (((T14.PERSON_ID = ''',AV_PERSON_ID,''' AND  T14.PROP_PERSON_ROLE_ID IN(3,9)) OR T3.PERSON_ID = ''',AV_PERSON_ID,''' OR T1.HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM    UNIT_ADMINISTRATOR WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND UNIT_ADMINISTRATOR_TYPE_CODE = 3)
                        OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP) AND (T1.GRANT_HEADER_ID IS NULL OR T6.HOME_UNIT_NUMBER = (SELECT VALUE FROM PARAMETER WHERE PARAMETER_NAME = ''ROOT_UNIT'')))
                        OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP) AND (T1.GRANT_HEADER_ID IS NOT NULL AND T6.HOME_UNIT_NUMBER <> (SELECT VALUE FROM PARAMETER WHERE PARAMETER_NAME = ''ROOT_UNIT'')))
                        OR T6.HOME_UNIT_NUMBER IN(SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP_PROPOSAL_GM)))' ),
						
        'REVIEW_INPROGRESS', CONCAT(' (T1.STATUS_CODE NOT IN(1,3,4,5,6,7,9,10,11,12,20,22,24,29,30) AND T1.HOME_UNIT_NUMBER IN
                        ((SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
                        UNION
                        (SELECT DISTINCT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND UNIT_ADMINISTRATOR_TYPE_CODE = 3))) ' )
		);

SET @TAB_BASE_JOIN = '';
IF AV_TAB_TYPE = 'ALL_PROPOSALS' THEN
    SET @TAB_BASE_JOIN = '
        LEFT OUTER JOIN EPS_PROPOSAL_PERSON_ROLES T3 ON T1.PROPOSAL_ID = T3.PROPOSAL_ID  LEFT JOIN EPS_PROPOSAL_PERSONS T14 ON T14.PROPOSAL_ID = T1.PROPOSAL_ID ';
ELSEIF AV_TAB_TYPE = 'MY_REVIEW_PENDING_PROPOSAL' THEN
    SET @TAB_BASE_JOIN = CONCAT(
        ' LEFT JOIN (
            SELECT *
            FROM PRE_REVIEW
            WHERE PRE_REVIEW_ID IN (
                SELECT MAX(PR.PRE_REVIEW_ID)
                FROM PRE_REVIEW PR
                WHERE PR.REVIEWER_PERSON_ID = ''', AV_PERSON_ID, '''
                  AND PR.PRE_REVIEW_STATUS_CODE = ''1''
                  AND PR.MODULE_ITEM_CODE = 3
                  AND PR.MODULE_SUB_ITEM_CODE = 0
                  AND PR.MODULE_SUB_ITEM_KEY = 0
                GROUP BY PR.MODULE_ITEM_KEY,
                         PR.REVIEWER_PERSON_ID,
                         PR.MODULE_ITEM_CODE,
                         PR.MODULE_SUB_ITEM_CODE,
                         PR.MODULE_SUB_ITEM_KEY
            )
        ) T10 ON T10.MODULE_ITEM_KEY = T1.PROPOSAL_ID AND T10.MODULE_ITEM_CODE = 3 AND T10.MODULE_SUB_ITEM_CODE = 0 AND T10.MODULE_SUB_ITEM_KEY = 0
        LEFT OUTER JOIN PROPOSAL_REVIEW T11 ON T11.PROPOSAL_ID = T1.PROPOSAL_ID
        LEFT OUTER JOIN WORKFLOW T12 ON T12.MODULE_ITEM_ID = CAST(T1.PROPOSAL_ID AS CHAR) AND T12.MODULE_CODE = 3
        LEFT OUTER JOIN WORKFLOW_DETAIL T13 ON T13.WORKFLOW_ID = T12.WORKFLOW_ID
        LEFT OUTER JOIN EPS_PROPOSAL_PERSON_ROLES T3 ON T1.PROPOSAL_ID = T3.PROPOSAL_ID AND T3.ROLE_ID = 650'
    );
END IF;
    SET @TAB_QUERY = JSON_UNQUOTE(JSON_EXTRACT(@TAB_QUERY_MAP, CONCAT('$.', AV_TAB_TYPE)));

-- EXTRACT ALL JSON DATA INTO VARIABLES: START

SET SESSION group_concat_max_len = 100000;

SET @PI_IS_EMP =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_PI.isEmp'));

SET @KEY_PERSON_IS_EMP =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPSAL_KEY_PERSONS.isEmp'));

SET @PROJECT_TEAM_IS_EMP =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_PROJECT_TEAM.isEmp'));

SET @SPL_REVIEW_PROTOCOL =
    LOWER(JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_SPL_REVIEW_PROTOCOL')));

SET @START_DATE_FROM =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_START_DATE.fromDate'));
SET @START_DATE_TO =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_START_DATE.toDate'));

SET @END_DATE_FROM =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_END_DATE.fromDate'));
SET @END_DATE_TO =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_END_DATE.toDate'));

SET @INTERNAL_DL_FROM =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROP_INTERNAL_DEADLINE_DATE.fromDate'));
SET @INTERNAL_DL_TO =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROP_INTERNAL_DEADLINE_DATE.toDate'));

SET @SPONSOR_DL_FROM =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROP_SPONSOR_DEADLINE_DATE.fromDate'));
SET @SPONSOR_DL_TO =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROP_SPONSOR_DEADLINE_DATE.toDate'));

SET @PROPOSAL_ID_VAL =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON,'$.CRT_DEV_PROPOSAL_ID'));

SET @EXTERNAL_FUNDING_AGENCY_ID_VAL =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON,'$.CRT_EXTERNAL_FUNDING_AGENCY_ID'));

SET @PROGRAM_ANNOUNCEMENT_NO_VAL =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON,'$.CRT_DEV_PROPO_PROGRAM_ANNOUNCEMENT_NUMBER'));

SET @GRANT_CALL_TITLE_VAL = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPO_GRANT_CALL_TITLE'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @CFDA_NUMBER_VAL =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON,'$.CRT_DEV_PROP_CFDA_NUMBER'));

SET @PROPOSAL_TITLE_VAL =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON,'$.CRT_DEV_PROPOSAL_TITLE'));

SET @GRANT_CALL_ABBR_VAL =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON,'$.CRT_DEV_PROP_GRANT_CALL_ABBREVATION'));

SET @MASTER_PROPOSAL_VAL =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON,'$.CRT_MASTER_PROPOSAL'));
	
SET @MASTER_PROPOSAL_AWARD_VAL =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON,'$.CRT_DEV_PROPOSAL_MASTER_AWARD'));

SET @KEYWORD_VAL =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON,'$.CRT_DEV_PROPOSAL_KEYWORD'));

SET @ORGANIZATION_VAL =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON,'$.CRT_DEV_PROPOSAL_ORGANIZATION'));

SET @RESEARCH_AREA_VAL = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_RESEARCH_AREAS'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @KEY_PERSON_VAL = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPSAL_KEY_PERSONS.values'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @KEY_PERSONS_ROLES_VAL = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_KEY_PERSON_ROLES'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @PI_PERSON_VAL = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_PI.values'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @PROJECT_PERSON_VAL = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_PROJECT_TEAM.values'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @PROP_TYPE_CODE = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_TYPE'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @PROP_SPONSOR_CODE = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROP_SPONSOR'),
        '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @PROP_PRIME_SPONSOR_CODE = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROP_PRIME_SPONSOR'),
        '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @PROP_FUNDING_SCHEME = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROP_FUNDING_SCHEME'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @GRANT_CALL_UNIT = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_GRANT_CALL_UNIT'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @IP_STATUS_FILTER_VAL = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_IP_STATUS'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @PROP_ACTIVITY_TYPE = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_CATEGORY'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @PROP_STATUS_CODE = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROPOSAL_STATUS'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @IS_INACTIVE = 0;

IF @PROP_STATUS_CODE IS NOT NULL AND @PROP_STATUS_CODE <> '' THEN
    IF LOCATE('''35''', @PROP_STATUS_CODE) > 0 THEN
        SET @IS_INACTIVE = 1;
    END IF;
END IF;

SET @PROP_HOME_UNIT = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROP_HOME_UNIT_NAME'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

SET @PROP_AWARD_TYPE = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_DEV_PROP_AWARD_TYPE'),
        '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
    HAVING COUNT(*) > 0
);

-- EXTRACT ALL JSON DATA INTO VARIABLES: END


-- PREPARE CRITERIA QUERY: START

IF (@KEY_PERSON_VAL IS NOT NULL AND TRIM(@KEY_PERSON_VAL) != ''
    AND @KEY_PERSONS_ROLES_VAL IS NOT NULL AND TRIM(@KEY_PERSONS_ROLES_VAL) != '') THEN
    SET @PROPSAL_KEY_PERSON_CRT = CONCAT('(
    ( ''', @KEY_PERSON_IS_EMP, ''' = ''true''  AND EXISTS (SELECT 1 FROM EPS_PROPOSAL_PERSONS WHERE PROPOSAL_ID = T1.PROPOSAL_ID AND PERSON_ID IN (', @KEY_PERSON_VAL, ') AND PROP_PERSON_ROLE_ID IN (', @KEY_PERSONS_ROLES_VAL, ') ))
     OR
    ( ''', @KEY_PERSON_IS_EMP, ''' = ''false'' AND EXISTS (SELECT 1 FROM EPS_PROPOSAL_PERSONS WHERE PROPOSAL_ID = T1.PROPOSAL_ID AND ROLODEX_ID IN (', @KEY_PERSON_VAL, ') AND PROP_PERSON_ROLE_ID IN (', @KEY_PERSONS_ROLES_VAL, ') ))
)');
 
ELSEIF (@KEY_PERSON_VAL IS NOT NULL AND TRIM(@KEY_PERSON_VAL) != '') THEN
    SET @PROPSAL_KEY_PERSON_CRT = CONCAT('(
    ( ''', @KEY_PERSON_IS_EMP, ''' = ''true''  AND EXISTS (SELECT 1 FROM EPS_PROPOSAL_PERSONS WHERE PROPOSAL_ID = T1.PROPOSAL_ID AND PERSON_ID IN (', @KEY_PERSON_VAL, ') ))
     OR
    ( ''', @KEY_PERSON_IS_EMP, ''' = ''false'' AND EXISTS (SELECT 1 FROM EPS_PROPOSAL_PERSONS WHERE PROPOSAL_ID = T1.PROPOSAL_ID AND ROLODEX_ID IN (', @KEY_PERSON_VAL, ') ))
)');
 
ELSEIF (@KEY_PERSONS_ROLES_VAL IS NOT NULL AND TRIM(@KEY_PERSONS_ROLES_VAL) != '') THEN
    SET @PROPSAL_KEY_PERSONS_ROLES_CRT = CONCAT('(EXISTS(SELECT 1 FROM EPS_PROPOSAL_PERSONS WHERE PROPOSAL_ID = T1.PROPOSAL_ID AND PROP_PERSON_ROLE_ID IN (', @KEY_PERSONS_ROLES_VAL, ') ))');
END IF;

SET @PROPOSAL_SPECIAL_REVIEW_CRT = CONCAT('(EXISTS (SELECT 1 FROM PROPOSAL_SPECIAL_REVIEW_JSON ASR WHERE ASR.PROPOSAL_ID = T1.PROPOSAL_ID AND LOWER(ASR.SPECIAL_REVIEWS) LIKE LOWER(''%', @SPL_REVIEW_PROTOCOL, '%'')))');

SET @CRT_PROPOSAL_PI_CRT = CONCAT('(
    ( ''', @PI_IS_EMP, ''' = ''true''  AND EXISTS (SELECT 1 FROM EPS_PROPOSAL_PERSONS WHERE PROPOSAL_ID = T1.PROPOSAL_ID AND PROP_PERSON_ROLE_ID = 3 AND PERSON_ID   IN (', @PI_PERSON_VAL, ') ))
     OR
    ( ''', @PI_IS_EMP, ''' = ''false'' AND EXISTS (SELECT 1 FROM EPS_PROPOSAL_PERSONS WHERE PROPOSAL_ID = T1.PROPOSAL_ID AND PROP_PERSON_ROLE_ID = 3 AND ROLODEX_ID IN (', @PI_PERSON_VAL, ') ))
)');

SET @CRT_DEV_PROP_PROJECT_TEAM_CRT = CONCAT('(
    ( ''', @PROJECT_TEAM_IS_EMP, ''' = ''true''  AND EXISTS (SELECT 1 FROM EPS_PROPOSAL_PROJECT_TEAM APT2 WHERE APT2.PROPOSAL_ID = T1.PROPOSAL_ID AND APT2.NON_EMPLOYEE_FLAG = ''N'' AND APT2.PERSON_ID IN (', @PROJECT_PERSON_VAL, ') ))
     OR
    ( ''', @PROJECT_TEAM_IS_EMP, ''' = ''false'' AND EXISTS (SELECT 1 FROM EPS_PROPOSAL_PROJECT_TEAM APT2 WHERE APT2.PROPOSAL_ID = T1.PROPOSAL_ID AND APT2.NON_EMPLOYEE_FLAG = ''Y'' AND APT2.PERSON_ID IN (', @PROJECT_PERSON_VAL, ') ))
)');

IF @START_DATE_FROM IS NOT NULL AND @START_DATE_TO IS NOT NULL THEN
    SET @PROPOSAL_START_DATE_CRT = CONCAT('( T1.PROPOSAL_ID IS NOT NULL AND CAST(T1.START_DATE AS DATE) BETWEEN ''', @START_DATE_FROM, ''' AND ''', @START_DATE_TO, ''' )');
ELSEIF @START_DATE_FROM IS NOT NULL AND @START_DATE_TO IS NULL THEN
    SET @PROPOSAL_START_DATE_CRT = CONCAT('( T1.PROPOSAL_ID IS NOT NULL AND CAST(T1.START_DATE AS DATE) >= ''', @START_DATE_FROM, ''' )');
ELSEIF @START_DATE_FROM IS NULL AND @START_DATE_TO IS NOT NULL THEN
    SET @PROPOSAL_START_DATE_CRT = CONCAT('( T1.PROPOSAL_ID IS NOT NULL AND CAST(T1.START_DATE AS DATE) <= ''', @START_DATE_TO, ''' )');
END IF;

IF @END_DATE_FROM IS NOT NULL AND @END_DATE_TO IS NOT NULL THEN
    SET @PROPOSAL_END_DATE_CRT = CONCAT('( T1.PROPOSAL_ID IS NOT NULL AND CAST(T1.END_DATE AS DATE) BETWEEN ''', @END_DATE_FROM, ''' AND ''', @END_DATE_TO, ''' )');
ELSEIF @END_DATE_FROM IS NOT NULL AND @END_DATE_TO IS NULL THEN
    SET @PROPOSAL_END_DATE_CRT = CONCAT('( T1.PROPOSAL_ID IS NOT NULL AND CAST(T1.END_DATE AS DATE) >= ''', @END_DATE_FROM, ''' )');
ELSEIF @END_DATE_FROM IS NULL AND @END_DATE_TO IS NOT NULL THEN
    SET @PROPOSAL_END_DATE_CRT = CONCAT('( T1.PROPOSAL_ID IS NOT NULL AND CAST(T1.END_DATE AS DATE) <= ''', @END_DATE_TO, ''' )');
END IF;

IF @INTERNAL_DL_FROM IS NOT NULL AND @INTERNAL_DL_TO IS NOT NULL THEN
    SET @PROPOSAL_INTERNAL_DEADLINE_DATE_CRT = CONCAT('( T1.PROPOSAL_ID IS NOT NULL AND CAST(T1.INTERNAL_DEADLINE_DATE AS DATE) BETWEEN ''', @INTERNAL_DL_FROM, ''' AND ''', @INTERNAL_DL_TO, ''' )');
ELSEIF @INTERNAL_DL_FROM IS NOT NULL AND @INTERNAL_DL_TO IS NULL THEN
    SET @PROPOSAL_INTERNAL_DEADLINE_DATE_CRT = CONCAT('( T1.PROPOSAL_ID IS NOT NULL AND CAST(T1.INTERNAL_DEADLINE_DATE AS DATE) >= ''', @INTERNAL_DL_FROM, ''' )');
ELSEIF @INTERNAL_DL_FROM IS NULL AND @INTERNAL_DL_TO IS NOT NULL THEN
    SET @PROPOSAL_INTERNAL_DEADLINE_DATE_CRT = CONCAT('( T1.PROPOSAL_ID IS NOT NULL AND CAST(T1.INTERNAL_DEADLINE_DATE AS DATE) <= ''', @INTERNAL_DL_TO, ''' )');
END IF;

IF @SPONSOR_DL_FROM IS NOT NULL AND @SPONSOR_DL_TO IS NOT NULL THEN
    SET @PROPOSAL_SPONSOR_DEADLINE_DATE_CRT = CONCAT('( T1.PROPOSAL_ID IS NOT NULL AND CAST(T1.SPONSOR_DEADLINE_DATE AS DATE) BETWEEN ''', @SPONSOR_DL_FROM, ''' AND ''', @SPONSOR_DL_TO, ''' )');
ELSEIF @SPONSOR_DL_FROM IS NOT NULL AND @SPONSOR_DL_TO IS NULL THEN
    SET @PROPOSAL_SPONSOR_DEADLINE_DATE_CRT = CONCAT('( T1.PROPOSAL_ID IS NOT NULL AND CAST(T1.SPONSOR_DEADLINE_DATE AS DATE) >= ''', @SPONSOR_DL_FROM, ''' )');
ELSEIF @SPONSOR_DL_FROM IS NULL AND @SPONSOR_DL_TO IS NOT NULL THEN
    SET @PROPOSAL_SPONSOR_DEADLINE_DATE_CRT = CONCAT('( T1.PROPOSAL_ID IS NOT NULL AND CAST(T1.SPONSOR_DEADLINE_DATE AS DATE) <= ''', @SPONSOR_DL_TO, ''' )');
END IF;

SET @CRITERIA_MAP = JSON_OBJECT(
    'CRT_DEV_PROPOSAL_ID',                   CONCAT('(T1.PROPOSAL_ID LIKE ''%', @PROPOSAL_ID_VAL, '%'')'),
    'CRT_EXTERNAL_FUNDING_AGENCY_ID',        CONCAT('(T1.EXTERNAL_FUNDING_AGENCY_ID IS NOT NULL AND T1.EXTERNAL_FUNDING_AGENCY_ID LIKE ''%', @EXTERNAL_FUNDING_AGENCY_ID_VAL, '%'')'),
    'CRT_DEV_PROPO_PROGRAM_ANNOUNCEMENT_NUMBER', CONCAT('(T1.PROGRAM_ANNOUNCEMENT_NUMBER LIKE ''%', @PROGRAM_ANNOUNCEMENT_NO_VAL, '%'')'),
    'CRT_DEV_PROPO_GRANT_CALL_TITLE', CONCAT('(', IFNULL(CONCAT('T1.GRANT_HEADER_ID IN (', @GRANT_CALL_TITLE_VAL, ')'), '1=1'), ')'),
    'CRT_DEV_PROP_CFDA_NUMBER',              CONCAT('(T1.CFDA_NUMBER LIKE ''%', @CFDA_NUMBER_VAL, '%'')'),
    'CRT_DEV_PROPOSAL_TITLE',                CONCAT('(T1.TITLE LIKE ''%', @PROPOSAL_TITLE_VAL, '%'')'),
    'CRT_DEV_PROPOSAL_TYPE',        CONCAT('(', IFNULL(CONCAT('T1.TYPE_CODE IN (', @PROP_TYPE_CODE, ')'), '1=1'), ')'),
    'CRT_DEV_PROP_AWARD_TYPE',      CONCAT('(', IFNULL(CONCAT('T1.AWARD_TYPE_CODE IN (', @PROP_AWARD_TYPE, ')'), '1=1'), ')'),
    'CRT_DEV_PROP_HOME_UNIT_NAME',  CONCAT('(', IFNULL(CONCAT('T1.HOME_UNIT_NUMBER IN (', @PROP_HOME_UNIT, ')'), '1=1'), ')'),
    'CRT_DEV_PROP_SPONSOR',         CONCAT('(', IFNULL(CONCAT('T1.SPONSOR_CODE IN (', @PROP_SPONSOR_CODE, ')'), '1=1'), ')'),
    'CRT_DEV_PROP_PRIME_SPONSOR',   CONCAT('(', IFNULL(CONCAT('T1.PRIME_SPONSOR_CODE IN (', @PROP_PRIME_SPONSOR_CODE, ')'), '1=1'), ')'),
    'CRT_DEV_PROP_FUNDING_SCHEME',  CONCAT('(', IFNULL(CONCAT('FS.FUNDING_SCHEME_CODE IN (', @PROP_FUNDING_SCHEME, ')'), '1=1'), ')'),
    'CRT_DEV_PROPOSAL_GRANT_CALL_UNIT', CONCAT('(', IFNULL(CONCAT('GC.HOME_UNIT_NUMBER IN (', @GRANT_CALL_UNIT, ')'), '1=1'), ')'),
    'CRT_DEV_PROPOSAL_CATEGORY',    CONCAT('(', IFNULL(CONCAT('T1.ACTIVITY_TYPE_CODE IN (', @PROP_ACTIVITY_TYPE, ')'), '1=1'), ')'),
    'CRT_DEV_PROPOSAL_STATUS',      CONCAT('(', IFNULL(CONCAT('T1.STATUS_CODE IN (', @PROP_STATUS_CODE, ')'), '1=1'), ')'),
    'CRT_DEV_PROP_GRANT_CALL_ABBREVATION', CONCAT('(GC.ABBREVIATION LIKE ''%', @GRANT_CALL_ABBR_VAL, '%'')'),
    'CRT_MASTER_PROPOSAL',          CONCAT('(T1.BASE_PROPOSAL_NUMBER LIKE ''%', @MASTER_PROPOSAL_VAL, '%'')'),
	'CRT_DEV_PROPOSAL_MASTER_AWARD',          CONCAT('(T1.AWARD_NUMBER LIKE ''%', @MASTER_PROPOSAL_AWARD_VAL, '%'')'),
    'CRT_DEV_PROPOSAL_PI',          @CRT_PROPOSAL_PI_CRT,
    'CRT_DEV_PROPSAL_KEY_PERSONS',   IFNULL(@PROPSAL_KEY_PERSON_CRT, '1=1'),
    'CRT_DEV_PROPOSAL_KEY_PERSON_ROLES',  IFNULL( @PROPSAL_KEY_PERSONS_ROLES_CRT, '1=1'),
    'CRT_DEV_PROPOSAL_START_DATE',  @PROPOSAL_START_DATE_CRT,
    'CRT_DEV_PROPOSAL_END_DATE',    @PROPOSAL_END_DATE_CRT,
    'CRT_DEV_PROP_INTERNAL_DEADLINE_DATE',  @PROPOSAL_INTERNAL_DEADLINE_DATE_CRT,
    'CRT_DEV_PROP_SPONSOR_DEADLINE_DATE',   @PROPOSAL_SPONSOR_DEADLINE_DATE_CRT,
    'CRT_DEV_PROPOSAL_PROJECT_TEAM',        @CRT_DEV_PROP_PROJECT_TEAM_CRT,
    'CRT_DEV_PROPOSAL_SPL_REVIEW_PROTOCOL', @PROPOSAL_SPECIAL_REVIEW_CRT,
    'CRT_DEV_PROPOSAL_ORGANIZATION', CONCAT('(EXISTS (
            SELECT 1 
            FROM PROPOSAL_ORGANIZATION_FILTER PORG 
            WHERE PORG.PROPOSAL_ID = T1.PROPOSAL_ID 
            AND LOWER(PORG.ORGANIZATION) LIKE LOWER(''%', @ORGANIZATION_VAL, '%'')
        ))'),

    'CRT_DEV_PROPOSAL_KEYWORD', CONCAT('EXISTS (
        SELECT 1 FROM PROPOSAL_KEYWORDS_JSON PKJ
        WHERE PKJ.PROPOSAL_ID = T1.PROPOSAL_ID
          AND JSON_SEARCH(PKJ.KEYWORDS, ''one'',
              CONCAT(''%'', ''', @KEYWORD_VAL, ''', ''%''),
              NULL, ''$[*].KEYWORD'') IS NOT NULL
    )'),
	
	'CRT_DEV_PROPOSAL_RESEARCH_AREAS', CONCAT('(', IFNULL(CONCAT('EXISTS (SELECT 1 FROM EPS_PROPOSAL_RESRCH_AREAS ARA2 WHERE ARA2.PROPOSAL_ID = T1.PROPOSAL_ID AND ARA2.RESRCH_TYPE_AREA_CODE IN (', @RESEARCH_AREA_VAL, '))'), '1=1'), ')'),
    'CRT_DEV_IP_STATUS', CONCAT('(', IFNULL(CONCAT('EXISTS (
        SELECT 1 FROM PROPOSAL_ADMIN_DETAILS PAD
        INNER JOIN PROPOSAL T51 ON T51.PROPOSAL_ID = PAD.INST_PROPOSAL_ID
        WHERE PAD.DEV_PROPOSAL_ID = T1.PROPOSAL_ID
          AND T51.STATUS_CODE IN (', @IP_STATUS_FILTER_VAL, '))'), '1=1'), ')')
);

SELECT JSON_MERGE_PATCH(@CRITERIA_MAP, @CUST_CRITERIA_MAP) INTO @CRITERIA_MAP;
SELECT FN_PREPARE_DASHBOARD_CRITERIA(AV_FILTER_JSON, @CRITERIA_MAP) INTO LS_FILTER_CONDITION;
-- PREPARE CRITERIA QUERY: END

-- PREPARE FINAL AGGREGATED QUERY: START

IF AV_SORT_TYPE IS NULL OR AV_SORT_TYPE = '' THEN
    SET AV_SORT_TYPE = 'T1.UPDATE_TIMESTAMP DESC';
ELSE
    SET AV_SORT_TYPE =  CONCAT(AV_SORT_TYPE,',T1.UPDATE_TIMESTAMP DESC');
END IF;

    SET LS_DYN_SQL = CONCAT(@DYNAMIC_CTE,
        CASE WHEN AV_IS_COUNT = TRUE 
            THEN ' SELECT TOTAL_COUNT FROM (SELECT COUNT(DISTINCT T1.PROPOSAL_ID) AS TOTAL_COUNT'
            ELSE CONCAT(' SELECT ', IFNULL(@DISPLAY, '*'), ' FROM (SELECT DISTINCT ', IFNULL(@SELECT_STM, '*'))
        END, 
        ' FROM EPS_PROPOSAL T1
		LEFT  OUTER  JOIN EPS_PROPOSAL_PERSONS T8 ON T8.PROPOSAL_ID = T1.PROPOSAL_ID
		LEFT  OUTER  JOIN GRANT_CALL_HEADER T6 ON T6.GRANT_HEADER_ID = T1.GRANT_HEADER_ID
        ',IFNULL(@TAB_BASE_JOIN,''),'
        ',IFNULL(@JOIN_QUERY,''),'
        WHERE T1.DOCUMENT_STATUS_CODE <> 3
        AND ( @IS_INACTIVE = 1 OR T1.STATUS_CODE <> 35 )',
        CASE WHEN @TAB_QUERY IS NOT NULL AND @TAB_QUERY <> '' THEN CONCAT(' AND ( ', @TAB_QUERY, ')') ELSE '' END, 
        CASE WHEN LS_FILTER_CONDITION IS NOT NULL AND LS_FILTER_CONDITION != '' THEN CONCAT(' AND ', LS_FILTER_CONDITION) ELSE ''END,
        IF(AV_IS_COUNT = FALSE,CONCAT(' ORDER BY ', AV_SORT_TYPE, ' '),''),
        IF(AV_IS_COUNT = FALSE,CONCAT(' LIMIT ', AV_LIMIT, ' OFFSET ', AV_OFFSET),''),') T');
		
-- PREPARE FINAL AGGREGATED QUERY: END

    SET @QUERY_STATEMENT = LS_DYN_SQL;
    PREPARE EXECUTABLE_STATEMENT FROM @QUERY_STATEMENT;
    EXECUTE EXECUTABLE_STATEMENT;
    DEALLOCATE PREPARE EXECUTABLE_STATEMENT;
    SET SESSION optimizer_search_depth = old_depth;
END
