-- `FN_AWARD_SPONSOR_TYPE`;

CREATE FUNCTION `FN_AWARD_SPONSOR_TYPE`(
AV_AWARD_ID INT(10),
AV_SPONSOR_TYPE_CODE VARCHAR(3)
) RETURNS VARCHAR(6)
    DETERMINISTIC
BEGIN
DECLARE LI_COUNT INT;

SELECT COUNT(1) INTO LI_COUNT
FROM AWARD
WHERE AWARD_ID = AV_AWARD_ID
  AND SPONSOR_CODE IN (
    SELECT SPONSOR_CODE
    FROM SPONSOR
    WHERE SPONSOR_TYPE_CODE = AV_SPONSOR_TYPE_CODE
  );

IF LI_COUNT = 1 THEN
   RETURN 'TRUE';
END IF;

RETURN 'FALSE';
END
