CREATE 
VIEW `EPS_PROPOSAL_PERSONNEL_V` AS
    SELECT DISTINCT
        `BP`.`BUDGET_HEADER_ID` AS `BUDGET_HEADER_ID`,
        COALESCE(`BPP`.`PERSON_NAME`,
                `P`.`FULL_NAME`,
                `R`.`FULL_NAME`) AS `BUDGET_PERSONNEL_NAME`,
        `JC`.`JOB_TITLE` AS `BUDGET_PERSONNEL_JOB_TYPE`,
        `AP`.`DESCRIPTION` AS `BUDGET_PERSONNEL_APPOINTMENT_TYPE`
    FROM
        (((((((`BUDGET_PERIOD` `BP`
        LEFT JOIN `BUDGET_DETAIL` `BD` ON ((`BD`.`BUDGET_PERIOD_ID` = `BP`.`BUDGET_PERIOD_ID`)))
        LEFT JOIN `BUDGET_PERSON_DETAIL` `BPD` ON ((`BPD`.`BUDGET_DETAILS_ID` = `BD`.`BUDGET_DETAILS_ID`)))
        LEFT JOIN `BUDGET_PERSONS` `BPP` ON ((`BPP`.`BUDGET_PERSON_ID` = `BPD`.`BUDGET_PERSON_ID`)))
        LEFT JOIN `PERSON` `P` ON ((`P`.`PERSON_ID` = `BPP`.`PERSON_ID`)))
        LEFT JOIN `ROLODEX` `R` ON ((`R`.`ROLODEX_ID` = `BPP`.`ROLODEX_ID`)))
        LEFT JOIN `JOB_CODE` `JC` ON ((`JC`.`JOB_CODE` = `BPP`.`JOB_CODE`)))
        LEFT JOIN `APPOINTMENT_TYPE` `AP` ON ((`AP`.`APPOINTMENT_TYPE_CODE` = `BPP`.`APPOINTMENT_TYPE_CODE`)))
    WHERE
        (`JC`.`JOB_TITLE` IS NOT NULL)
