CREATE 
VIEW `EXTERNAL_REVIEWERS_DATA_REPORT_V` AS
    SELECT 
        `ER`.`EXTERNAL_REVIEWER_ID` AS `REVIEWER_ID`,
        `ER`.`FULL_NAME` AS `REVIEWER_NAME`,
        `ER`.`EMAIL_ADDRESS_PRIMARY` AS `PRIMARY_EMAIL`,
        `ERE`.`HI_INDEX` AS `H_INDEX`,
        `ER`.`DEPARTMENT` AS `DEPARTMENT`,
        `ERA`.`DESCRIPTION` AS `AFFILIATED_INSTITUTION`,
        DATE_FORMAT(`ER`.`AGREEMENT_START_DATE`, '%d/%m/%Y') AS `AGREEMENT_SIGNED_DATE`,
        DATE_FORMAT(`ER`.`AGREEMENT_END_DATE`, '%d/%m/%Y') AS `AGREEMENT_EXPIRY_DATE`,
        `ERAR`.`DESCRIPTION` AS `ACADEMIC_RANK`,
        `C`.`COUNTRY_NAME` AS `COUNTRY`,
        GROUP_CONCAT(DISTINCT `ESK`.`DESCRIPTION`
            SEPARATOR ', ') AS `SPECIALISM_KEYWORDS`,
        `RR`.`DESCRIPTION` AS `USER_ACCESS`,
        `ER_TYPE`.`DESCRIPTION` AS `ERM_REVIEW_TYPE`,
        `EXTR`.`DESCRIPTION` AS `ERM_REVIEW_TITLE`,
        `ER_STATUS`.`DESCRIPTION` AS `ERM_REVIEW_STATUS`,
        `ERV_STATUS`.`DESCRIPTION` AS `REVIEWER_REVIEW_STATUS`,
        `ERRS`.`DESCRIPTION` AS `REVIEWER_ASSIGNMENT_STATUS`,
        CONCAT(`EXTR`.`MODULE_ITEM_KEY`,
                '-',
                LPAD(`EXTR`.`VERSION_NUMBER`, 3, 0)) AS `EXT_REVIEW_NUMBER`,
        `PS`.`DESCRIPTION` AS `REVIEWER_STATUS`
    FROM
        (((((((((((((((`EXTERNAL_REVIEWER` `ER`
        LEFT JOIN `EXTERNAL_REVIEWER_EXT` `ERE` ON ((`ER`.`EXTERNAL_REVIEWER_ID` = `ERE`.`EXTERNAL_REVIEWER_ID`)))
        LEFT JOIN `EXT_REVIEWER_AFFILIATION` `ERA` ON ((`ER`.`AFFILATION_INSTITUITION_CODE` = `ERA`.`AFFILATION_INSTITUITION_CODE`)))
        LEFT JOIN `EXT_REVIEWER_ACADEMIC_RANK` `ERAR` ON ((`ER`.`ACADEMIC_RANK_CODE` = `ERAR`.`ACADEMIC_RANK_CODE`)))
        LEFT JOIN `COUNTRY` `C` ON ((`ER`.`COUNTRY_CODE` = `C`.`COUNTRY_CODE`)))
        LEFT JOIN `EXTERNAL_REVIEWER_SPECIALIZATION` `ERS` ON ((`ER`.`EXTERNAL_REVIEWER_ID` = `ERS`.`EXTERNAL_REVIEWER_ID`)))
        LEFT JOIN `EXT_SPECIALISM_KEYWORD` `ESK` ON ((`ERS`.`SPECIALIZATION_CODE` = `ESK`.`SPECIALISM_KEYWORD_CODE`)))
        LEFT JOIN `EXT_REVIEW_REVIEWERS` `ERR` ON ((`ER`.`EXTERNAL_REVIEWER_ID` = `ERR`.`EXTERNAL_REVIEWER_ID`)))
        LEFT JOIN `EXT_REVIEW_REVIEWERS_STATUS` `ERRS` ON ((`ERR`.`EXT_REVIEW_REVIEWERS_STATUS_CODE` = `ERRS`.`EXT_REVIEW_REVIEWERS_STATUS_CODE`)))
        LEFT JOIN `EXTERNAL_REVIEWER_RIGHTS` `ER_RIGHTS` ON ((`ER`.`EXTERNAL_REVIEWER_ID` = `ER_RIGHTS`.`EXTERNAL_REVIEWER_ID`)))
        LEFT JOIN `REVIEWER_RIGHTS` `RR` ON ((`ER_RIGHTS`.`REVIEWER_RIGHTS_ID` = `RR`.`REVIEWER_RIGHTS_ID`)))
        LEFT JOIN `EXT_REVIEW` `EXTR` ON ((`ERR`.`EXT_REVIEW_ID` = `EXTR`.`EXT_REVIEW_ID`)))
        LEFT JOIN `EXT_REVIEW_STATUS` `ER_STATUS` ON ((`ER_STATUS`.`EXT_REVIEW_STATUS_CODE` = `EXTR`.`EXT_REVIEW_STATUS_CODE`)))
        LEFT JOIN `EXT_REVIEWERS_STATUS` `ERV_STATUS` ON ((`ERR`.`EXT_REVIEWERS_STATUS_CODE` = `ERV_STATUS`.`EXT_REVIEWERS_STATUS_CODE`)))
        LEFT JOIN `EXT_REVIEW_SERVICE_TYPE` `ER_TYPE` ON ((`EXTR`.`EXT_REVIEW_SERVICE_TYPE_CODE` = `ER_TYPE`.`EXT_REVIEW_SERVICE_TYPE_CODE`)))
        LEFT JOIN `PERSON_STATUS` `PS` ON ((`PS`.`PERSON_STATUS_CODE` = `ER`.`STATUS`)))
    GROUP BY `ER`.`EXTERNAL_REVIEWER_ID` , `EXTR`.`EXT_REVIEW_ID`
