CREATE 
VIEW `WORKFLOW_DETAILED_V` AS
    SELECT 
        (CASE `W`.`MODULE_CODE`
            WHEN 1 THEN 'Award'
            WHEN 3 THEN 'Development Proposal'
            WHEN 16 THEN 'Progress Report'
        END) AS `MODULE`,
        `W`.`MODULE_ITEM_ID` AS `RECORD_ID`,
        (CASE `W`.`MODULE_CODE`
            WHEN 1 THEN `A`.`AWARD_NUMBER`
            WHEN 3 THEN `PD`.`PROPOSAL_ID`
            WHEN 16 THEN `PR`.`PROGRESS_REPORT_NUMBER`
        END) AS `RECORD_NUMBER`,
        (CASE `W`.`MODULE_CODE`
            WHEN 1 THEN `A`.`TITLE`
            WHEN 3 THEN `PD`.`TITLE`
            WHEN 16 THEN `PR`.`TITLE`
        END) AS `TITLE`,
        `W`.`WORKFLOW_SEQUENCE` AS `ROUTING_VERSION`,
        (CASE `W`.`MODULE_CODE`
            WHEN 1 THEN `S`.`DESCRIPTION`
            WHEN 3 THEN `PS`.`DESCRIPTION`
            WHEN 16 THEN `PRS`.`DESCRIPTION`
        END) AS `ROUTING_STATUS`,
        `WD`.`STOP_NAME` AS `STOP_NAME`,
        `WD`.`APPROVER_PERSON_NAME` AS `PRIMARY_APPROVER`,
        (CASE
            WHEN (`WD`.`APPROVAL_STATUS` NOT IN ('W' , 'T')) THEN `AP`.`FULL_NAME`
            ELSE ''
        END) AS `ACTION_TAKEN_BY`,
        `WS`.`DESCRIPTION` AS `APPROVER_STATUSES`,
        `WD`.`APPROVAL_COMMENT` AS `APPROVER_COMMENTS`,
        `W`.`WORKFLOW_START_DATE` AS `FIRST_WORKFLOW_START_DATE`,
        `SP`.`FULL_NAME` AS `SUBMITTED_BY`,
        `WD`.`MAP_NAME` AS `MAP_NAME`,
        `A`.`LEAD_UNIT_NUMBER` AS `AWARD_LEAD_UNIT_NUMBER`,
        `PD`.`HOME_UNIT_NUMBER` AS `PROPOSAL_LEAD_UNIT_NUMBER`,
        `PR`.`LEAD_UNIT_NUMBER` AS `PR_LEAD_UNIT_NUMBER`,
        `wd`.`MAP_NUMBER` AS `MAP_NUMBER`,
        `wd`.`APPROVAL_STOP_NUMBER` AS `APPROVAL_STOP_NUMBER`
    FROM
        ((((((((((`WORKFLOW` `W`
        INNER JOIN `WORKFLOW_DETAIL` `WD` ON ((`W`.`WORKFLOW_ID` = `WD`.`WORKFLOW_ID`)))
        LEFT JOIN `WORKFLOW_STATUS` `WS` ON ((`WS`.`APPROVAL_STATUS` = `WD`.`APPROVAL_STATUS`)))
        LEFT JOIN `AWARD` `A` ON (((`A`.`AWARD_ID` = `W`.`MODULE_ITEM_ID`)
            AND (`W`.`MODULE_CODE` = 1))))
        LEFT JOIN `AWARD_STATUS` `S` ON ((`S`.`STATUS_CODE` = `A`.`STATUS_CODE`)))
        LEFT JOIN `EPS_PROPOSAL` `PD` ON (((`PD`.`PROPOSAL_ID` = `W`.`MODULE_ITEM_ID`)
            AND (`W`.`MODULE_CODE` = 3))))
        LEFT JOIN `EPS_PROPOSAL_STATUS` `PS` ON ((`PD`.`STATUS_CODE` = `PS`.`STATUS_CODE`)))
        LEFT JOIN (SELECT 
            `APR`.`PROGRESS_REPORT_STATUS_CODE` AS `PROGRESS_REPORT_STATUS_CODE`,
                `APR`.`PROGRESS_REPORT_ID` AS `PROGRESS_REPORT_ID`,
                `A`.`LEAD_UNIT_NUMBER` AS `LEAD_UNIT_NUMBER`,
                `APR`.`PROGRESS_REPORT_NUMBER` AS `PROGRESS_REPORT_NUMBER`,
                `APR`.`TITLE` AS `TITLE`
        FROM
            (`AWARD` `A`
        JOIN `AWARD_PROGRESS_REPORT` `APR` ON ((`APR`.`AWARD_ID` = `A`.`AWARD_ID`))))  `PR` ON (((`PR`.`PROGRESS_REPORT_ID` = `W`.`MODULE_ITEM_ID`)
            AND (`W`.`MODULE_CODE` = 16))))
        LEFT JOIN `PROGRESS_REPORT_STATUS` `PRS` ON ((`PRS`.`PROGRESS_REPORT_STATUS_CODE` = `PR`.`PROGRESS_REPORT_STATUS_CODE`)))
        LEFT JOIN `PERSON` `AP` ON ((`WD`.`UPDATE_USER` = `AP`.`USER_NAME`)))
        LEFT JOIN `PERSON` `SP` ON ((`W`.`WORKFLOW_START_PERSON` = `SP`.`PERSON_ID`)))
    WHERE
        ((`W`.`MODULE_CODE` IN (1 , 3, 16))
            AND (`W`.`IS_WORKFLOW_ACTIVE` = 'Y'))
    ORDER BY `w`.`MODULE_ITEM_ID` , `wd`.`MAP_NUMBER` , `wd`.`APPROVAL_STOP_NUMBER`
