CREATE PROCEDURE `GET_SERVICE_REQUEST_DASHBOARD_WIDGET_DATA`(
    IN AV_PERSON_ID VARCHAR(40),
    IN AV_IS_CHART VARCHAR(20),
    IN AV_CATEGORY_CODE VARCHAR(500),
    IN AV_STATUS_CODE VARCHAR(500),
    IN AV_PRIORITY_ID VARCHAR(100),
    IN AV_REPORTER_PERSON_ID VARCHAR(500),
    IN AV_UNIT_NUMBER VARCHAR(500),
    IN AV_DESCENT_FLAG VARCHAR(1),
    IN AV_ASSIGNEE_PERSON_ID VARCHAR(500),
    IN AV_CREATE_TIMESTAMP_FROM_DATE VARCHAR(30),
    IN AV_CREATE_TIMESTAMP_TO_DATE VARCHAR(30),
    IN AV_TYPE_CODE_FILTER VARCHAR(200),
    IN AV_OFFSET INT(10),
    IN AV_LIMIT INT(10),
    IN AV_SORT_TYPE VARCHAR(500)
)
BEGIN
    DECLARE LS_DYN_SQL LONGTEXT;
    DECLARE LS_FILTER_CONDITION LONGTEXT DEFAULT '';
    DECLARE LS_ACCESS_QUERY LONGTEXT DEFAULT '';
    DECLARE LS_SORT_TYPE VARCHAR(600) DEFAULT 'T1.UPDATE_TIMESTAMP DESC';

    SET SESSION time_zone = '+00:00';

    IF AV_SORT_TYPE IS NOT NULL AND AV_SORT_TYPE != '' THEN
        SET LS_SORT_TYPE = CONCAT(AV_SORT_TYPE, ',T1.UPDATE_TIMESTAMP DESC');
    END IF;

    -- Build optional filter conditions (applied in both chart and drill-down modes)
    IF AV_CATEGORY_CODE IS NOT NULL AND AV_CATEGORY_CODE != '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T1.CATEGORY_CODE IN (', AV_CATEGORY_CODE, '))');
    END IF;

    IF AV_STATUS_CODE IS NOT NULL AND AV_STATUS_CODE != '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T1.STATUS_CODE IN (', AV_STATUS_CODE, '))');
    END IF;

    IF AV_PRIORITY_ID IS NOT NULL AND AV_PRIORITY_ID != '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T1.PRIORITY_ID IN (', AV_PRIORITY_ID, '))');
    END IF;

    IF AV_REPORTER_PERSON_ID IS NOT NULL AND AV_REPORTER_PERSON_ID != '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T1.REPORTER_PERSON_ID IN (', AV_REPORTER_PERSON_ID, '))');
    END IF;

    IF AV_ASSIGNEE_PERSON_ID IS NOT NULL AND AV_ASSIGNEE_PERSON_ID != '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T1.ASSIGNEE_PERSON_ID IN (', AV_ASSIGNEE_PERSON_ID, '))');
    END IF;

    IF (AV_CREATE_TIMESTAMP_FROM_DATE IS NOT NULL AND AV_CREATE_TIMESTAMP_FROM_DATE != '')
        OR (AV_CREATE_TIMESTAMP_TO_DATE IS NOT NULL AND AV_CREATE_TIMESTAMP_TO_DATE != '') THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (',
            '(', QUOTE(AV_CREATE_TIMESTAMP_FROM_DATE), ' IS NULL AND CAST(T1.CREATE_TIMESTAMP AS DATE) <= ', QUOTE(AV_CREATE_TIMESTAMP_TO_DATE), ')',
            ' OR (', QUOTE(AV_CREATE_TIMESTAMP_TO_DATE), ' IS NULL AND CAST(T1.CREATE_TIMESTAMP AS DATE) >= ', QUOTE(AV_CREATE_TIMESTAMP_FROM_DATE), ')',
            ' OR (CAST(T1.CREATE_TIMESTAMP AS DATE) BETWEEN ', QUOTE(AV_CREATE_TIMESTAMP_FROM_DATE), ' AND ', QUOTE(AV_CREATE_TIMESTAMP_TO_DATE), ')',
            ')');
    END IF;

    -- Type filter: single code (drill-down bar click) or comma-quoted list (chart filter popup)
    IF AV_TYPE_CODE_FILTER IS NOT NULL AND AV_TYPE_CODE_FILTER != '' THEN
        IF INSTR(AV_TYPE_CODE_FILTER, ',') > 0 OR LEFT(TRIM(AV_TYPE_CODE_FILTER), 1) = '''' THEN
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T1.TYPE_CODE IN (', AV_TYPE_CODE_FILTER, '))');
        ELSE
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T1.TYPE_CODE = ', QUOTE(AV_TYPE_CODE_FILTER), ')');
        END IF;
    END IF;

    -- Access control (ALL_REQUEST tab from GET_SERVICE_REQUEST_DASHBOARD_V1)
    SET LS_ACCESS_QUERY = CONCAT('
    (
        (
            T1.REPORTER_PERSON_ID = ''', AV_PERSON_ID, '''
            OR T1.ASSIGNEE_PERSON_ID = ''', AV_PERSON_ID, '''
            OR EXISTS (SELECT 1 FROM SR_HEADER_IDS WHERE SR_HEADER_ID = T1.SR_HEADER_ID)
            OR EXISTS (SELECT 1 FROM SR_TEMP WHERE SR_HEADER_ID = T1.SR_HEADER_ID)
            OR T1.UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP_SR)
        )
        OR
        (
            (EXISTS(SELECT 1 FROM ROLE_RIGHTS T1 LEFT JOIN RIGHTS T2 ON T1.RIGHT_ID = T2.RIGHT_ID LEFT JOIN PERSON_ROLES T3 ON T1.ROLE_ID = T3.ROLE_ID WHERE T3.PERSON_ID = ''', AV_PERSON_ID, ''' AND T2.RIGHT_NAME = ''SERVICE_REQUEST_ADMINISTRATOR''))
            AND T1.UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
        )
        OR
        (
            (EXISTS(SELECT 1 FROM ROLE_RIGHTS T1 LEFT JOIN RIGHTS T2 ON T1.RIGHT_ID = T2.RIGHT_ID LEFT JOIN PERSON_ROLES T3 ON T1.ROLE_ID = T3.ROLE_ID WHERE T3.PERSON_ID = ''', AV_PERSON_ID, ''' AND T2.RIGHT_NAME = ''VIEW_SR_ADMIN_GROUP''))
            AND T1.ADMIN_GROUP_ID IN (
                SELECT AG.ADMIN_GROUP_ID FROM ADMIN_GROUP AG
                INNER JOIN ROLE_RIGHTS RR ON AG.ROLE_ID = RR.ROLE_ID
                INNER JOIN RIGHTS R ON RR.RIGHT_ID = R.RIGHT_ID
                INNER JOIN PERSON_ROLES PR ON RR.ROLE_ID = PR.ROLE_ID
                WHERE PR.PERSON_ID = ''', AV_PERSON_ID, ''' AND R.RIGHT_NAME = ''VIEW_SR_ADMIN_GROUP''
            )
        )
    ) OR EXISTS (SELECT 1 FROM SR_TASK_ROLES WHERE UNIT_NUMBER = T1.UNIT_NUMBER) OR ((EXISTS (SELECT 1 FROM SR_TASK WHERE ASSIGNEE_PERSON_ID = ''', AV_PERSON_ID, ''' AND SR_HEADER_ID = T1.SR_HEADER_ID)))');

    -- Common CTE block
    SET LS_DYN_SQL = CONCAT('
        WITH ACCESS_TMP AS (
            SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
            AND T3.RIGHT_NAME IN (''SERVICE_REQUEST_ADMINISTRATOR'')
            UNION
            SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
            WHERE UNIT_NUMBER IN (
                SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                AND T3.RIGHT_NAME IN (''SERVICE_REQUEST_ADMINISTRATOR'')
            )
        ),
        SR_TASK_ROLES AS (
            SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
            AND T3.RIGHT_NAME IN (''MANAGE_SERVICE_REQUEST_TASK'')
            UNION
            SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
            WHERE UNIT_NUMBER IN (
                SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                AND T3.RIGHT_NAME IN (''MANAGE_SERVICE_REQUEST_TASK'')
            )
        ),
        ACCESS_TMP_SR AS (
            SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
            AND T3.RIGHT_NAME IN (''MODIFY_SERVICE_REQUEST'',''VIEW_SERVICE_REQUEST'')
            UNION
            SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
            WHERE UNIT_NUMBER IN (
                SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                AND T3.RIGHT_NAME IN (''MODIFY_SERVICE_REQUEST'',''VIEW_SERVICE_REQUEST'')
            )
        ),
        SR_TEMP AS (
            SELECT DISTINCT CAST(T9.MODULE_ITEM_ID AS UNSIGNED) AS SR_HEADER_ID
            FROM WORKFLOW T9
            INNER JOIN WORKFLOW_DETAIL T10 ON T9.WORKFLOW_ID = T10.WORKFLOW_ID
            WHERE T10.APPROVER_PERSON_ID = ''', AV_PERSON_ID, '''
            AND T9.MODULE_CODE = 20
            AND T9.IS_WORKFLOW_ACTIVE = ''Y''
            AND T10.APPROVAL_STATUS = ''W''
        ),
        SR_HEADER_IDS AS (
            SELECT DISTINCT SR_HEADER_ID
            FROM SR_PERSON_ROLES T5
            INNER JOIN ROLE_RIGHTS RR ON RR.ROLE_ID = T5.ROLE_ID
            INNER JOIN RIGHTS R ON R.RIGHT_ID = RR.RIGHT_ID
            WHERE R.RIGHT_NAME IN (''SERVICE_REQUEST_WATCHER'', ''MODIFY_SERVICE_REQUEST'',''VIEW_SERVICE_REQUEST'')
            AND T5.PERSON_ID = ''', AV_PERSON_ID, '''
        )');

    -- Widget unit filter with optional child units
    IF AV_UNIT_NUMBER IS NOT NULL AND AV_UNIT_NUMBER != '' THEN
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, ',
        UNITS_BY_DESCEND_FLAG AS (
            SELECT CHILD_UNIT_NUMBER AS UNIT_NUMBER FROM UNIT_WITH_CHILDREN
            WHERE UNIT_NUMBER = ''', AV_UNIT_NUMBER, ''' AND ''', IFNULL(AV_DESCENT_FLAG, 'N'), ''' = ''Y''
            UNION
            SELECT ''', AV_UNIT_NUMBER, ''' AS UNIT_NUMBER
        )');
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND EXISTS (SELECT 1 FROM UNITS_BY_DESCEND_FLAG UD WHERE UD.UNIT_NUMBER = T1.UNIT_NUMBER)');
    END IF;

    -- CHART MODE: Return count grouped by SR type
    IF AV_IS_CHART = 'IS_CHART' THEN
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, '
        SELECT T2.TYPE_CODE, T2.DESCRIPTION, COUNT(T1.SR_HEADER_ID) AS TOTAL_COUNT,
        SUM(CASE WHEN T1.STATUS_CODE = 5 THEN 1 ELSE 0 END) AS RESOLVED_COUNT
        FROM SR_HEADER T1
        INNER JOIN SR_TYPE T2 ON T1.TYPE_CODE = T2.TYPE_CODE
        INNER JOIN SR_STATUS T3 ON T3.STATUS_CODE = T1.STATUS_CODE
        WHERE (T1.IS_SYSTEM_GENERATED = ''N'') AND (', LS_ACCESS_QUERY, ')',
        LS_FILTER_CONDITION, '
        GROUP BY T2.TYPE_CODE, T2.DESCRIPTION
        ORDER BY TOTAL_COUNT DESC');

    -- COUNT MODE: Total rows for drill-down pagination
    ELSEIF AV_IS_CHART = 'IS_COUNT' THEN
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, '
        SELECT COUNT(T1.SR_HEADER_ID) AS TOTAL_COUNT
        FROM SR_HEADER T1
        INNER JOIN SR_TYPE T2 ON T1.TYPE_CODE = T2.TYPE_CODE
        INNER JOIN SR_STATUS T3 ON T3.STATUS_CODE = T1.STATUS_CODE
        WHERE (T1.IS_SYSTEM_GENERATED = ''N'') AND (', LS_ACCESS_QUERY, ')',
        LS_FILTER_CONDITION);

    -- DRILL-DOWN MODE: Return paginated SR details as JSON
    ELSEIF AV_IS_CHART = 'IS_DRILL_DOWN' THEN
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, '
        SELECT JSON_ARRAYAGG(JSON_OBJECT(
            ''COL_SR_ID'', T.COL_SR_ID,
            ''HEADER_ID'', T.HEADER_ID,
            ''statusCode'', T.statusCode,
            ''unitNumber'', T.unitNumber,
            ''COL_SR_STATUS'', T.COL_SR_STATUS,
            ''COL_SR_SUBJECT'', T.COL_SR_SUBJECT,
            ''COL_SR_TYPE'', T.COL_SR_TYPE,
            ''COL_SR_CATEGORY'', T.COL_SR_CATEGORY,
            ''COL_SR_PRIORITY'', T.COL_SR_PRIORITY,
            ''COL_SR_REPORTER'', T.COL_SR_REPORTER,
            ''serviceRequestId'', T.serviceRequestId,
            ''COL_SR_DEPARTMENT'', T.COL_SR_DEPARTMENT,
            ''isSystemGenerated'', T.isSystemGenerated,
            ''COL_SR_ASSI_PERSON'', T.COL_SR_ASSI_PERSON
        )) AS widget_data
        FROM (
            SELECT
                T1.SR_HEADER_ID AS COL_SR_ID,
                T1.SR_HEADER_ID AS HEADER_ID,
                T1.STATUS_CODE AS statusCode,
                T1.UNIT_NUMBER AS unitNumber,
                T3.DESCRIPTION AS COL_SR_STATUS,
                T1.SUBJECT AS COL_SR_SUBJECT,
                T2.DESCRIPTION AS COL_SR_TYPE,
                T8.DESCRIPTION AS COL_SR_CATEGORY,
                T9.DESCRIPTION AS COL_SR_PRIORITY,
                T7.FULL_NAME AS COL_SR_REPORTER,
                T1.SR_HEADER_ID AS serviceRequestId,
                T4.DISPLAY_NAME AS COL_SR_DEPARTMENT,
                T1.IS_SYSTEM_GENERATED AS isSystemGenerated,
                T6.FULL_NAME AS COL_SR_ASSI_PERSON
            FROM SR_HEADER T1
            INNER JOIN SR_TYPE T2 ON T1.TYPE_CODE = T2.TYPE_CODE
            INNER JOIN SR_STATUS T3 ON T3.STATUS_CODE = T1.STATUS_CODE
            LEFT JOIN ADMIN_GROUP T10 ON T10.ADMIN_GROUP_ID = T1.ADMIN_GROUP_ID
            LEFT JOIN SR_PRIORITY T9 ON T9.PRIORITY_ID = T1.PRIORITY_ID
            LEFT JOIN SR_CATEGORY T8 ON T8.CATEGORY_CODE = T1.CATEGORY_CODE
            LEFT JOIN PERSON T7 ON T7.PERSON_ID = T1.REPORTER_PERSON_ID
            LEFT JOIN PERSON T6 ON T6.PERSON_ID = T1.ASSIGNEE_PERSON_ID
            LEFT JOIN UNIT T4 ON T4.UNIT_NUMBER = T1.UNIT_NUMBER
            WHERE (T1.IS_SYSTEM_GENERATED = ''N'') AND (', LS_ACCESS_QUERY, ')',
            LS_FILTER_CONDITION, '
            ORDER BY ', LS_SORT_TYPE, ' LIMIT ', AV_LIMIT, ' OFFSET ', AV_OFFSET, '
        ) T
        ');
    END IF;

    SET @QUERY_STATEMENT = LS_DYN_SQL;
    PREPARE EXECUTABLE_STATEMENT FROM @QUERY_STATEMENT;
    EXECUTE EXECUTABLE_STATEMENT;
    DEALLOCATE PREPARE EXECUTABLE_STATEMENT;

END
