CREATE 
VIEW `sr_contract_admin_v` AS 
    SELECT distinct p.PERSON_ID AS PERSON_ID, p.FULL_NAME AS DESCRIPTION
    FROM UNIT_ADMINISTRATOR ua
    JOIN PERSON p ON ua.PERSON_ID = p.PERSON_ID
    WHERE ua.UNIT_ADMINISTRATOR_TYPE_CODE = 12
    ORDER BY ua.UPDATE_TIMESTAMP DESC;
