CREATE PROCEDURE `IP_PERSON_ATTACHMENT_MIGRATION`()
BEGIN

	DECLARE DONE INT DEFAULT 0;

	DECLARE LS_OLD_FILE_ID	varchar(36);
    DECLARE LS_NEW_FILE_ID VARCHAR(36);
	DECLARE LS_DATA	longblob;
	DECLARE LS_FILE_PATH	varchar(255);
	DECLARE LS_ORIGINAL_FILE_NAME	varchar(500);
	DECLARE LS_FILE_NAME	varchar(100);
	DECLARE LS_ARCHIVED	char(1);

	DECLARE UUID_EXISTS INT DEFAULT 1;

	DECLARE CUR_FILE_DATA CURSOR FOR SELECT ID, DATA, FILE_PATH,
    ORIGINAL_FILE_NAME, FILE_NAME, IS_ARCHIVED FROM FILE_DATA fd 
    WHERE EXISTS (SELECT 1 FROM eps_proposal_person_attachmnt a 
    JOIN PROPOSAL_PERSONS_ATTACHMNT b 
	ON b.FILE_DATA_ID = a.FILE_DATA_ID WHERE a.FILE_DATA_ID = fd.ID); 
    
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;

	set sql_safe_updates = 0;
		OPEN CUR_FILE_DATA;
			INSERT_LOOP: LOOP
				FETCH CUR_FILE_DATA INTO LS_OLD_FILE_ID, LS_DATA, LS_FILE_PATH,
                LS_ORIGINAL_FILE_NAME, LS_FILE_NAME, LS_ARCHIVED;
                
				IF DONE = 1 THEN
					LEAVE INSERT_LOOP;
				END IF;
                
                SET UUID_EXISTS = 1;

				UUID_LOOP: LOOP
					SET LS_NEW_FILE_ID = UUID();

					SELECT COUNT(*) INTO UUID_EXISTS
					FROM FILE_DATA WHERE ID = LS_NEW_FILE_ID;

					IF UUID_EXISTS = 0 THEN
						LEAVE UUID_LOOP;
					END IF;
				END LOOP;
                
                INSERT INTO FILE_DATA (`ID`, `DATA`, `MODULE_CODE`, `FILE_PATH`, `ORIGINAL_FILE_NAME`,
				`FILE_NAME`, `IS_ARCHIVED`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES
                (LS_NEW_FILE_ID, LS_DATA, 2, LS_FILE_PATH, LS_ORIGINAL_FILE_NAME,
				LS_FILE_NAME, LS_ARCHIVED, UTC_TIMESTAMP(), 'admin');
                
                UPDATE PROPOSAL_PERSONS_ATTACHMNT SET FILE_DATA_ID = LS_NEW_FILE_ID 
                WHERE FILE_DATA_ID = LS_OLD_FILE_ID;
                
			END LOOP;
        CLOSE CUR_FILE_DATA;
	-- set sql_safe_updates = 1;
    
END
