CREATE PROCEDURE `AWARD_MASTER_PERSON_DATA_SYNC`()
BEGIN
SET SQL_SAFE_UPDATES = 0;

UPDATE AWARD_MASTER_DATASET_RT A
INNER JOIN PERSON P
    ON A.PI_PERSON_ID = P.PERSON_ID
INNER JOIN UNIT U
    ON P.HOME_UNIT = U.UNIT_NUMBER
SET
    A.PI_NAME = P.FULL_NAME,
    A.PI_HOME_UNIT_NUMBER = P.HOME_UNIT,
    A.PI_HOME_UNIT = U.UNIT_NAME,
 A.LAST_SYNC_TIME = UTC_TIMESTAMP()
WHERE (UPPER(TRIM(A.PI_NAME)) <> UPPER(TRIM(P.FULL_NAME)) OR (A.PI_NAME IS NULL AND P.FULL_NAME IS NOT NULL) OR (A.PI_NAME IS NOT NULL AND P.FULL_NAME IS NULL))
   OR (A.PI_HOME_UNIT_NUMBER <> P.HOME_UNIT OR (A.PI_HOME_UNIT_NUMBER IS NULL AND P.HOME_UNIT IS NOT NULL) OR (A.PI_HOME_UNIT_NUMBER IS NOT NULL AND P.HOME_UNIT IS NULL))
   OR (UPPER(TRIM(A.PI_HOME_UNIT)) <> UPPER(TRIM(U.UNIT_NAME)) OR (A.PI_HOME_UNIT IS NULL AND U.UNIT_NAME IS NOT NULL) OR (A.PI_HOME_UNIT IS NOT NULL AND U.UNIT_NAME IS NULL));


UPDATE AWARD_MASTER_DATASET_RT A
INNER JOIN ROLODEX P
    ON A.PI_PERSON_ID = P.ROLODEX_ID
SET A.PI_NAME = P.FULL_NAME
,  A.LAST_SYNC_TIME = UTC_TIMESTAMP()
WHERE (UPPER(TRIM(A.PI_NAME)) <> UPPER(TRIM(P.FULL_NAME)) OR (A.PI_NAME IS NULL AND P.FULL_NAME IS NOT NULL) OR (A.PI_NAME IS NOT NULL AND P.FULL_NAME IS NULL));


UPDATE AWARD_MASTER_DATASET_RT A
INNER JOIN PERSON P
    ON A.KEY_PERSON_ID = P.PERSON_ID
INNER JOIN UNIT U
    ON P.HOME_UNIT = U.UNIT_NUMBER
LEFT JOIN COUNTRY C
    ON C.COUNTRY_CODE = P.COUNTRY_CODE
SET
    A.KEY_PERSON_NAME = P.FULL_NAME,
    A.KEY_PERSON_DEPARTMENT_NUMBER = P.HOME_UNIT,
    A.KEY_PERSON_DEPARTMENT = U.UNIT_NAME,
    A.KEY_PERSON_EMAIL = P.EMAIL_ADDRESS,
    A.KEY_PERSON_GENDER = P.GENDER,
    A.KEY_PERSON_COUNTRY = C.COUNTRY_NAME,
 A.LAST_SYNC_TIME = UTC_TIMESTAMP()
WHERE (UPPER(TRIM(A.KEY_PERSON_NAME)) <> UPPER(TRIM(P.FULL_NAME)) OR (A.KEY_PERSON_NAME IS NULL AND P.FULL_NAME IS NOT NULL) OR (A.KEY_PERSON_NAME IS NOT NULL AND P.FULL_NAME IS NULL))
   OR (A.KEY_PERSON_DEPARTMENT_NUMBER <> P.HOME_UNIT OR (A.KEY_PERSON_DEPARTMENT_NUMBER IS NULL AND P.HOME_UNIT IS NOT NULL) OR (A.KEY_PERSON_DEPARTMENT_NUMBER IS NOT NULL AND P.HOME_UNIT IS NULL))
   OR (UPPER(TRIM(A.KEY_PERSON_DEPARTMENT)) <> UPPER(TRIM(U.UNIT_NAME)) OR (A.KEY_PERSON_DEPARTMENT IS NULL AND U.UNIT_NAME IS NOT NULL) OR (A.KEY_PERSON_DEPARTMENT IS NOT NULL AND U.UNIT_NAME IS NULL))
   OR (UPPER(TRIM(A.KEY_PERSON_EMAIL)) <> UPPER(TRIM(P.EMAIL_ADDRESS)) OR (A.KEY_PERSON_EMAIL IS NULL AND P.EMAIL_ADDRESS IS NOT NULL) OR (A.KEY_PERSON_EMAIL IS NOT NULL AND P.EMAIL_ADDRESS IS NULL))
   OR (A.KEY_PERSON_GENDER <> P.GENDER OR (A.KEY_PERSON_GENDER IS NULL AND P.GENDER IS NOT NULL) OR (A.KEY_PERSON_GENDER IS NOT NULL AND P.GENDER IS NULL))
   OR (UPPER(TRIM(A.KEY_PERSON_COUNTRY)) <> UPPER(TRIM(C.COUNTRY_NAME)) OR (A.KEY_PERSON_COUNTRY IS NULL AND C.COUNTRY_NAME IS NOT NULL) OR (A.KEY_PERSON_COUNTRY IS NOT NULL AND C.COUNTRY_NAME IS NULL));


UPDATE AWARD_MASTER_DATASET_RT A
INNER JOIN ROLODEX P
    ON A.KEY_PERSON_ID = P.ROLODEX_ID
LEFT JOIN COUNTRY C
    ON C.COUNTRY_CODE = P.COUNTRY_CODE
LEFT JOIN AWARD_PERSONS AP ON AP.AWARD_ID = A.AWARD_ID AND A.KEY_PERSON_ID = AP.ROLODEX_ID
SET
    A.KEY_PERSON_NAME = P.FULL_NAME,
    A.KEY_PERSON_EMAIL = P.EMAIL_ADDRESS,
    A.KEY_PERSON_COUNTRY = C.COUNTRY_NAME,
 A.KEY_PERSON_ORGANIZATION = AP.DEPARTMENT,
 A.LAST_SYNC_TIME = UTC_TIMESTAMP()
WHERE (UPPER(TRIM(A.KEY_PERSON_NAME)) <> UPPER(TRIM(P.FULL_NAME)) OR (A.KEY_PERSON_NAME IS NULL AND P.FULL_NAME IS NOT NULL) OR (A.KEY_PERSON_NAME IS NOT NULL AND P.FULL_NAME IS NULL))
   OR (UPPER(TRIM(A.KEY_PERSON_EMAIL)) <> UPPER(TRIM(P.EMAIL_ADDRESS)) OR (A.KEY_PERSON_EMAIL IS NULL AND P.EMAIL_ADDRESS IS NOT NULL) OR (A.KEY_PERSON_EMAIL IS NOT NULL AND P.EMAIL_ADDRESS IS NULL))
   OR (UPPER(TRIM(A.KEY_PERSON_COUNTRY)) <> UPPER(TRIM(C.COUNTRY_NAME)) OR (A.KEY_PERSON_COUNTRY IS NULL AND C.COUNTRY_NAME IS NOT NULL) OR (A.KEY_PERSON_COUNTRY IS NOT NULL AND C.COUNTRY_NAME IS NULL))
    OR (UPPER(TRIM(A.KEY_PERSON_ORGANIZATION)) <> UPPER(TRIM(AP.DEPARTMENT)) OR (A.KEY_PERSON_ORGANIZATION IS NULL AND AP.DEPARTMENT IS NOT NULL) OR (A.KEY_PERSON_ORGANIZATION IS NOT NULL AND AP.DEPARTMENT IS NULL));

SET SQL_SAFE_UPDATES = 1;

END;
