CREATE PROCEDURE `GET_AWARD_DASHBOARD_V1`(
    IN AV_FILTER_JSON JSON,
    IN AV_DISPLAY_LIST JSON,
    IN AV_PERSON_ID VARCHAR(40),
    IN AV_OFFSET INT(10),
    IN AV_LIMIT INT(10),
    IN AV_TAB_TYPE VARCHAR(30),
    IN AV_IS_COUNT BOOLEAN,
    IN AV_SORT_TYPE VARCHAR(500)
)
BEGIN

    -- Declare variables
    DECLARE LS_DYN_SQL LONGTEXT;
    DECLARE LS_FILTER_CONDITION LONGTEXT;
    DECLARE LS_OFFSET INT(11);
    DECLARE LS_TAB_QUERY_WHERE_CLAUSE LONGTEXT;

    -- Custom data element variables
    DECLARE LI_CUSTOM_DATA_ELEMENTS_ID INT(11);
    DECLARE LI_DATA_TYPE INT(11);
    DECLARE LS_CUST_LABEL VARCHAR(255);
    DECLARE LI_CUST_ORDER INT(11);
    DECLARE LS_IS_MULTI_SELECT_LOOKUP VARCHAR(1);
    DECLARE LS_CUSTOM_CRT VARCHAR(255);
    DECLARE LS_CUST_CRT_VALUE TEXT;
    DECLARE CUSTOM_CRT_QUERY TEXT;
    DECLARE LS_CUSTOM_COL VARCHAR(255);
    DECLARE LS_CUSTOM_DATA_ELEMENT VARCHAR(255);
    DECLARE LS_CUSTOM_DATA_JOIN_SEL TEXT;
    DECLARE NOT_FOUND INT DEFAULT 0;
    DECLARE old_depth INT;

    -- Cursor for custom data elements used in award advanced search
    DECLARE CUSTOM_DATA_ELEMENTS_IDS CURSOR FOR
        SELECT CDE.CUSTOM_DATA_ELEMENTS_ID, CDE.DATA_TYPE, CDE.COLUMN_LABEL, CDEU.ORDER_NUMBER, CDE.IS_MULTI_SELECT_LOOKUP
        FROM CUSTOM_DATA_ELEMENTS CDE
        INNER JOIN CUSTOM_DATA_ELEMENT_USAGE CDEU ON CDEU.CUSTOM_DATA_ELEMENTS_ID = CDE.CUSTOM_DATA_ELEMENTS_ID
        WHERE CDEU.MODULE_CODE = 1 AND CDE.IS_ACTIVE = 'Y' AND CDEU.IS_REQ_ADVANCE_SEARCH = 'Y';

    -- Handler for cursor
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;

    -- Initialize variables
    SET LS_FILTER_CONDITION = '';
    SET LS_CUSTOM_DATA_JOIN_SEL = '';
    SET LS_TAB_QUERY_WHERE_CLAUSE = '';
    SET LS_DYN_SQL = '';
    SET @CUST_CRITERIA_MAP = JSON_OBJECT();
    SET @CUST_COL_MAP = JSON_OBJECT();
    SET @AV_FILTER_JSON = AV_FILTER_JSON;
    SET @AV_DISPLAY_LIST = AV_DISPLAY_LIST;
    SET SESSION time_zone = '+00:00';
    SET old_depth = @@SESSION.optimizer_search_depth;
    SET SESSION optimizer_search_depth = 15;

    -- =============================================
    -- CUSTOM DATA HANDLING
    -- Build custom data select, criteria, and column maps
    -- =============================================
    OPEN CUSTOM_DATA_ELEMENTS_IDS;
    CUSTOM_DATA_ELEMENTS_LOOP: LOOP
        SET NOT_FOUND = 0;
        FETCH CUSTOM_DATA_ELEMENTS_IDS INTO LI_CUSTOM_DATA_ELEMENTS_ID, LI_DATA_TYPE, LS_CUST_LABEL, LI_CUST_ORDER, LS_IS_MULTI_SELECT_LOOKUP;

        IF NOT_FOUND = 1 THEN
            LEAVE CUSTOM_DATA_ELEMENTS_LOOP;
        END IF;

        SET LS_CUSTOM_CRT = CONCAT('CRT_AWD_CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID);
        SET LS_CUSTOM_DATA_ELEMENT = CONCAT('CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID);
        SET LS_CUST_CRT_VALUE = JSON_UNQUOTE(JSON_EXTRACT(AV_FILTER_JSON, CONCAT('$.', LS_CUSTOM_CRT)));

        -- Build custom data select expression based on data type
        SET LS_CUSTOM_DATA_JOIN_SEL = CONCAT(
            LS_CUSTOM_DATA_JOIN_SEL,
            CASE
                WHEN LI_DATA_TYPE = 4 OR (LI_DATA_TYPE IN (8, 9) AND LS_IS_MULTI_SELECT_LOOKUP = 'Y') THEN
                    CONCAT(
                        'JSON_ARRAYAGG(JSON_OBJECT(''CUSTOM_ANSWER'', CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID,
                        ')) AS CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID
                    )
                WHEN LI_DATA_TYPE = 3 THEN
                    CONCAT('(UNIX_TIMESTAMP( CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID, '))*1000 AS CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID)
                ELSE
                    CONCAT('CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID)
            END,
            ','
        );

        -- Build custom data criteria based on data type and filter value
        IF LS_CUST_CRT_VALUE IS NOT NULL THEN
            SET CUSTOM_CRT_QUERY = NULL;
            IF LI_DATA_TYPE IN (3) THEN
                SET CUSTOM_CRT_QUERY = CONCAT('(', LS_CUSTOM_DATA_ELEMENT, ' = (UNIX_TIMESTAMP(''', LS_CUST_CRT_VALUE, ''')*1000))');
            ELSEIF LI_DATA_TYPE IN (1, 10) THEN
                SET CUSTOM_CRT_QUERY = CONCAT('(', LS_CUSTOM_DATA_ELEMENT, ' LIKE ''%', LS_CUST_CRT_VALUE, '%'')');
            ELSEIF LI_DATA_TYPE IN (4, 8, 9, 6) THEN
                IF LS_IS_MULTI_SELECT_LOOKUP = 'Y' THEN
                    SET CUSTOM_CRT_QUERY = CONCAT('(EXISTS(SELECT 1 FROM AWARD_CUSTOM_DATA_RT WHERE AWARD_ID = T1.AWARD_ID AND MATCH(', LS_CUSTOM_DATA_ELEMENT, ') AGAINST (''', LS_CUST_CRT_VALUE, ''') ))');
                ELSE
                    SET CUSTOM_CRT_QUERY = CONCAT('(EXISTS(SELECT 1 FROM AWARD_CUSTOM_DATA_RT WHERE AWARD_ID = T1.AWARD_ID AND ',
                        LS_CUSTOM_DATA_ELEMENT, ' IN (SELECT value FROM JSON_TABLE(''', LS_CUST_CRT_VALUE, ''',''$[*]'' COLUMNS (value LONGTEXT PATH ''$'')) AS t)  ))');
                END IF;
            ELSE
                IF LI_DATA_TYPE IN (7, 5) THEN
                    SET LS_CUST_CRT_VALUE = JSON_UNQUOTE(JSON_EXTRACT(LS_CUST_CRT_VALUE, '$[0]'));
                END IF;

                SET CUSTOM_CRT_QUERY = CONCAT('(', LS_CUSTOM_DATA_ELEMENT, ' = ''', LS_CUST_CRT_VALUE, ''')');
            END IF;

            IF CUSTOM_CRT_QUERY IS NOT NULL THEN
                SET @CUST_CRITERIA_MAP = JSON_INSERT(@CUST_CRITERIA_MAP, CONCAT('$.', LS_CUSTOM_CRT), CUSTOM_CRT_QUERY);
            END IF;
        END IF;

        -- Build custom data column map for display
        SET LS_CUSTOM_COL = CONCAT('COL_AWD_CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID);

        IF JSON_CONTAINS(AV_DISPLAY_LIST, JSON_QUOTE(LS_CUSTOM_COL)) = 1 THEN
            SET @CUST_COL_MAP = JSON_INSERT(@CUST_COL_MAP, CONCAT('$.', LS_CUSTOM_COL), CONCAT('CD.', CONCAT('CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID)));
        END IF;

    END LOOP CUSTOM_DATA_ELEMENTS_LOOP;
    CLOSE CUSTOM_DATA_ELEMENTS_IDS;

    SET LS_CUSTOM_DATA_JOIN_SEL = TRIM(TRAILING ',' FROM LS_CUSTOM_DATA_JOIN_SEL);

    -- =============================================
    -- BUILD CTEs
    -- =============================================
    SET @DYNAMIC_CTE = CONCAT('WITH ACCESS_TMP AS (
                                SELECT UNIT_NUMBER
                                FROM PERSON_ROLES T1
                                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                                WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                                AND T3.RIGHT_NAME IN (''VIEW_AWARD'', ''MODIFY_AWARD'')
                                UNION
                                SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
                                WHERE UNIT_NUMBER IN (
                                    SELECT UNIT_NUMBER
                                    FROM PERSON_ROLES T1
                                    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                                    INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                                    WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                                    AND T3.RIGHT_NAME IN (''VIEW_AWARD'', ''MODIFY_AWARD'')
                                )),
                            ACCESS_TMP_GM AS (
                                SELECT UNIT_NUMBER
                                FROM PERSON_ROLES T1
                                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                                WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                                AND T3.RIGHT_NAME IN (''VIEW_AWARD'', ''MODIFY_AWARD'') AND T1.ROLE_ID=''100''
                                UNION
                                SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
                                WHERE UNIT_NUMBER IN (
                                    SELECT UNIT_NUMBER
                                    FROM PERSON_ROLES T1
                                    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                                    INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                                    WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                                    AND T3.RIGHT_NAME IN (''VIEW_AWARD'', ''MODIFY_AWARD'') AND T1.ROLE_ID=''100''
                                )),
                            ACCESS_TMP_FOR_MODIFY_VARIATION AS (
                                SELECT UNIT_NUMBER
                                FROM PERSON_ROLES T1
                                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                                WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                                AND T3.RIGHT_NAME = ''MODIFY_ALL_VARIATION_REQUESTS''
                                UNION
                                SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
                                WHERE UNIT_NUMBER IN (
                                    SELECT UNIT_NUMBER
                                    FROM PERSON_ROLES T1
                                    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                                    INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                                    WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                                    AND T3.RIGHT_NAME = ''MODIFY_ALL_VARIATION_REQUESTS''
                                )),
                            ACCESS_TMP_GM_FOR_MODIFY_VARIATION AS (
                                SELECT UNIT_NUMBER
                                FROM PERSON_ROLES T1
                                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                                WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                                AND T3.RIGHT_NAME = ''MODIFY_ALL_VARIATION_REQUESTS'' AND T1.ROLE_ID=''100''
                                UNION
                                SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
                                WHERE UNIT_NUMBER IN (
                                    SELECT UNIT_NUMBER
                                    FROM PERSON_ROLES T1
                                    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                                    INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                                    WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                                    AND T3.RIGHT_NAME = ''MODIFY_ALL_VARIATION_REQUESTS'' AND T1.ROLE_ID=''100''
                                ))
                        ');

    SET @KEY_WORD_CTE = 'AWARD_KEYWORDS_JSON AS (
                            SELECT AK.AWARD_ID,
                                JSON_ARRAYAGG(
                                    JSON_OBJECT(''KEYWORD'', COALESCE(SK.DESCRIPTION, AK.KEYWORD))
                                ) AS KEYWORDS
                            FROM AWARD_SCIENCE_KEYWORD AK
                            LEFT JOIN SCIENCE_KEYWORD SK ON SK.SCIENCE_KEYWORD_CODE = AK.SCIENCE_KEYWORD_CODE
                            GROUP BY AK.AWARD_ID
                        )';

    SET @AWARD_PEOPLE_CTE = 'AWARD_PEOPLE_JSON AS (
        SELECT AP.AWARD_ID,
            JSON_ARRAYAGG(
                JSON_OBJECT(
                    ''FIRST_NAME'', COALESCE(P.FIRST_NAME, R.FIRST_NAME),
                    ''LAST_NAME'', COALESCE(P.LAST_NAME, R.LAST_NAME),
                    ''FULL_NAME'', AP.FULL_NAME,
                    ''ROLE_NAME'', PPR.DESCRIPTION,
                    ''PERCENTAGE_OF_EFFORT'', AP.PERCENTAGE_OF_EFFORT
                )
            ) AS KEY_PERSONS
        FROM AWARD_PERSONS AP
        LEFT JOIN PERSON P ON P.PERSON_ID = AP.PERSON_ID
        LEFT JOIN ROLODEX R ON R.ROLODEX_ID = AP.ROLODEX_ID
        LEFT JOIN eps_prop_person_role PPR ON PPR.PROP_PERSON_ROLE_ID = AP.PERSON_ROLE_ID
        GROUP BY AP.AWARD_ID
    )';

    SET @KEY_PERSONS_ROLES_CTE = 'AWARD_KEY_PERSONS_ROLES_JSON AS (
        SELECT AP.AWARD_ID,
            JSON_ARRAYAGG(
                JSON_OBJECT(
                    ''ROLE_NAME'', PPR.DESCRIPTION
                )
            ) AS KEY_PERSONS_ROLES
        FROM AWARD_PERSONS AP
        LEFT JOIN PERSON P ON P.PERSON_ID = AP.PERSON_ID
        LEFT JOIN ROLODEX R ON R.ROLODEX_ID = AP.ROLODEX_ID
        LEFT JOIN eps_prop_person_role PPR ON PPR.PROP_PERSON_ROLE_ID = AP.PERSON_ROLE_ID
        GROUP BY AP.AWARD_ID
    )';

    SET @AWARD_GRANT_CALL_CTE = 'AWARD_GRANT_CALL_JSON AS (
        SELECT A.AWARD_ID,
            JSON_ARRAYAGG(
                JSON_OBJECT(
                    ''GRANT_HEADER_ID'', GCH.GRANT_HEADER_ID,
                    ''ABBREVIATION'', GCH.ABBREVIATION,
                    ''GRANT_CALL_NAME'', GCH.NAME
                )
            ) AS GRANT_CALL
        FROM AWARD A
        INNER JOIN GRANT_CALL_HEADER GCH ON GCH.GRANT_HEADER_ID = A.GRANT_HEADER_ID
        WHERE A.GRANT_HEADER_ID IS NOT NULL
        GROUP BY A.AWARD_ID
    )';

    SET @AWARD_CONTACT_CTE = 'AWARD_CONTACT_JSON AS (
        SELECT AC.AWARD_ID,
            JSON_ARRAYAGG(
                JSON_OBJECT(
                    ''FIRST_NAME'', COALESCE(P.FIRST_NAME, R.FIRST_NAME),
                    ''LAST_NAME'', COALESCE(P.LAST_NAME, R.LAST_NAME),
                    ''FULL_NAME'', AC.FULL_NAME,
                    ''CONTACT_TYPE'', ACT.DESCRIPTION
                )
            ) AS CONTACTS
        FROM AWARD_CONTACT AC
        LEFT JOIN PERSON P ON P.PERSON_ID = AC.PERSON_ID
        LEFT JOIN ROLODEX R ON R.ROLODEX_ID = AC.ROLODEX_ID
        LEFT JOIN AWARD_CONTACT_TYPE ACT ON ACT.CONTACT_TYPE_CODE = AC.CONTACT_TYPE_CODE
        GROUP BY AC.AWARD_ID
    )';

    SET @AWARD_PROJECT_TEAM_CTE = 'AWARD_PROJECT_TEAM_JSON AS (
        SELECT APT.AWARD_ID,
            JSON_ARRAYAGG(
                JSON_OBJECT(
                    ''FIRST_NAME'', COALESCE(P.FIRST_NAME, R.FIRST_NAME),
                    ''LAST_NAME'', COALESCE(P.LAST_NAME, R.LAST_NAME),
                    ''FULL_NAME'', APT.FULL_NAME,
                    ''ROLE_NAME'', APT.PROJECT_ROLE
                )
            ) AS PROJECT_TEAM
        FROM AWARD_PROJECT_TEAM APT
        LEFT JOIN PERSON P ON P.PERSON_ID = APT.PERSON_ID AND APT.NON_EMPLOYEE_FLAG = ''N''
        LEFT JOIN ROLODEX R ON R.ROLODEX_ID = APT.PERSON_ID AND APT.NON_EMPLOYEE_FLAG = ''Y''
        GROUP BY APT.AWARD_ID
    )';

    SET @AWARD_SPECIAL_REVIEW_CTE = 'AWARD_SPECIAL_REVIEW_JSON AS (
        SELECT AWARD_ID,
            JSON_ARRAYAGG(
                JSON_OBJECT(''PROTOCOL_NUMBER'', PROTOCOL_NUMBER)
            ) AS SPECIAL_REVIEWS
        FROM AWARD_SPECIAL_REVIEW
        GROUP BY AWARD_ID
    )';

    SET @AWARD_RESEARCH_AREAS_CTE = 'AWARD_RESEARCH_AREAS_JSON AS (
        SELECT ARA.AWARD_ID,
            JSON_ARRAYAGG(
                JSON_OBJECT(
                    ''AREA'', RA.DESCRIPTION,
                    ''SUB_AREA'', RSA.DESCRIPTION
                )
            ) AS RESEARCH_AREAS
        FROM AWARD_RESEARCH_AREAS ARA
        LEFT JOIN RESEARCH_TYPE_AREA RA ON RA.RESRCH_TYPE_AREA_CODE = ARA.RESRCH_TYPE_AREA_CODE
        LEFT JOIN RESEARCH_TYPE_SUB_AREA RSA ON RSA.RESRCH_TYPE_SUB_AREA_CODE = ARA.RESRCH_TYPE_SUB_AREA_CODE
        GROUP BY ARA.AWARD_ID
    )';

    SET @CTE_MAP = JSON_OBJECT(
        'CTE_KEYWORD_CTE', @KEY_WORD_CTE,
        'CTE_AWARD_PEOPLE', @AWARD_PEOPLE_CTE,
        'CTE_AWARD_PROJECT_TEAM', @AWARD_PROJECT_TEAM_CTE,
        'CTE_AWARD_CONTACT', @AWARD_CONTACT_CTE,
        'CTE_AWARD_SPECIAL_REVIEW', @AWARD_SPECIAL_REVIEW_CTE,
        'CTE_AWARD_RESEARCH_AREAS', @AWARD_RESEARCH_AREAS_CTE,
        'CTE_AWARD_GRANT_CALL', @AWARD_GRANT_CALL_CTE,
        'CTE_KEY_PERSONS_ROLES',@KEY_PERSONS_ROLES_CTE
    );

    SET @CTE_KEY_MAP = JSON_ARRAY(
        JSON_OBJECT('CTE_KEYWORD_CTE', JSON_ARRAY('COL_AWD_KEYWORDS', 'CRT_AWD_KEYWORDS')),
        JSON_OBJECT('CTE_AWARD_PEOPLE', JSON_ARRAY('COL_AWD_KEY_PERSON', 'CRT_AWD_KEY_PERSON')),
        JSON_OBJECT('CTE_AWARD_PROJECT_TEAM', JSON_ARRAY('COL_AWD_PROJECT_TEAM', 'CRT_AWD_PROJECT_TEAM')),
        JSON_OBJECT('CTE_AWARD_CONTACT', JSON_ARRAY('COL_AWD_CONTACT', 'CRT_AWD_CONTACT')),
        JSON_OBJECT('CTE_AWARD_SPECIAL_REVIEW', JSON_ARRAY('COL_AWD_SPL_REVIEW_PROTOCOL', 'CRT_AWD_SPL_REVIEW_PROTOCOL')),
        JSON_OBJECT('CTE_AWARD_RESEARCH_AREAS', JSON_ARRAY('COL_AWD_RESEARCH_AREAS', 'CRT_AWD_RESEARCH_AREAS')),
        JSON_OBJECT('CTE_AWARD_GRANT_CALL', JSON_ARRAY('COL_AWD_GRANT_CALL_ABBREVIATION')),
        JSON_OBJECT('CTE_KEY_PERSONS_ROLES', JSON_ARRAY('CRT_AWD_KEY_PERSON_ROLES'))
    );

    -- Append conditional CTEs based on display list and filter JSON
    SET @DYNAMIC_CTE = CONCAT(@DYNAMIC_CTE, COALESCE(FN_PREPARE_DASHBOARD_JOINS(@AV_DISPLAY_LIST, @AV_FILTER_JSON, @CTE_KEY_MAP, @CTE_MAP, 'CTE'), ''));
	
    -- CTE only for pending awards
    IF AV_TAB_TYPE = 'PENDING_AWARDS' THEN
    SET @DYNAMIC_CTE = CONCAT(@DYNAMIC_CTE,
    ', PENDING_IDS AS (

    SELECT DISTINCT CAST(W.MODULE_ITEM_ID AS UNSIGNED) AS AWARD_ID
    FROM WORKFLOW W
    JOIN WORKFLOW_DETAIL WD
        ON WD.WORKFLOW_ID = W.WORKFLOW_ID
    WHERE W.MODULE_CODE = 1
      AND W.IS_WORKFLOW_ACTIVE = ''Y''
      AND WD.APPROVER_PERSON_ID = ''', AV_PERSON_ID, '''
      AND WD.APPROVAL_STATUS = ''W''

    UNION

    SELECT DISTINCT CAST(PR.MODULE_ITEM_KEY AS UNSIGNED)
    FROM PRE_REVIEW PR
    WHERE PR.MODULE_ITEM_CODE = 1
      AND PR.PRE_REVIEW_STATUS_CODE = ''1''
      AND PR.PRE_REVIEW_TYPE_CODE = ''3''
      AND PR.REVIEWER_PERSON_ID = ''', AV_PERSON_ID, ''' ),

    TASK_IDS AS (
    SELECT DISTINCT CAST(T16.MODULE_ITEM_ID AS UNSIGNED) AS AWARD_ID
    FROM TASK T16 FORCE INDEX (TASK_IDX4)
    WHERE T16.ASSIGNEE_PERSON_ID =''', AV_PERSON_ID, '''
      AND T16.TASK_STATUS_CODE IN (1,2,4)
    )
');
END IF;
    -- =============================================
    -- BUILD SELECT AND DISPLAY MAPS
    -- =============================================
    IF AV_IS_COUNT = FALSE THEN
        SET @QUERY_MAP = JSON_OBJECT(
            'awardId', 'T1.AWARD_ID',
            'awardNumber', 'T1.AWARD_NUMBER',
            'HEADER_ID', 'T1.AWARD_ID',
            'COL_AWD_ID', 'T1.AWARD_ID',
            'COL_AWD_NUMBER', 'T1.AWARD_NUMBER',
            'COL_AWD_ACCOUNT_NUMBER', 'T1.ACCOUNT_NUMBER',
            'COL_AWD_TITLE', 'T1.TITLE',
            'COL_AWD_LEAD_UNIT', 'U.DISPLAY_NAME',
            'COL_AWD_SPONSOR', 'S.DISPLAY_NAME',
            'COL_AWD_PRIME_SPONSOR', 'PS.DISPLAY_NAME',
            'COL_AWD_SPONSOR_ACRONYM', 'S.ACRONYM',
            'COL_AWD_STATUS', 'AST.DESCRIPTION',
            'COL_AWD_GRANT_CALL', 'T7.NAME',
            'COL_AWD_LAST_MOD_DATE', '(UNIX_TIMESTAMP(T1.UPDATE_TIMESTAMP)*1000)',
            'COL_AWD_TYPE', 'AT.DESCRIPTION',
            'COL_AWD_SPONSOR_AWARD_NUMBER', 'T1.SPONSOR_AWARD_NUMBER',
            'COL_AWD_ACCOUNT_TYPE', 'ACTY.DESCRIPTION',
            'COL_AWD_GRANT_TYPE', 'GCT.DESCRIPTION',
            'COL_AWD_EFFECTIVE_DATE', '(UNIX_TIMESTAMP(T1.BEGIN_DATE)*1000)',
            'COL_AWD_FINAL_EXPIRATION_DATE', '(UNIX_TIMESTAMP(T1.FINAL_EXPIRATION_DATE)*1000)',
            'COL_AWD_PI', 'API.FULL_NAME',
            'COL_AWD_KEYWORDS', '(K.KEYWORDS)',
            'COL_AWD_ACTIVITY_TYPE', 'ATC.DESCRIPTION',
            'COL_AWD_NOTICE_DATE', '(UNIX_TIMESTAMP(T1.AWARD_EFFECTIVE_DATE)*1000)',
            'COL_AWD_CFDA_NUMBER', 'T1.CFDA_NUMBER',
            'COL_AWD_DFAFS_NUMBER', 'T1.DFAFS_NUMBER',
            'COL_AWD_BUDGET_STATUS', 'ABS.DESCRIPTION',
            'COL_AWD_VERSION_STATUS', 'T1.AWARD_SEQUENCE_STATUS',
            'COL_AWD_KEY_PERSON', '(KP.KEY_PERSONS)',
            'COL_AWD_PROJECT_TEAM', '(PT.PROJECT_TEAM)',
            'COL_AWD_GRANT_CALL_ABBREVIATION', '(GCJ.GRANT_CALL)',
            'COL_AWD_CONTACT', '(ACJ.CONTACTS)',
            'COL_AWD_SPL_REVIEW_PROTOCOL', '(ASR.SPECIAL_REVIEWS)',
            'COL_AWD_FUNDING_SCHEME', 'FS.SCHEME_NAME',
            'COL_AWD_VERSION_TYPE', 'CASE WHEN T1.AWARD_DOCUMENT_TYPE_CODE = 1 THEN ''Award Setup'' ELSE SRT.DESCRIPTION END',
            'COL_AWD_RESEARCH_AREAS', '(RAR.RESEARCH_AREAS)'
        );

        -- Append mandatory display columns
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST, '$', 'awardId');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST, '$', 'awardNumber');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST, '$', 'HEADER_ID');

        SELECT JSON_MERGE_PATCH(@QUERY_MAP, @CUST_COL_MAP) INTO @QUERY_MAP;

        SET @DISPLAY_MAP = (
            SELECT JSON_OBJECTAGG(jk.k, JSON_UNQUOTE(JSON_EXTRACT(@QUERY_MAP, CONCAT('$.', jk.k))))
            FROM JSON_TABLE(AV_DISPLAY_LIST, '$[*]' COLUMNS (k VARCHAR(100) PATH '$')) AS jk
            WHERE JSON_EXTRACT(@QUERY_MAP, CONCAT('$.', jk.k)) IS NOT NULL
        );

        SELECT FN_PREPARE_DASHBOARD_SELECT(@DISPLAY_MAP) INTO @SELECT_STM;
        SELECT FN_PREPARE_DASHBOARD_JSON(@DISPLAY_MAP) INTO @DISPLAY;

    END IF;

    -- =============================================
    -- BUILD JOIN MAPS
    -- =============================================
    SET @CUSTOM_DATA_JOIN = CONCAT('LEFT JOIN (SELECT AWARD_ID,', LS_CUSTOM_DATA_JOIN_SEL, ' FROM AWARD_CUSTOM_DATA_RT GROUP BY AWARD_ID) CD ON CD.AWARD_ID = T1.AWARD_ID');

    SET @JOIN_QUERY_MAP = JSON_OBJECT(
        'JOIN_CUSTOM_DATA', @CUSTOM_DATA_JOIN,
        'JOIN_AWARD_PERSONS', 'LEFT JOIN AWARD_PERSONS API ON T1.AWARD_ID = API.AWARD_ID AND API.PERSON_ROLE_ID = 3',
        'JOIN_AWARD_SPONSOR', 'LEFT JOIN SPONSOR S ON S.SPONSOR_CODE = T1.SPONSOR_CODE',
        'JOIN_AWARD_PRIME_SPONSOR', 'LEFT JOIN SPONSOR PS ON PS.SPONSOR_CODE = T1.PRIME_SPONSOR_CODE',
        'JOIN_AWARD_STATUS', 'LEFT JOIN AWARD_STATUS AST ON AST.STATUS_CODE = T1.STATUS_CODE',
        'JOIN_AWD_RESEARCH_AREAS', 'LEFT JOIN AWARD_RESEARCH_AREAS_JSON RAR ON T1.AWARD_ID = RAR.AWARD_ID',
        'JOIN_AWARD_TYPE', 'LEFT JOIN AWARD_TYPE AT ON AT.AWARD_TYPE_CODE = T1.AWARD_TYPE_CODE',
        'JOIN_AWARD_UNIT', 'LEFT JOIN UNIT U ON U.UNIT_NUMBER = T1.LEAD_UNIT_NUMBER',
        'JOIN_AWARD_GRANT_TYPE', 'LEFT JOIN GRANT_CALL_TYPE GCT ON GCT.GRANT_TYPE_CODE = T7.GRANT_TYPE_CODE',
        'JOIN_AWARD_KEYWORDS', 'LEFT JOIN AWARD_KEYWORDS_JSON K ON T1.AWARD_ID = K.AWARD_ID',
        'JOIN_AWARD_ACTIVITY_TYPE', 'LEFT JOIN ACTIVITY_TYPE ATC ON ATC.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE',
        'JOIN_AWD_KEY_PERSON', 'LEFT JOIN AWARD_PEOPLE_JSON KP ON T1.AWARD_ID = KP.AWARD_ID',
        'JOIN_AWD_PROJECT_TEAM', 'LEFT JOIN AWARD_PROJECT_TEAM_JSON PT ON T1.AWARD_ID = PT.AWARD_ID',
        'JOIN_AWD_CONTACT', 'LEFT JOIN AWARD_CONTACT_JSON ACJ ON T1.AWARD_ID = ACJ.AWARD_ID',
        'JOIN_AWD_SPL_REVIEW', 'LEFT JOIN AWARD_SPECIAL_REVIEW_JSON ASR ON T1.AWARD_ID = ASR.AWARD_ID',
        'JOIN_AWD_GRANT_CALL_JSON', 'LEFT JOIN AWARD_GRANT_CALL_JSON GCJ ON T1.AWARD_ID = GCJ.AWARD_ID',
        'JOIN_AWARD_VARIATION_TYPE', 'LEFT JOIN SR_TYPE SRT ON SRT.TYPE_CODE = T1.AWARD_VARIATION_TYPE_CODE',
        'JOIN_AWARD_ACCOUNT_TYPE', 'LEFT JOIN ACCOUNT_TYPE ACTY ON ACTY.ACCOUNT_TYPE_CODE = T1.ACCOUNT_TYPE_CODE',
        'JOIN_AWARD_FUNDING_SCHEME', 'LEFT JOIN SPONSOR_FUNDING_SCHEME SFS ON SFS.FUNDING_SCHEME_ID = T7.FUNDING_SCHEME_ID LEFT JOIN FUNDING_SCHEME FS ON FS.FUNDING_SCHEME_CODE = SFS.FUNDING_SCHEME_CODE',
        'JOIN_AWARD_BUDGET_STATUS', 'LEFT JOIN (SELECT ABH.AWARD_ID, ABH.AWARD_BUDGET_STATUS_CODE FROM AWARD_BUDGET_HEADER ABH INNER JOIN (SELECT AWARD_ID, MAX(VERSION_NUMBER) AS MV FROM AWARD_BUDGET_HEADER GROUP BY AWARD_ID) MX ON ABH.AWARD_ID = MX.AWARD_ID AND ABH.VERSION_NUMBER = MX.MV) ABH ON ABH.AWARD_ID = T1.AWARD_ID LEFT JOIN AWARD_BUDGET_STATUS ABS ON ABS.AWARD_BUDGET_STATUS_CODE = ABH.AWARD_BUDGET_STATUS_CODE'
    );

    SET @JOIN_KEY_MAP = JSON_ARRAY(
        JSON_OBJECT('JOIN_CUSTOM_DATA', JSON_ARRAY('CUST_ELEMENTS_ID')),
        JSON_OBJECT('JOIN_AWARD_PERSONS', JSON_ARRAY('COL_AWD_PI', 'CRT_AWD_PI')),
        JSON_OBJECT('JOIN_AWD_RESEARCH_AREAS', JSON_ARRAY('COL_AWD_RESEARCH_AREAS', 'CRT_AWD_RESEARCH_AREAS')),
        JSON_OBJECT('JOIN_AWARD_SPONSOR', JSON_ARRAY('COL_AWD_SPONSOR', 'COL_AWD_SPONSOR_ACRONYM', 'CRT_AWD_SPONSOR')),
        JSON_OBJECT('JOIN_AWARD_PRIME_SPONSOR', JSON_ARRAY('COL_AWD_PRIME_SPONSOR', 'CRT_AWD_PRIME_SPONSOR')),
        JSON_OBJECT('JOIN_AWARD_STATUS', JSON_ARRAY('COL_AWD_STATUS', 'CRT_AWD_STATUS')),
        JSON_OBJECT('JOIN_AWARD_TYPE', JSON_ARRAY('COL_AWD_TYPE', 'CRT_AWD_TYPE')),
        JSON_OBJECT('JOIN_AWARD_UNIT', JSON_ARRAY('COL_AWD_LEAD_UNIT', 'CRT_AWD_LEAD_UNIT')),
        JSON_OBJECT('JOIN_AWARD_GRANT_TYPE', JSON_ARRAY('COL_AWD_GRANT_TYPE', 'CRT_AWD_GRANT_TYPE')),
        JSON_OBJECT('JOIN_AWARD_KEYWORDS', JSON_ARRAY('COL_AWD_KEYWORDS')),
        JSON_OBJECT('JOIN_AWARD_ACTIVITY_TYPE', JSON_ARRAY('COL_AWD_ACTIVITY_TYPE', 'CRT_AWD_ACTIVITY_TYPE')),
        JSON_OBJECT('JOIN_AWARD_BUDGET_STATUS', JSON_ARRAY('COL_AWD_BUDGET_STATUS', 'CRT_AWD_BUDGET_STATUS')),
        JSON_OBJECT('JOIN_AWD_KEY_PERSON', JSON_ARRAY('COL_AWD_KEY_PERSON', 'CRT_AWD_KEY_PERSON')),
        JSON_OBJECT('JOIN_AWD_PROJECT_TEAM', JSON_ARRAY('COL_AWD_PROJECT_TEAM', 'CRT_AWD_PROJECT_TEAM')),
        JSON_OBJECT('JOIN_AWD_CONTACT', JSON_ARRAY('COL_AWD_CONTACT', 'CRT_AWD_CONTACT')),
        JSON_OBJECT('JOIN_AWD_GRANT_CALL_JSON', JSON_ARRAY('COL_AWD_GRANT_CALL_ABBREVIATION')),
        JSON_OBJECT('JOIN_AWARD_FUNDING_SCHEME', JSON_ARRAY('COL_AWD_FUNDING_SCHEME', 'CRT_AWD_FUNDING_SCHEME')),
        JSON_OBJECT('JOIN_AWARD_VARIATION_TYPE', JSON_ARRAY('COL_AWD_VERSION_TYPE', 'CRT_AWD_VERSION_TYPE')),
        JSON_OBJECT('JOIN_AWARD_ACCOUNT_TYPE', JSON_ARRAY('COL_AWD_ACCOUNT_TYPE')),
        JSON_OBJECT('JOIN_AWD_SPL_REVIEW', JSON_ARRAY('COL_AWD_SPL_REVIEW_PROTOCOL', 'CRT_AWD_SPL_REVIEW_PROTOCOL'))
    );

    -- Prepare conditional joins based on display list and filter JSON
    SELECT FN_PREPARE_DASHBOARD_JOINS(AV_DISPLAY_LIST, AV_FILTER_JSON, @JOIN_KEY_MAP, @JOIN_QUERY_MAP, 'JOIN') INTO @JOIN_QUERY;

    -- =============================================
    -- BUILD TAB QUERIES
    -- =============================================

    SET @MY_AWARDS_QUERY = CONCAT('WHERE ((AP.PERSON_ID = ''', AV_PERSON_ID, ''' AND AP.PERSON_ROLE_ID = 3)) AND T1.AWARD_SEQUENCE_STATUS = ''ACTIVE'' AND T1.STATUS_CODE NOT IN (11,12,5,4)');

    SET @ALL_AWARDS_QUERY = CONCAT(
        ' WHERE (',
        'T1.LEAD_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)',
        ' OR T7.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP_GM)',
        ' OR (T1.LEAD_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP_FOR_MODIFY_VARIATION)',
        '     AND (T1.AWARD_DOCUMENT_TYPE_CODE = ''3''',
        '          OR (0 < (SELECT COUNT(1) FROM AWARD AW',
        '                 WHERE AW.AWARD_NUMBER = T1.AWARD_NUMBER',
        '                   AND AW.AWARD_DOCUMENT_TYPE_CODE = 3',
        '                   AND AW.AWARD_SEQUENCE_STATUS = ''PENDING''))))',
        ' OR (T7.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP_GM_FOR_MODIFY_VARIATION)',
        '     AND (T1.AWARD_DOCUMENT_TYPE_CODE = ''3''',
        '          OR (0 < (SELECT COUNT(1) FROM AWARD AW',
        '                 WHERE AW.AWARD_NUMBER = T1.AWARD_NUMBER',
        '                   AND AW.AWARD_DOCUMENT_TYPE_CODE = 3',
        '                   AND AW.AWARD_SEQUENCE_STATUS = ''PENDING''))))',
        ' OR T1.AWARD_ID IN (SELECT AWARD_ID FROM AWARD_PERSONS',
        '                    WHERE PERSON_ID = ''', AV_PERSON_ID, ''')',
        ' OR (T1.AWARD_ID IN (SELECT DISTINCT S1.AWARD_ID FROM AWARD_PERSON_ROLES S1',
        '                     WHERE T1.AWARD_DOCUMENT_TYPE_CODE <> 1',
        '                       AND S1.PERSON_ID = ''', AV_PERSON_ID, '''',
        '                       AND T1.AWARD_SEQUENCE_STATUS IN (''ACTIVE'')',
        '                    UNION',
        '                    SELECT DISTINCT S2.AWARD_ID FROM AWARD_PERSON_ROLES S2',
        '                    WHERE T1.AWARD_DOCUMENT_TYPE_CODE = 1',
        '                      AND S2.PERSON_ID = ''', AV_PERSON_ID, '''))',
        ' OR (T1.AWARD_NUMBER IN (SELECT DISTINCT X1.AWARD_NUMBER',
        '                         FROM AWARD_PERSON_ROLES X1',
        '                         INNER JOIN AWARD Y1 ON X1.AWARD_ID = Y1.AWARD_ID',
        '                         WHERE Y1.AWARD_DOCUMENT_TYPE_CODE <> 1',
        '                           AND X1.PERSON_ID = ''', AV_PERSON_ID, '''',
        '                           AND Y1.AWARD_SEQUENCE_STATUS IN (''ACTIVE''))',
        '     AND T1.AWARD_SEQUENCE_STATUS IN (''PENDING'')',
        '     AND T1.SEQUENCE_NUMBER > (SELECT MAX(SEQUENCE_NUMBER)',
        '                               FROM AWARD',
        '                               WHERE AWARD_NUMBER = T1.AWARD_NUMBER',
        '                                 AND AWARD_SEQUENCE_STATUS IN (''ACTIVE'')))',
        ') AND T1.AWARD_SEQUENCE_STATUS NOT IN (''ARCHIVE'',''CANCELLED'')'
    );
	
    SET @PENDING_AWARDS_QUERY = CONCAT(
    ' WHERE
    (
        (
            EXISTS (
                SELECT 1
                FROM PENDING_IDS P
                WHERE P.AWARD_ID = T1.AWARD_ID
            )
            AND T4.STATUS_CODE NOT IN (11,12,5,4)
            AND T1.AWARD_SEQUENCE_STATUS NOT IN (''ARCHIVE'',''CANCELLED'')
        )
        OR
        (
            EXISTS (
        SELECT 1
        FROM TASK_IDS TI
        WHERE TI.AWARD_ID = T1.AWARD_ID
    )
            AND T4.STATUS_CODE NOT IN (12,5,4)
        )
    )'
    );

    SET @PENDING_JOINS = '';

    SET @DRAFT_AWARDS_QUERY = CONCAT('WHERE ((T1.CREATE_USER = (SELECT USER_NAME FROM PERSON WHERE PERSON_ID = ''', AV_PERSON_ID, ''') ',
        'OR (T1.LEAD_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP) AND T1.AWARD_DOCUMENT_TYPE_CODE = 1) ',
        'OR (AP.PERSON_ID = ''', AV_PERSON_ID, ''')) ',
        'AND (T1.STATUS_CODE NOT IN (11,12,5,4)) AND (T1.WORKFLOW_AWARD_STATUS_CODE NOT IN (3,5)) AND (T1.AWARD_SEQUENCE_STATUS = ''PENDING''))');

    SET @HOLD_AWARDS_QUERY = CONCAT('WHERE ((T1.CREATE_USER = (SELECT USER_NAME FROM PERSON WHERE PERSON_ID = ''', AV_PERSON_ID, ''') ',
        'OR (T1.LEAD_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)) ',
        'OR (AP.PERSON_ID = ''', AV_PERSON_ID, ''')) ',
        'AND (T1.STATUS_CODE NOT IN (11,12,5,4)) AND (T1.WORKFLOW_AWARD_STATUS_CODE IN (5)) AND (T1.AWARD_SEQUENCE_STATUS = ''PENDING''))');

    SET @TAB_QUERY_MAP = JSON_OBJECT(
        'MY_AWARDS', @MY_AWARDS_QUERY,
        'ALL_AWARDS', @ALL_AWARDS_QUERY,
        'PENDING_AWARDS', @PENDING_AWARDS_QUERY,
        'DRAFT_AWARDS', @DRAFT_AWARDS_QUERY,
        'HOLD_AWARDS', @HOLD_AWARDS_QUERY
    );

    SET @TAB_QUERY = JSON_UNQUOTE(JSON_EXTRACT(@TAB_QUERY_MAP, CONCAT('$.', AV_TAB_TYPE)));
    IF LS_TAB_QUERY_WHERE_CLAUSE IS NOT NULL AND LS_TAB_QUERY_WHERE_CLAUSE <> '' THEN
        SET @TAB_QUERY = CONCAT(LS_TAB_QUERY_WHERE_CLAUSE, @TAB_QUERY);
    END IF;

    -- =============================================
    -- EXTRACT FILTER JSON INTO SESSION VARIABLES
    -- =============================================

    SET SESSION group_concat_max_len = 100000;

    SET @AWD_ID_VAL =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_ID'));

    SET @AWD_NUMBER_VAL =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_NUMBER'));

    SET @AWD_ACCOUNT_NUMBER_VAL =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_ACCOUNT_NUMBER'));

    SET @AWD_TITLE_VAL =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_TITLE'));

    SET @AWD_SPONSOR_AWARD_NUMBER_VAL =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_SPONSOR_AWARD_NUMBER'));

    SET @AWD_CFDA_NUMBER_VAL =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_CFDA_NUMBER'));

    SET @AWD_DFAFS_NUMBER_VAL =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_DFAFS_NUMBER'));

    SET @AWD_KEYWORDS_VAL =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_KEYWORDS'));

    SET @AWD_SPL_REVIEW_PROTOCOL_VAL =
        LOWER(JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_SPL_REVIEW_PROTOCOL')));

    SET @PI_IS_EMP =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_PI.isEmp'));

    SET @KEY_PERSON_IS_EMP =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_KEY_PERSON.isEmp'));

    SET @PROJECT_TEAM_IS_EMP =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_PROJECT_TEAM.isEmp'));

    SET @CONTACT_IS_EMP =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_CONTACT.isEmp'));

    SET @PI_PERSON_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_PI.values'),
            '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @KEY_PERSON_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_KEY_PERSON.values'),
            '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @KEY_PERSONS_ROLES_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_KEY_PERSON_ROLES'),
            '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
        HAVING COUNT(*) > 0
     );

    SET @PROJECT_TEAM_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_PROJECT_TEAM.values'),
            '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @CONTACT_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_CONTACT.values'),
            '$[*]' COLUMNS(res VARCHAR(2550) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    -- Array/multiselect filter values
    SET @AWD_LEAD_UNIT_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_LEAD_UNIT'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @AWD_TYPE_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_TYPE'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @AWD_PRIME_SPONSOR_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_PRIME_SPONSOR'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @AWD_SPONSOR_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_SPONSOR'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @AWD_FUNDING_SCHEME_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_FUNDING_SCHEME'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @AWD_STATUS_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_STATUS'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

	SET @AWD_GRANT_CALL_VAL =
    JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_GRANT_CALL_ABBREVIATION'));

    SET @AWD_GRANT_CALL_ID_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_GRANT_CALL'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @AWD_VARIATION_TYPE_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_VERSION_TYPE'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );
    
    SET @AWD_FUNDING_SCHEME_VAL = (
    SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_FUNDING_SCHEME'),
        '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
    HAVING COUNT(*) > 0
	);

    SET @AWD_ACCOUNT_TYPE_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_ACCOUNT_TYPE'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @AWD_GRANT_TYPE_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_GRANT_TYPE'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @AWD_ACTIVITY_TYPE_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_ACTIVITY_TYPE'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @AWD_BUDGET_STATUS_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_BUDGET_STATUS'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @AWD_VERSION_STATUS_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_VERSION_STATUS'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @AWD_RESEARCH_AREAS_VAL = (
        SELECT GROUP_CONCAT(CONCAT('\'', jt.res, '\'') SEPARATOR ',')
        FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_RESEARCH_AREAS'),
            '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
        HAVING COUNT(*) > 0
    );

    SET @LAST_MOD_DATE_FROM =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_LAST_MOD_DATE.fromDate'));
    SET @LAST_MOD_DATE_TO =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_LAST_MOD_DATE.toDate'));

    SET @EFFECTIVE_DATE_FROM =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_EFFECTIVE_DATE.fromDate'));
    SET @EFFECTIVE_DATE_TO =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_EFFECTIVE_DATE.toDate'));

    SET @FINAL_EXP_DATE_FROM =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_FINAL_EXPIRATION_DATE.fromDate'));
    SET @FINAL_EXP_DATE_TO =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_FINAL_EXPIRATION_DATE.toDate'));

    SET @NOTICE_DATE_FROM =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_NOTICE_DATE.fromDate'));
    SET @NOTICE_DATE_TO =
        JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_AWD_NOTICE_DATE.toDate'));

    -- =============================================
    -- PREPARE CRITERIA QUERY
    -- =============================================

    SET @CRT_AWD_PI_CRT = CONCAT('(
        ( ''', @PI_IS_EMP, ''' = ''true'' AND EXISTS (
            SELECT 1 FROM AWARD_PERSONS AP2
            WHERE AP2.AWARD_ID = T1.AWARD_ID AND AP2.PERSON_ROLE_ID = 3
              AND AP2.PERSON_ID IN (', @PI_PERSON_VAL, ')))
         OR
        ( ''', @PI_IS_EMP, ''' = ''false'' AND EXISTS (
            SELECT 1 FROM AWARD_PERSONS AP2
            WHERE AP2.AWARD_ID = T1.AWARD_ID AND AP2.PERSON_ROLE_ID = 3
              AND AP2.ROLODEX_ID IN (', @PI_PERSON_VAL, ')))
    )');

		SET @KEY_PERSON_IS_EMP = COALESCE(NULLIF(TRIM(@KEY_PERSON_IS_EMP), ''), 'true');
		IF @KEY_PERSON_IS_EMP NOT IN ('true', 'false') THEN
			SET @KEY_PERSON_IS_EMP = 'true';
		END IF;

		IF (@KEY_PERSON_VAL IS NOT NULL AND TRIM(@KEY_PERSON_VAL) != ''
			AND @KEY_PERSONS_ROLES_VAL IS NOT NULL AND TRIM(@KEY_PERSONS_ROLES_VAL) != '') THEN
			SET @CRT_AWD_KEY_PERSON_CRT = CONCAT('(
			( ''', @KEY_PERSON_IS_EMP, ''' = ''true'' AND EXISTS (SELECT 1 FROM AWARD_PERSONS WHERE AWARD_ID = T1.AWARD_ID AND PERSON_ID IN (', @KEY_PERSON_VAL, ') AND PERSON_ROLE_ID IN (', @KEY_PERSONS_ROLES_VAL, ') ))
			 OR
			( ''', @KEY_PERSON_IS_EMP, ''' = ''false'' AND EXISTS (SELECT 1 FROM AWARD_PERSONS WHERE AWARD_ID = T1.AWARD_ID AND ROLODEX_ID IN (', @KEY_PERSON_VAL, ') AND PERSON_ROLE_ID IN (', @KEY_PERSONS_ROLES_VAL, ') ))
		)');
		ELSEIF (@KEY_PERSON_VAL IS NOT NULL AND TRIM(@KEY_PERSON_VAL) != '') THEN
			SET @CRT_AWD_KEY_PERSON_CRT = CONCAT('(
			( ''', @KEY_PERSON_IS_EMP, ''' = ''true'' AND T1.AWARD_ID IN (SELECT AWARD_ID FROM AWARD_PERSONS WHERE PERSON_ID IN (', @KEY_PERSON_VAL, ')))
			 OR
			( ''', @KEY_PERSON_IS_EMP, ''' = ''false'' AND T1.AWARD_ID IN (SELECT AWARD_ID FROM AWARD_PERSONS WHERE ROLODEX_ID IN (', @KEY_PERSON_VAL, ')))
		)');
		ELSEIF (@KEY_PERSONS_ROLES_VAL IS NOT NULL AND TRIM(@KEY_PERSONS_ROLES_VAL) != '') THEN
			SET @CRT_AWD_KEY_PERSON_CRT = NULL;
			SET @AWARD_KEY_PERSONS_ROLES_CRT = CONCAT('(EXISTS (SELECT 1 FROM AWARD_PERSONS WHERE AWARD_ID = T1.AWARD_ID AND PERSON_ROLE_ID IN (', @KEY_PERSONS_ROLES_VAL, ') ))');
		END IF;


    SET @CRT_AWD_PROJECT_TEAM_CRT = CONCAT('(
        ( ''', @PROJECT_TEAM_IS_EMP, ''' = ''true'' AND EXISTS (
            SELECT 1 FROM AWARD_PROJECT_TEAM APT2
            WHERE APT2.AWARD_ID = T1.AWARD_ID AND APT2.NON_EMPLOYEE_FLAG = ''N''
              AND APT2.PERSON_ID IN (', @PROJECT_TEAM_VAL, ')))
         OR
        ( ''', @PROJECT_TEAM_IS_EMP, ''' = ''false'' AND EXISTS (
            SELECT 1 FROM AWARD_PROJECT_TEAM APT2
            WHERE APT2.AWARD_ID = T1.AWARD_ID AND APT2.NON_EMPLOYEE_FLAG = ''Y''
              AND APT2.PERSON_ID IN (', @PROJECT_TEAM_VAL, ')))
    )');

    SET @CRT_AWD_CONTACT_CRT = CONCAT('(
        ( ''', @CONTACT_IS_EMP, ''' = ''true'' AND EXISTS (
            SELECT 1 FROM AWARD_CONTACT AC2
            WHERE AC2.AWARD_ID = T1.AWARD_ID
              AND AC2.PERSON_ID IN (', @CONTACT_VAL, ')))
         OR
        ( ''', @CONTACT_IS_EMP, ''' = ''false'' AND EXISTS (
            SELECT 1 FROM AWARD_CONTACT AC2
            WHERE AC2.AWARD_ID = T1.AWARD_ID
              AND AC2.ROLODEX_ID IN (', @CONTACT_VAL, ')))
    )');

    SET @CRT_AWD_SPL_REVIEW_PROTOCOL_CRT = CONCAT(
        '(EXISTS (SELECT 1 FROM AWARD_SPECIAL_REVIEW ASR2',
        ' WHERE ASR2.AWARD_ID = T1.AWARD_ID',
        ' AND LOWER(ASR2.PROTOCOL_NUMBER) LIKE ''%', @AWD_SPL_REVIEW_PROTOCOL_VAL, '%''))'
    );

    IF @LAST_MOD_DATE_FROM IS NOT NULL AND @LAST_MOD_DATE_TO IS NOT NULL THEN
        SET @CRT_AWD_LAST_MOD_DATE_CRT = CONCAT('( T1.AWARD_ID IS NOT NULL AND CAST(T1.UPDATE_TIMESTAMP AS DATE) BETWEEN ''', @LAST_MOD_DATE_FROM, ''' AND ''', @LAST_MOD_DATE_TO, ''' )');
    ELSEIF @LAST_MOD_DATE_FROM IS NOT NULL AND @LAST_MOD_DATE_TO IS NULL THEN
        SET @CRT_AWD_LAST_MOD_DATE_CRT = CONCAT('( T1.AWARD_ID IS NOT NULL AND CAST(T1.UPDATE_TIMESTAMP AS DATE) >= ''', @LAST_MOD_DATE_FROM, ''' )');
    ELSEIF @LAST_MOD_DATE_FROM IS NULL AND @LAST_MOD_DATE_TO IS NOT NULL THEN
        SET @CRT_AWD_LAST_MOD_DATE_CRT = CONCAT('( T1.AWARD_ID IS NOT NULL AND CAST(T1.UPDATE_TIMESTAMP AS DATE) <= ''', @LAST_MOD_DATE_TO, ''' )');
    END IF;

    IF @EFFECTIVE_DATE_FROM IS NOT NULL AND @EFFECTIVE_DATE_TO IS NOT NULL THEN
        SET @CRT_AWD_EFFECTIVE_DATE_CRT = CONCAT('( T1.AWARD_ID IS NOT NULL AND CAST(T1.BEGIN_DATE AS DATE) BETWEEN ''', @EFFECTIVE_DATE_FROM, ''' AND ''', @EFFECTIVE_DATE_TO, ''' )');
    ELSEIF @EFFECTIVE_DATE_FROM IS NOT NULL AND @EFFECTIVE_DATE_TO IS NULL THEN
        SET @CRT_AWD_EFFECTIVE_DATE_CRT = CONCAT('( T1.AWARD_ID IS NOT NULL AND CAST(T1.BEGIN_DATE AS DATE) >= ''', @EFFECTIVE_DATE_FROM, ''' )');
    ELSEIF @EFFECTIVE_DATE_FROM IS NULL AND @EFFECTIVE_DATE_TO IS NOT NULL THEN
        SET @CRT_AWD_EFFECTIVE_DATE_CRT = CONCAT('( T1.AWARD_ID IS NOT NULL AND CAST(T1.BEGIN_DATE AS DATE) <= ''', @EFFECTIVE_DATE_TO, ''' )');
    END IF;

    IF @FINAL_EXP_DATE_FROM IS NOT NULL AND @FINAL_EXP_DATE_TO IS NOT NULL THEN
        SET @CRT_AWD_FINAL_EXPIRATION_DATE_CRT = CONCAT('( T1.AWARD_ID IS NOT NULL AND CAST(T1.FINAL_EXPIRATION_DATE AS DATE) BETWEEN ''', @FINAL_EXP_DATE_FROM, ''' AND ''', @FINAL_EXP_DATE_TO, ''' )');
    ELSEIF @FINAL_EXP_DATE_FROM IS NOT NULL AND @FINAL_EXP_DATE_TO IS NULL THEN
        SET @CRT_AWD_FINAL_EXPIRATION_DATE_CRT = CONCAT('( T1.AWARD_ID IS NOT NULL AND CAST(T1.FINAL_EXPIRATION_DATE AS DATE) >= ''', @FINAL_EXP_DATE_FROM, ''' )');
    ELSEIF @FINAL_EXP_DATE_FROM IS NULL AND @FINAL_EXP_DATE_TO IS NOT NULL THEN
        SET @CRT_AWD_FINAL_EXPIRATION_DATE_CRT = CONCAT('( T1.AWARD_ID IS NOT NULL AND CAST(T1.FINAL_EXPIRATION_DATE AS DATE) <= ''', @FINAL_EXP_DATE_TO, ''' )');
    END IF;

    IF @NOTICE_DATE_FROM IS NOT NULL AND @NOTICE_DATE_TO IS NOT NULL THEN
        SET @CRT_AWD_NOTICE_DATE_CRT = CONCAT('( T1.AWARD_ID IS NOT NULL AND CAST(T1.AWARD_EFFECTIVE_DATE AS DATE) BETWEEN ''', @NOTICE_DATE_FROM, ''' AND ''', @NOTICE_DATE_TO, ''' )');
    ELSEIF @NOTICE_DATE_FROM IS NOT NULL AND @NOTICE_DATE_TO IS NULL THEN
        SET @CRT_AWD_NOTICE_DATE_CRT = CONCAT('( T1.AWARD_ID IS NOT NULL AND CAST(T1.AWARD_EFFECTIVE_DATE AS DATE) >= ''', @NOTICE_DATE_FROM, ''' )');
    ELSEIF @NOTICE_DATE_FROM IS NULL AND @NOTICE_DATE_TO IS NOT NULL THEN
        SET @CRT_AWD_NOTICE_DATE_CRT = CONCAT('( T1.AWARD_ID IS NOT NULL AND CAST(T1.AWARD_EFFECTIVE_DATE AS DATE) <= ''', @NOTICE_DATE_TO, ''' )');
    END IF;

    -- Build the complete criteria map: maps each filter key to its SQL WHERE fragment
    SET @CRITERIA_MAP = JSON_OBJECT(
        'CRT_AWD_ID',                       CONCAT('(T1.AWARD_ID LIKE ''%', @AWD_ID_VAL, '%'')'),
        'CRT_AWD_NUMBER',                    CONCAT('(T1.AWARD_NUMBER LIKE ''%', @AWD_NUMBER_VAL, '%'')'),
        'CRT_AWD_ACCOUNT_NUMBER',            CONCAT('(T1.ACCOUNT_NUMBER LIKE ''%', @AWD_ACCOUNT_NUMBER_VAL, '%'')'),
        'CRT_AWD_TITLE',                     CONCAT('(T1.TITLE LIKE ''%', @AWD_TITLE_VAL, '%'')'),
        'CRT_AWD_SPONSOR_AWARD_NUMBER',      CONCAT('(T1.SPONSOR_AWARD_NUMBER LIKE ''%', @AWD_SPONSOR_AWARD_NUMBER_VAL, '%'')'),
        'CRT_AWD_CFDA_NUMBER',               CONCAT('(T1.CFDA_NUMBER LIKE ''%', @AWD_CFDA_NUMBER_VAL, '%'')'),
        'CRT_AWD_DFAFS_NUMBER',              CONCAT('(T1.DFAFS_NUMBER LIKE ''%', @AWD_DFAFS_NUMBER_VAL, '%'')'),
        'CRT_AWD_TYPE',                      CONCAT('(', IFNULL(CONCAT('T1.AWARD_TYPE_CODE IN (', @AWD_TYPE_VAL, ')'), '1=1'), ')'),
        'CRT_AWD_LEAD_UNIT',                 CONCAT('(', IFNULL(CONCAT('T1.LEAD_UNIT_NUMBER IN (', @AWD_LEAD_UNIT_VAL, ')'), '1=1'), ')'),
        'CRT_AWD_PRIME_SPONSOR',             CONCAT('(', IFNULL(CONCAT('T1.PRIME_SPONSOR_CODE IN (', @AWD_PRIME_SPONSOR_VAL, ')'), '1=1'), ')'),
        'CRT_AWD_SPONSOR',                   CONCAT('(', IFNULL(CONCAT('T1.SPONSOR_CODE IN (', @AWD_SPONSOR_VAL, ')'), '1=1'), ')'),
        'CRT_AWD_STATUS',                    CONCAT('(', IFNULL(CONCAT('T1.STATUS_CODE IN (', @AWD_STATUS_VAL, ')'), '1=1'), ')'),
		'CRT_AWD_GRANT_CALL_ABBREVIATION', CONCAT('(T7.ABBREVIATION LIKE ''%', @AWD_GRANT_CALL_VAL, '%'')'),
        'CRT_AWD_ACCOUNT_TYPE',              CONCAT('(', IFNULL(CONCAT('T1.ACCOUNT_TYPE_CODE IN (', @AWD_ACCOUNT_TYPE_VAL, ')'), '1=1'), ')'),
        'CRT_AWD_GRANT_TYPE',                CONCAT('(', IFNULL(CONCAT('GCT.GRANT_TYPE_CODE IN (', @AWD_GRANT_TYPE_VAL, ')'), '1=1'), ')'),
        'CRT_AWD_ACTIVITY_TYPE',             CONCAT('(', IFNULL(CONCAT('T1.ACTIVITY_TYPE_CODE IN (', @AWD_ACTIVITY_TYPE_VAL, ')'), '1=1'), ')'),
        'CRT_AWD_BUDGET_STATUS',             CONCAT('(', IFNULL(CONCAT('ABS.AWARD_BUDGET_STATUS_CODE IN (', @AWD_BUDGET_STATUS_VAL, ')'), '1=1'), ')'),
        'CRT_AWD_VERSION_STATUS',            CONCAT('(', IFNULL(CONCAT('T1.AWARD_SEQUENCE_STATUS IN (', @AWD_VERSION_STATUS_VAL, ')'), '1=1'), ')'),
        'CRT_AWD_RESEARCH_AREAS',            CONCAT('(', IFNULL(CONCAT('EXISTS (SELECT 1 FROM AWARD_RESEARCH_AREAS ARA2 WHERE ARA2.AWARD_ID = T1.AWARD_ID AND ARA2.RESRCH_TYPE_AREA_CODE IN (', @AWD_RESEARCH_AREAS_VAL, '))'), '1=1'), ')'),
        'CRT_AWD_PI',                        @CRT_AWD_PI_CRT,
        'CRT_AWD_KEYWORDS',                  CONCAT('(EXISTS(SELECT 1 FROM AWARD_SCIENCE_KEYWORD AK LEFT JOIN SCIENCE_KEYWORD SK ON AK.SCIENCE_KEYWORD_CODE = SK.SCIENCE_KEYWORD_CODE WHERE AK.AWARD_ID = T1.AWARD_ID AND (SK.DESCRIPTION LIKE ''%', @AWD_KEYWORDS_VAL, '%'' OR AK.KEYWORD LIKE ''%', @AWD_KEYWORDS_VAL, '%'')))'),
        'CRT_AWD_LAST_MOD_DATE',             @CRT_AWD_LAST_MOD_DATE_CRT,
        'CRT_AWD_EFFECTIVE_DATE',            @CRT_AWD_EFFECTIVE_DATE_CRT,
        'CRT_AWD_FINAL_EXPIRATION_DATE',     @CRT_AWD_FINAL_EXPIRATION_DATE_CRT,
        'CRT_AWD_NOTICE_DATE',               @CRT_AWD_NOTICE_DATE_CRT,
		'CRT_AWD_KEY_PERSON',   IFNULL(@CRT_AWD_KEY_PERSON_CRT, '1=1'),
		'CRT_AWD_KEY_PERSON_ROLES',  IFNULL(@AWARD_KEY_PERSONS_ROLES_CRT, '1=1'),
        'CRT_AWD_VERSION_TYPE', CONCAT('(', IFNULL(CONCAT('T1.AWARD_VARIATION_TYPE_CODE IN (', @AWD_VARIATION_TYPE_VAL, ')'), '1=1'), ')'),
        'CRT_AWD_PROJECT_TEAM',              @CRT_AWD_PROJECT_TEAM_CRT,
        'CRT_AWD_CONTACT',                   @CRT_AWD_CONTACT_CRT,
        'CRT_AWD_SPL_REVIEW_PROTOCOL',       @CRT_AWD_SPL_REVIEW_PROTOCOL_CRT,
		'CRT_AWD_FUNDING_SCHEME',        CONCAT('(', IFNULL(CONCAT('FS.FUNDING_SCHEME_CODE IN (', @AWD_FUNDING_SCHEME_VAL, ')'), '1=1'), ')'),
        'CRT_AWD_GRANT_CALL',                CONCAT('(', IFNULL(CONCAT('T1.GRANT_HEADER_ID IN (', @AWD_GRANT_CALL_ID_VAL, ')'), '1=1'), ')')
    );

    -- Merge custom data criteria and build the final filter condition
    SELECT JSON_MERGE_PATCH(@CRITERIA_MAP, @CUST_CRITERIA_MAP) INTO @CRITERIA_MAP;
    SELECT FN_PREPARE_DASHBOARD_CRITERIA(AV_FILTER_JSON, @CRITERIA_MAP) INTO LS_FILTER_CONDITION;

    -- =============================================
    -- SORT TYPE
    -- Set default sort order if not provided
    -- =============================================
    IF AV_SORT_TYPE IS NULL OR AV_SORT_TYPE = '' THEN
        IF AV_TAB_TYPE = 'ALL_AWARDS' THEN
            SET AV_SORT_TYPE = 'T1.AWARD_NUMBER ASC';
        ELSE
            SET AV_SORT_TYPE = 'T1.UPDATE_TIMESTAMP DESC';
        END IF;
    ELSE
        SET AV_SORT_TYPE = CONCAT(AV_SORT_TYPE, ',T1.UPDATE_TIMESTAMP DESC');
    END IF;

    -- =============================================
    -- BUILD AND EXECUTE FINAL DYNAMIC SQL
    -- =============================================
    SET LS_DYN_SQL = CONCAT(@DYNAMIC_CTE,
        CASE WHEN AV_IS_COUNT = TRUE
            THEN ' SELECT TOTAL_COUNT FROM (SELECT COUNT(DISTINCT T1.AWARD_ID) AS TOTAL_COUNT'
            ELSE CONCAT(' SELECT ', IFNULL(@DISPLAY, '*'), ' FROM (SELECT ', IFNULL(@SELECT_STM, '*'))
        END,
        ' FROM AWARD T1 ',
        'LEFT JOIN AWARD_PERSONS AP ON T1.AWARD_ID = AP.AWARD_ID AND AP.PERSON_ROLE_ID = 3 ',
        'LEFT JOIN GRANT_CALL_HEADER T7 ON T7.GRANT_HEADER_ID = T1.GRANT_HEADER_ID ',
        'LEFT JOIN AWARD_STATUS T4 ON T4.STATUS_CODE = T1.STATUS_CODE ',
        @PENDING_JOINS,
        IFNULL(@JOIN_QUERY, ''),
        CASE WHEN @TAB_QUERY IS NOT NULL AND @TAB_QUERY <> '' THEN CONCAT(' ', @TAB_QUERY) ELSE '' END,
        CASE WHEN LS_FILTER_CONDITION IS NOT NULL AND LS_FILTER_CONDITION <> '' THEN CONCAT(' AND ', LS_FILTER_CONDITION) ELSE '' END,
        IF(AV_IS_COUNT = FALSE, ' GROUP BY T1.AWARD_ID ', ''),
        IF(AV_IS_COUNT = FALSE, CONCAT(' ORDER BY ', AV_SORT_TYPE, ' '), ''),
        IF(AV_IS_COUNT = FALSE, CONCAT(' LIMIT ', AV_LIMIT, ' OFFSET ', AV_OFFSET), ''),
        ') T'
    );

    -- Prepare and execute the dynamic SQL statement
    SET @QUERY_STATEMENT = LS_DYN_SQL;
    PREPARE EXECUTABLE_STATEMENT FROM @QUERY_STATEMENT;
    EXECUTE EXECUTABLE_STATEMENT;
    DEALLOCATE PREPARE EXECUTABLE_STATEMENT;
    SET SESSION optimizer_search_depth = old_depth;

END
