CREATE PROCEDURE `GET_AWARDS_FOR_BUDGET_UTILIZATION`()
BEGIN
/*
	SELECT 
		S1.AWARD_ID,
		CASE
			WHEN
				((S1.TOTAL_EXPENDITURE_TO_DATE < 0.5 * S1.TOTAL_LATEST_APPROVED_BUDGET) AND (N1.NOTIFICATION_TYPE_ID <> 1417 OR N1.NOTIFICATION_TYPE_ID IS NULL)) THEN 'Y'
			WHEN
				((S1.TOTAL_EXPENDITURE_TO_DATE > S1.TOTAL_LATEST_APPROVED_BUDGET) AND (N1.NOTIFICATION_TYPE_ID <> 1418 OR N1.NOTIFICATION_TYPE_ID IS NULL)) THEN 'N'
		END AS UNDER_UTIL_FLAG
	FROM
    (
			SELECT DISTINCT A1.AWARD_ID, A1.AWARD_NUMBER, SUM(E1.TOTAL_EXPENSE_AMOUNT) AS TOTAL_EXPENDITURE_TO_DATE, AB1.TOTAL_COST AS TOTAL_LATEST_APPROVED_BUDGET
			FROM AWARD_EXPENSE_DETAILS E1
            INNER JOIN AWARD A1 ON E1.AWARD_NUMBER = A1.AWARD_NUMBER
			INNER JOIN AWARD_BUDGET_HEADER AB1 ON AB1.AWARD_ID = A1.AWARD_ID
            WHERE AB1.VERSION_NUMBER IN (SELECT MAX(AB2.VERSION_NUMBER) FROM AWARD_BUDGET_HEADER AB2 WHERE AB1.AWARD_ID = AB2.AWARD_ID)
			AND E1.ACCOUNT_NUMBER IS NOT NULL
			AND E1.INTERNAL_ORDER_CODE IS NOT NULL
			AND A1.FINAL_EXPIRATION_DATE < DATE_SUB(NOW(), INTERVAL 6 MONTH)
			AND A1.AWARD_SEQUENCE_STATUS = "ACTIVE" GROUP BY A1.AWARD_NUMBER
		
	) S1
    LEFT JOIN NOTIFICATION_LOG N1 ON
		(
			((N1.NOTIFICATION_TYPE_ID = 1417 AND N1.MODULE_ITEM_KEY = S1.AWARD_ID) OR
			(N1.NOTIFICATION_TYPE_ID = 1418 AND N1.MODULE_ITEM_KEY = S1.AWARD_ID))
		) AND N1.MODULE_CODE = 1
    WHERE (
		(((S1.TOTAL_EXPENDITURE_TO_DATE < 0.5 * S1.TOTAL_LATEST_APPROVED_BUDGET) OR
        (S1.TOTAL_EXPENDITURE_TO_DATE > S1.TOTAL_LATEST_APPROVED_BUDGET)) AND N1.NOTIFICATION_TYPE_ID IS NULL)
	);
*/
END
