CREATE  PROCEDURE `GET_GRANT_CALL_DETAILS_FOR_ELASTIC`(
	IN AV_MODULE_ITEM_ID INT
)
BEGIN

    SELECT 'ID',
           'Title',
           'Status',
           'Type',
           'Sponsor'
    
    UNION

    SELECT 
        G.GRANT_HEADER_ID AS ID,
        G.NAME AS Title,
        GCS.DESCRIPTION AS Status,
        GCT.DESCRIPTION AS Type,
        S.DISPLAY_NAME

    FROM GRANT_CALL_HEADER G
    INNER JOIN GRANT_CALL_STATUS GCS 
        ON G.GRANT_STATUS_CODE = GCS.GRANT_STATUS_CODE
    INNER JOIN GRANT_CALL_TYPE GCT 
        ON G.GRANT_TYPE_CODE = GCT.GRANT_TYPE_CODE
    LEFT OUTER JOIN SPONSOR S 
        ON G.SPONSOR_CODE = S.SPONSOR_CODE

    WHERE G.GRANT_HEADER_ID = AV_MODULE_ITEM_ID;
END
