CREATE PROCEDURE `GET_GRANT_CALL_DASHBOARD_V1`(
    IN AV_FILTER_JSON JSON,
    IN AV_DISPLAY_LIST JSON,
    IN AV_PERSON_ID VARCHAR(40),
    IN AV_OFFSET INT(10),
    IN AV_LIMIT INT(10),
    IN AV_TAB_TYPE VARCHAR(30),
    IN AV_IS_COUNT BOOLEAN,
    IN AV_SORT_TYPE VARCHAR(500),
    IN AV_IS_CALENDAR_VIEW BOOLEAN
)
BEGIN
    DECLARE LS_DYN_SQL LONGTEXT;
    DECLARE LS_FILTER_CONDITION LONGTEXT;
    DECLARE LS_CREATE_GRANT_COUNT INT(11);
    DECLARE LS_OFFSET INT(11);
    DECLARE IS_UNIT_ADMIN INT(11);

    DECLARE LI_CUSTOM_DATA_ELEMENTS_ID INT(11);
    DECLARE LI_DATA_TYPE INT(11);
    DECLARE LS_CUST_LABEL VARCHAR(255);
    DECLARE LI_CUST_ORDER INT(11);
    DECLARE LS_IS_MULTI_SELECT_LOOKUP VARCHAR(1);
    DECLARE LS_CUSTOM_CRT VARCHAR(255);
    DECLARE LS_CUST_CRT_VALUE TEXT;
    DECLARE CUSTOM_CRT_QUERY TEXT;
    DECLARE LS_CUSTOM_COL VARCHAR(255);
    DECLARE LS_CUSTOM_DATA_ELEMENT VARCHAR(255);
    DECLARE LS_CUST_COL TEXT;
    DECLARE LS_CUSTOM_DATA_JOIN_SEL TEXT;
    DECLARE NOT_FOUND INT DEFAULT 0;

    DECLARE CUSTOM_DATA_ELEMENTS_IDS CURSOR FOR
      SELECT CDE.CUSTOM_DATA_ELEMENTS_ID, CDE.DATA_TYPE, CDE.COLUMN_LABEL, CDEU.ORDER_NUMBER, CDE.IS_MULTI_SELECT_LOOKUP
      FROM CUSTOM_DATA_ELEMENTS CDE
      INNER JOIN CUSTOM_DATA_ELEMENT_USAGE CDEU ON CDEU.CUSTOM_DATA_ELEMENTS_ID = CDE.CUSTOM_DATA_ELEMENTS_ID
      WHERE CDEU.MODULE_CODE = 15
        AND CDE.IS_ACTIVE = 'Y'
        AND CDEU.IS_REQ_ADVANCE_SEARCH = 'Y';

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;

    SET LS_FILTER_CONDITION = '';
    SET LS_CUSTOM_DATA_JOIN_SEL = '';
    SET LS_DYN_SQL = '';
    SET @CUST_CRITERIA_MAP = JSON_OBJECT();
    SET @CUST_COL_MAP = JSON_OBJECT();
    SET @AV_FILTER_JSON = AV_FILTER_JSON;
    SET @AV_DISPLAY_LIST = AV_DISPLAY_LIST;
    SET SESSION group_concat_max_len = 100000;

    OPEN CUSTOM_DATA_ELEMENTS_IDS;
    CUSTOM_DATA_ELEMENTS_LOOP: LOOP
        SET NOT_FOUND = 0;
        FETCH CUSTOM_DATA_ELEMENTS_IDS INTO LI_CUSTOM_DATA_ELEMENTS_ID, LI_DATA_TYPE, LS_CUST_LABEL, LI_CUST_ORDER, LS_IS_MULTI_SELECT_LOOKUP;

        IF NOT_FOUND = 1 THEN
            LEAVE CUSTOM_DATA_ELEMENTS_LOOP;
        END IF;

        SET LS_CUSTOM_CRT = CONCAT('CRT_GRANT_CALL_CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID);
        SET LS_CUSTOM_DATA_ELEMENT = CONCAT('CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID);
        SET LS_CUST_CRT_VALUE = JSON_UNQUOTE(JSON_EXTRACT(AV_FILTER_JSON, CONCAT('$.', LS_CUSTOM_CRT)));

        SET LS_CUSTOM_DATA_JOIN_SEL = CONCAT(
            LS_CUSTOM_DATA_JOIN_SEL,
            CASE
               WHEN LI_DATA_TYPE = 4 OR (LI_DATA_TYPE IN (8,9) AND LS_IS_MULTI_SELECT_LOOKUP = 'Y') THEN
                    CONCAT(
                        'JSON_ARRAYAGG(JSON_OBJECT(''CUSTOM_ANSWER'', CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID,
                        ')) AS CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID
                    )
               WHEN LI_DATA_TYPE = 3 THEN
                    CONCAT('(UNIX_TIMESTAMP(CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID, '))*1000 AS CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID)
               ELSE
                    CONCAT('CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID)
            END,
            ','
        );

        IF LS_CUST_CRT_VALUE IS NOT NULL THEN
            SET CUSTOM_CRT_QUERY = NULL;

            IF LI_DATA_TYPE IN (3) THEN
                SET CUSTOM_CRT_QUERY = CONCAT('(', LS_CUSTOM_DATA_ELEMENT, ' = (UNIX_TIMESTAMP(''', LS_CUST_CRT_VALUE, ''')*1000))');
            ELSEIF LI_DATA_TYPE IN (1,10) THEN
                SET CUSTOM_CRT_QUERY = CONCAT('(', LS_CUSTOM_DATA_ELEMENT, ' LIKE ''%', LS_CUST_CRT_VALUE, '%'')');
            ELSEIF LI_DATA_TYPE IN (4,8,9,6) THEN
                IF LS_IS_MULTI_SELECT_LOOKUP = 'Y' THEN
                    SET CUSTOM_CRT_QUERY = CONCAT('(EXISTS(SELECT 1 FROM GRANT_CALL_CUSTOM_DATA_RT WHERE GRANT_HEADER_ID = T1.GRANT_HEADER_ID AND MATCH(', LS_CUSTOM_DATA_ELEMENT, ') AGAINST (''', LS_CUST_CRT_VALUE, ''') ))');
                ELSE
                    SET CUSTOM_CRT_QUERY = CONCAT('(EXISTS(SELECT 1 FROM GRANT_CALL_CUSTOM_DATA_RT WHERE GRANT_HEADER_ID = T1.GRANT_HEADER_ID AND ', LS_CUSTOM_DATA_ELEMENT, ' IN (SELECT value FROM JSON_TABLE(''',LS_CUST_CRT_VALUE,''',"$[*]" COLUMNS (value LONGTEXT PATH "$")) AS t)  ))');
                END IF;
            ELSE
                IF LI_DATA_TYPE IN (7, 5) THEN
                    SET LS_CUST_CRT_VALUE = JSON_UNQUOTE(JSON_EXTRACT(LS_CUST_CRT_VALUE, '$[0]'));
                END IF;
                SET CUSTOM_CRT_QUERY = CONCAT('(', LS_CUSTOM_DATA_ELEMENT, ' = ''', LS_CUST_CRT_VALUE, ''')');
            END IF;

            IF CUSTOM_CRT_QUERY IS NOT NULL THEN
                SET @CUST_CRITERIA_MAP = JSON_INSERT(@CUST_CRITERIA_MAP, CONCAT('$.', LS_CUSTOM_CRT), CUSTOM_CRT_QUERY);
            END IF;
        END IF;

        SET LS_CUSTOM_COL = CONCAT('COL_GRANT_CALL_CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID);
        IF JSON_CONTAINS(AV_DISPLAY_LIST, JSON_QUOTE(LS_CUSTOM_COL)) = 1 THEN
            SET @CUST_COL_MAP = JSON_INSERT(@CUST_COL_MAP, CONCAT('$.', LS_CUSTOM_COL), CONCAT('CD.', CONCAT('CUST_ELEMENTS_ID_', LI_CUSTOM_DATA_ELEMENTS_ID)));
        END IF;
    END LOOP;
    CLOSE CUSTOM_DATA_ELEMENTS_IDS;

    SET LS_CUSTOM_DATA_JOIN_SEL = TRIM(TRAILING ',' FROM LS_CUSTOM_DATA_JOIN_SEL);

    SET @DYNAMIC_CTE = CONCAT(
        'WITH ACCESS_TMP AS (
            SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
              AND RIGHT_NAME IN (''MODIFY_GRANT_CALL'',''VIEW_GRANT_CALL'',''PUBLISH_GRANT_CALL'')
            UNION
            SELECT CHILD_UNIT_NUMBER
            FROM UNIT_WITH_CHILDREN
            WHERE UNIT_NUMBER IN (
                SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                  AND RIGHT_NAME IN (''MODIFY_GRANT_CALL'',''VIEW_GRANT_CALL'',''PUBLISH_GRANT_CALL'')
            )
        )'
    );

    SET @GC_KEYWORD_CTE = 'GC_KEYWORDS_JSON AS (
        SELECT GK.GRANT_HEADER_ID,
               JSON_ARRAYAGG(JSON_OBJECT(''KEYWORD'', COALESCE(SK.DESCRIPTION, GK.KEYWORD))) AS KEYWORDS
        FROM GRANT_CALL_KEYWORDS GK
        LEFT JOIN SCIENCE_KEYWORD SK ON SK.SCIENCE_KEYWORD_CODE = GK.SCIENCE_KEYWORD_CODE
        GROUP BY GK.GRANT_HEADER_ID
    )';

    SET @GC_CONTACT_CTE = 'GC_CONTACTS_JSON AS (
        SELECT GC.GRANT_HEADER_ID,
               JSON_ARRAYAGG(JSON_OBJECT(''FULL_NAME'', GC.FULL_NAME, ''EMAIL'', GC.EMAIL, ''DESIGNATION'', GC.DESIGNATION, ''MOBILE'', GC.MOBILE)) AS CONTACTS
        FROM GRANT_CALL_CONTACTS GC
        GROUP BY GC.GRANT_HEADER_ID
    )';

    SET @GC_RESEARCH_CTE = 'GC_RESEARCH_AREAS_JSON AS (
        SELECT GRA.GRANT_HEADER_ID,
               JSON_ARRAYAGG(JSON_OBJECT(''AREA'', RTA.DESCRIPTION, ''SUB_AREA'', RTSA.DESCRIPTION)) AS RESEARCH_AREAS
        FROM GRANT_CALL_RESEARCH_AREAS GRA
        LEFT JOIN RESEARCH_TYPE_AREA RTA ON RTA.RESRCH_TYPE_AREA_CODE = GRA.RESRCH_TYPE_AREA_CODE
        LEFT JOIN RESEARCH_TYPE_SUB_AREA RTSA ON RTSA.RESRCH_TYPE_SUB_AREA_CODE = GRA.RESRCH_TYPE_SUB_AREA_CODE
        GROUP BY GRA.GRANT_HEADER_ID
    )';

    SET @GC_KPI_CTE = 'GC_KPI_JSON AS (
        SELECT GK.GRANT_HEADER_ID,
               JSON_ARRAYAGG(JSON_OBJECT(''KPI_TYPE'', KT.DESCRIPTION, ''KPI_CRITERIA'', KCT.DESCRIPTION)) AS KPI_DETAILS
        FROM GRANT_CALL_KPI GK
        LEFT JOIN KPI_TYPE KT ON KT.KPI_TYPE_CODE = GK.KPI_TYPE_CODE
        LEFT JOIN GRANT_CALL_KPI_CRITERIA GKC ON GKC.GRANT_CALL_KPI_ID = GK.GRANT_CALL_KPI_ID
        LEFT JOIN KPI_CRITERIA_TYPE KCT ON KCT.KPI_CRITERIA_TYPE_CODE = GKC.KPI_CRITERIA_TYPE_CODE
        GROUP BY GK.GRANT_HEADER_ID
    )';

    SET @CTE_MAP = JSON_OBJECT(
        'CTE_GC_KEYWORD', @GC_KEYWORD_CTE,
        'CTE_GC_CONTACT', @GC_CONTACT_CTE,
        'CTE_GC_RESEARCH', @GC_RESEARCH_CTE,
        'CTE_GC_KPI', @GC_KPI_CTE
    );

    SET @CTE_KEY_MAP = JSON_ARRAY(
        JSON_OBJECT('CTE_GC_KEYWORD', JSON_ARRAY('COL_GRANT_CALL_KEYWORD', 'CRT_GRANT_CALL_KEYWORD')),
        JSON_OBJECT('CTE_GC_CONTACT', JSON_ARRAY('COL_GRANT_CALL_POC', 'CRT_GRANT_CALL_POC')),
        JSON_OBJECT('CTE_GC_RESEARCH', JSON_ARRAY('COL_GRANT_CALL_AREA_OF_RESEARCH', 'CRT_GRANT_CALL_AREA_OF_RESEARCH')),
        JSON_OBJECT('CTE_GC_KPI', JSON_ARRAY('COL_GRANT_CALL_KPI', 'CRT_GRANT_CALL_KPI'))
    );

    SET @DYNAMIC_CTE = CONCAT(@DYNAMIC_CTE, COALESCE(FN_PREPARE_DASHBOARD_JOINS(@AV_DISPLAY_LIST, @AV_FILTER_JSON, @CTE_KEY_MAP, @CTE_MAP, 'CTE'), ''));

    IF AV_IS_COUNT = FALSE THEN
        SET @QUERY_MAP = JSON_OBJECT(
            'grantCallId', 'T1.GRANT_HEADER_ID',
            'grantCallName','T1.NAME',
            'sponsorName', 'T6.DISPLAY_NAME',
            'abbrevation','T1.ABBREVIATION',
            'grantCallTypeDesc','T2.DESCRIPTION',
            'homeUnitName','T5.DISPLAY_NAME',
            'openingDate','T1.OPENING_DATE',
            'closingDate','T1.CLOSING_DATE',
            'statusCode', 'T1.GRANT_STATUS_CODE',
            'homeUnitNumber', 'T1.HOME_UNIT_NUMBER',
            'HEADER_ID', 'T1.GRANT_HEADER_ID',
            'COL_GRANT_CALL_ID', 'T1.GRANT_HEADER_ID',
            'COL_GRANT_CALL_TITLE', 'T1.NAME',
            'COL_GRANT_CALL_TYPE', 'T2.DESCRIPTION',
            'COL_GRANT_CALL_UNIT', 'T5.DISPLAY_NAME',
            'COL_GRANT_CALL_FUNDING_AGENCY', 'T6.DISPLAY_NAME',
            'COL_GRANT_CALL_PRIME_SPONSOR', 'T14.DISPLAY_NAME',
            'COL_GRANT_CALL_OPEN_DATE', '(UNIX_TIMESTAMP(T1.OPENING_DATE)*1000)',
            'COL_GRANT_CALL_CLOSE_DATE', '(UNIX_TIMESTAMP(T1.CLOSING_DATE)*1000)',
            'COL_GRANT_CALL_INTERNAL_DEADLINE', '(UNIX_TIMESTAMP(T1.INTERNAL_SUBMISSION_DEADLINE_DATE)*1000)',
            'COL_GRANT_CALL_STATUS', 'T3.DESCRIPTION',
            'COL_GRANT_CALL_CLOSING_TIME', 'DATE_FORMAT(T1.CLOSING_DATE, ''%H:%i:%s'')',
            'COL_GRANT_CALL_TYPE_FUNDING', 'ST.DESCRIPTION',
            'COL_GRANT_CALL_FUNDING_SCHEME', 'T10.SCHEME_NAME',
            'COL_GRANT_CALL_MAX_BUDGET', 'T1.MAX_BUDGET',
            'COL_GRANT_CALL_FUNDING_QUANTUM', 'T1.QUANTUM',
            'COL_GRANT_CALL_OVERHEAD_RATE_TYPE', 'RT.DESCRIPTION',
            'COL_GRANT_CALL_OVERHEAD_RATE', 'T1.OH_WAIVER_PERCENTAGE',
            'COL_GRANT_CALL_KEYWORD', '(GKJ.KEYWORDS)',
            'COL_GRANT_CALL_POC', '(GCJ.CONTACTS)',
            'COL_GRANT_CALL_AREA_OF_RESEARCH', '(GRAJ.RESEARCH_AREAS)',
            'COL_GRANT_CALL_KPI', '(GKPIJ.KPI_DETAILS)',
            'COL_GRANT_CALL_WEBLINK', 'T1.EXTERNAL_URL'
        );

        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST, '$', 'HEADER_ID');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST, '$', 'grantCallId');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST, '$', 'grantCallName');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST, '$', 'sponsorName');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST, '$', 'abbrevation');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST, '$', 'grantCallTypeDesc');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST, '$', 'homeUnitName');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST, '$', 'openingDate');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST, '$', 'closingDate');
        SET AV_DISPLAY_LIST = JSON_ARRAY_APPEND(AV_DISPLAY_LIST, '$', 'homeUnitNumber');
        SET @AV_DISPLAY_LIST = AV_DISPLAY_LIST;

        IF JSON_LENGTH(@CUST_COL_MAP) > 0 THEN
            SELECT JSON_MERGE_PATCH(@QUERY_MAP, @CUST_COL_MAP) INTO @QUERY_MAP;
        END IF;

        SET @DISPLAY_MAP = (
            SELECT JSON_OBJECTAGG(jk.k, JSON_UNQUOTE(JSON_EXTRACT(@QUERY_MAP, CONCAT('$.', jk.k))))
            FROM JSON_TABLE(AV_DISPLAY_LIST, '$[*]' COLUMNS (k VARCHAR(100) PATH '$')) AS jk
            WHERE JSON_EXTRACT(@QUERY_MAP, CONCAT('$.', jk.k)) IS NOT NULL
        );

        SELECT FN_PREPARE_DASHBOARD_SELECT(@DISPLAY_MAP) INTO @SELECT_STM;
        SELECT FN_PREPARE_DASHBOARD_JSON(@DISPLAY_MAP) INTO @DISPLAY;
    END IF;

    IF LS_CUSTOM_DATA_JOIN_SEL IS NOT NULL AND LS_CUSTOM_DATA_JOIN_SEL <> '' THEN
        SET @CUSTOM_DATA_JOIN = CONCAT(
            'LEFT JOIN (SELECT GRANT_HEADER_ID,', LS_CUSTOM_DATA_JOIN_SEL,
            ' FROM GRANT_CALL_CUSTOM_DATA_RT GROUP BY GRANT_HEADER_ID) CD ON CD.GRANT_HEADER_ID = T1.GRANT_HEADER_ID'
        );
    ELSE
        SET @CUSTOM_DATA_JOIN = '';
    END IF;

    SET @JOIN_QUERY_MAP = JSON_OBJECT(
        'JOIN_CUSTOM_DATA', @CUSTOM_DATA_JOIN,
        'JOIN_GRANT_CALL_TYPE', 'LEFT JOIN GRANT_CALL_TYPE T2 ON T2.GRANT_TYPE_CODE = T1.GRANT_TYPE_CODE',
        'JOIN_GRANT_CALL_STATUS', 'LEFT JOIN GRANT_CALL_STATUS T3 ON T3.GRANT_STATUS_CODE = T1.GRANT_STATUS_CODE',
        'JOIN_GRANT_CALL_UNIT', 'LEFT JOIN UNIT T5 ON T5.UNIT_NUMBER = T1.HOME_UNIT_NUMBER',
        'JOIN_SPONSOR_CODE', 'LEFT JOIN SPONSOR T6 ON T6.SPONSOR_CODE = T1.SPONSOR_CODE',
        'JOIN_GRANT_RELEVANT', 'LEFT JOIN GRANT_CALL_RELEVANT_FIELD T7 ON T7.GRANT_HEADER_ID = T1.GRANT_HEADER_ID',
        'JOIN_RELEVANT_FIELD', 'LEFT JOIN RELEVANT_FIELD T8 ON T8.RELEVANT_FIELD_CODE = T7.RELEVANT_FIELD_CODE',
        'JOIN_FUNDING_SCHEME', 'LEFT JOIN SPONSOR_FUNDING_SCHEME SFS ON SFS.FUNDING_SCHEME_ID = T1.FUNDING_SCHEME_ID LEFT JOIN FUNDING_SCHEME T10 ON T10.FUNDING_SCHEME_CODE = SFS.FUNDING_SCHEME_CODE',
        'JOIN_PRIME_SPONSOR_CODE', 'LEFT JOIN SPONSOR T14 ON T14.SPONSOR_CODE = T1.PRIME_SPONSOR_CODE',
        'JOIN_SPONSOR_TYPE', 'LEFT JOIN SPONSOR_TYPE ST ON ST.SPONSOR_TYPE_CODE = T1.SPONSOR_TYPE_CODE',
        'JOIN_RATE_TYPE', 'LEFT JOIN RATE_TYPE RT ON RT.RATE_CLASS_CODE = T1.RATE_CLASS_CODE AND RT.RATE_TYPE_CODE = T1.RATE_TYPE_CODE',
        'JOIN_GC_KEYWORD', 'LEFT JOIN GC_KEYWORDS_JSON GKJ ON GKJ.GRANT_HEADER_ID = T1.GRANT_HEADER_ID',
        'JOIN_GC_CONTACT', 'LEFT JOIN GC_CONTACTS_JSON GCJ ON GCJ.GRANT_HEADER_ID = T1.GRANT_HEADER_ID',
        'JOIN_GC_RESEARCH', 'LEFT JOIN GC_RESEARCH_AREAS_JSON GRAJ ON GRAJ.GRANT_HEADER_ID = T1.GRANT_HEADER_ID',
        'JOIN_GC_KPI', 'LEFT JOIN GC_KPI_JSON GKPIJ ON GKPIJ.GRANT_HEADER_ID = T1.GRANT_HEADER_ID'
    );

    SET @JOIN_KEY_MAP = JSON_ARRAY(
        JSON_OBJECT('JOIN_CUSTOM_DATA', JSON_ARRAY('CUST_ELEMENTS_ID')),
        JSON_OBJECT('JOIN_GRANT_CALL_TYPE', JSON_ARRAY('COL_GRANT_CALL_TYPE','CRT_GRANT_CALL_TYPE','grantCallTypeDesc')),
        JSON_OBJECT('JOIN_GRANT_CALL_STATUS', JSON_ARRAY('COL_GRANT_CALL_STATUS','CRT_GRANT_CALL_STATUS')),
        JSON_OBJECT('JOIN_GRANT_CALL_UNIT', JSON_ARRAY('COL_GRANT_CALL_UNIT','CRT_GRANT_CALL_UNIT','homeUnitName')),
        JSON_OBJECT('JOIN_SPONSOR_CODE', JSON_ARRAY('COL_GRANT_CALL_FUNDING_AGENCY','CRT_GRANT_CALL_FUNDING_AGENCY','sponsorName')),
        JSON_OBJECT('JOIN_FUNDING_SCHEME', JSON_ARRAY('COL_GRANT_CALL_FUNDING_SCHEME','CRT_GRANT_CALL_FUNDING_SCHEME')),
        JSON_OBJECT('JOIN_PRIME_SPONSOR_CODE', JSON_ARRAY('COL_GRANT_CALL_PRIME_SPONSOR','CRT_GRANT_CALL_PRIME_SPONSOR')),
        JSON_OBJECT('JOIN_SPONSOR_TYPE', JSON_ARRAY('COL_GRANT_CALL_TYPE_FUNDING','CRT_GRANT_CALL_TYPE_FUNDING')),
        JSON_OBJECT('JOIN_RATE_TYPE', JSON_ARRAY('COL_GRANT_CALL_OVERHEAD_RATE_TYPE','CRT_GRANT_CALL_OVERHEAD_RATE_TYPE')),
        JSON_OBJECT('JOIN_GC_KEYWORD', JSON_ARRAY('COL_GRANT_CALL_KEYWORD','CRT_GRANT_CALL_KEYWORD')),
        JSON_OBJECT('JOIN_GC_CONTACT', JSON_ARRAY('COL_GRANT_CALL_POC','CRT_GRANT_CALL_POC')),
        JSON_OBJECT('JOIN_GC_RESEARCH', JSON_ARRAY('COL_GRANT_CALL_AREA_OF_RESEARCH','CRT_GRANT_CALL_AREA_OF_RESEARCH')),
        JSON_OBJECT('JOIN_GC_KPI', JSON_ARRAY('COL_GRANT_CALL_KPI','CRT_GRANT_CALL_KPI'))
    );

    SELECT FN_PREPARE_DASHBOARD_JOINS(@AV_DISPLAY_LIST, @AV_FILTER_JSON, @JOIN_KEY_MAP, @JOIN_QUERY_MAP, 'JOIN') INTO @JOIN_QUERY;

    SET @TAB_ACCESS = CONCAT(
        '(CASE WHEN (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
            OR T1.CREATE_USER = (SELECT USER_NAME FROM PERSON WHERE PERSON_ID = ''', AV_PERSON_ID, '''))
        THEN
            (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
            OR T1.CREATE_USER = (SELECT USER_NAME FROM PERSON WHERE PERSON_ID = ''', AV_PERSON_ID, '''))
        ELSE
            (T1.GRANT_STATUS_CODE NOT IN (1,6) AND T1.IS_PUBLISHED = ''Y'') END)
        AND (CASE WHEN (''', AV_PERSON_ID, ''' IN (SELECT PERSON_ID FROM PERSON WHERE (HOME_UNIT = ''9999'' OR IS_EXTERNAL_USER = ''Y'') AND PERSON_ID = ''', AV_PERSON_ID, '''))
            THEN T1.GRANT_HEADER_ID IN (SELECT GRANT_HEADER_ID FROM GRANT_CALL_ELIGIBILITY WHERE GRANT_ELGBLTY_TYPE_CODE = 3)
            ELSE 1 END)'
    );

    SELECT COUNT(*) INTO LS_CREATE_GRANT_COUNT
    FROM ROLE_RIGHTS T1
    LEFT JOIN RIGHTS T2 ON T1.RIGHT_ID = T2.RIGHT_ID
    LEFT JOIN PERSON_ROLES T3 ON T1.ROLE_ID = T3.ROLE_ID
    WHERE T3.PERSON_ID = AV_PERSON_ID
      AND T2.RIGHT_NAME = 'CREATE_GRANT_CALL';

    IF LS_CREATE_GRANT_COUNT = 0 THEN
        SET @LIST_REQUEST = CONCAT('(T1.GRANT_STATUS_CODE IN (2, 4) AND T1.IS_PUBLISHED = ''Y'' AND ', @TAB_ACCESS, ')');
    ELSE
        SET @LIST_REQUEST = CONCAT('(T1.GRANT_STATUS_CODE NOT IN (3, 5) AND ', @TAB_ACCESS, ')');
    END IF;

    SET @ALL_REQUEST = CONCAT('(T1.GRANT_STATUS_CODE <> 5 AND ', @TAB_ACCESS, ')');

    SET @TAB_QUERY_MAP = JSON_OBJECT(
        'ALL_REQUEST', @ALL_REQUEST
    );

    SET @TAB_QUERY = JSON_UNQUOTE(JSON_EXTRACT(@TAB_QUERY_MAP, CONCAT('$.', AV_TAB_TYPE)));

    SET @GC_ID_VAL = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_ID'));
    SET @GC_TITLE_VAL = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_TITLE'));
    SET @GC_CLOSING_TIME_VAL = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_CLOSING_TIME'));
    SET @GC_MAX_BUDGET_VAL = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_MAX_BUDGET'));
    SET @GC_FUNDING_QUANTUM_VAL = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_FUNDING_QUANTUM'));
    SET @GC_OVERHEAD_RATE_VAL = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_OVERHEAD_RATE'));
    SET @GC_KEYWORD_VAL = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_KEYWORD'));
    SET @GC_POC_IS_EMP = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_POC.isEmp'));
    SET @GC_POC_VAL = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_POC'));
    SET @GC_AREA_VAL = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_AREA_OF_RESEARCH'));
    SET @GC_KPI_VAL = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_KPI'));
    SET @GC_WEBLINK_VAL = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_WEBLINK'));

    SET @OPEN_FROM = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_OPEN_DATE.fromDate'));
    SET @OPEN_TO = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_OPEN_DATE.toDate'));
    SET @CLOSE_FROM = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_CLOSE_DATE.fromDate'));
    SET @CLOSE_TO = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_CLOSE_DATE.toDate'));
    SET @INT_FROM = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_INTERNAL_DEADLINE.fromDate'));
    SET @INT_TO = JSON_UNQUOTE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_INTERNAL_DEADLINE.toDate'));

    SELECT GROUP_CONCAT(CONCAT('''', jt.res, '''') SEPARATOR ',') INTO @GC_TYPE_CODES
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_TYPE'),'$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
    HAVING COUNT(*) > 0;

    SELECT GROUP_CONCAT(CONCAT('''', jt.res, '''') SEPARATOR ',') INTO @GC_STATUS_CODES
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_STATUS'),'$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
    HAVING COUNT(*) > 0;

    SELECT GROUP_CONCAT(CONCAT('''', jt.res, '''') SEPARATOR ',') INTO @GC_UNITS
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_UNIT'),'$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
    HAVING COUNT(*) > 0;

    SELECT GROUP_CONCAT(CONCAT('''', jt.res, '''') SEPARATOR ',') INTO @GC_FUNDING_AGENCY_CODES
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_FUNDING_AGENCY'),'$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
    HAVING COUNT(*) > 0;

    SELECT GROUP_CONCAT(CONCAT('''', jt.res, '''') SEPARATOR ',') INTO @GC_PRIME_SPONSOR_CODES
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_PRIME_SPONSOR'),'$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
    HAVING COUNT(*) > 0;

    SELECT GROUP_CONCAT(CONCAT('''', jt.res, '''') SEPARATOR ',') INTO @GC_OVERHEAD_TYPES
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_OVERHEAD_RATE_TYPE'),'$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
    HAVING COUNT(*) > 0;

    SELECT GROUP_CONCAT(CONCAT('''', jt.res, '''') SEPARATOR ',') INTO @GC_TYPE_FUNDING_CODES
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_TYPE_FUNDING'),'$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
    HAVING COUNT(*) > 0;

    SELECT GROUP_CONCAT(CONCAT('''', jt.res, '''') SEPARATOR ',') INTO @GC_FUNDING_SCHEME_CODES
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_FUNDING_SCHEME'),'$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
    HAVING COUNT(*) > 0;

    SELECT GROUP_CONCAT(CONCAT('''', jt.res, '''') SEPARATOR ',') INTO @GC_RESEARCH_AREA_CODES
    FROM JSON_TABLE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_AREA_OF_RESEARCH'),'$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
    HAVING COUNT(*) > 0;

    SELECT GROUP_CONCAT(CONCAT('''', jt.res, '''') SEPARATOR ',') INTO @GC_POC_PERSON_IDS
    FROM JSON_TABLE(COALESCE(JSON_EXTRACT(@AV_FILTER_JSON, '$.CRT_GRANT_CALL_POC.values'), JSON_ARRAY()), '$[*]' COLUMNS(res VARCHAR(255) PATH '$')) jt
    HAVING COUNT(*) > 0;

    IF @OPEN_FROM IS NOT NULL AND @OPEN_TO IS NOT NULL THEN
        SET @GC_OPEN_DATE_CRT = CONCAT('(DATE(T1.OPENING_DATE) BETWEEN ''', @OPEN_FROM, ''' AND ''', @OPEN_TO, ''')');
    ELSEIF @OPEN_FROM IS NOT NULL AND @OPEN_TO IS NULL THEN
        SET @GC_OPEN_DATE_CRT = CONCAT('(DATE(T1.OPENING_DATE) >= ''', @OPEN_FROM, ''')');
    ELSEIF @OPEN_FROM IS NULL AND @OPEN_TO IS NOT NULL THEN
        SET @GC_OPEN_DATE_CRT = CONCAT('(DATE(T1.OPENING_DATE) <= ''', @OPEN_TO, ''')');
    END IF;

    IF @CLOSE_FROM IS NOT NULL AND @CLOSE_TO IS NOT NULL THEN
        SET @GC_CLOSE_DATE_CRT = CONCAT('(DATE(T1.CLOSING_DATE) BETWEEN ''', @CLOSE_FROM, ''' AND ''', @CLOSE_TO, ''')');
    ELSEIF @CLOSE_FROM IS NOT NULL AND @CLOSE_TO IS NULL THEN
        SET @GC_CLOSE_DATE_CRT = CONCAT('(DATE(T1.CLOSING_DATE) >= ''', @CLOSE_FROM, ''')');
    ELSEIF @CLOSE_FROM IS NULL AND @CLOSE_TO IS NOT NULL THEN
        SET @GC_CLOSE_DATE_CRT = CONCAT('(DATE(T1.CLOSING_DATE) <= ''', @CLOSE_TO, ''')');
    END IF;

    IF @INT_FROM IS NOT NULL AND @INT_TO IS NOT NULL THEN
        SET @GC_INT_DATE_CRT = CONCAT('(DATE(T1.INTERNAL_SUBMISSION_DEADLINE_DATE) BETWEEN ''', @INT_FROM, ''' AND ''', @INT_TO, ''')');
    ELSEIF @INT_FROM IS NOT NULL AND @INT_TO IS NULL THEN
        SET @GC_INT_DATE_CRT = CONCAT('(DATE(T1.INTERNAL_SUBMISSION_DEADLINE_DATE) >= ''', @INT_FROM, ''')');
    ELSEIF @INT_FROM IS NULL AND @INT_TO IS NOT NULL THEN
        SET @GC_INT_DATE_CRT = CONCAT('(DATE(T1.INTERNAL_SUBMISSION_DEADLINE_DATE) <= ''', @INT_TO, ''')');
    END IF;

    SET @GC_POC_IS_EMP = COALESCE(NULLIF(TRIM(@GC_POC_IS_EMP), ''), 'true');
    IF @GC_POC_IS_EMP NOT IN ('true', 'false') THEN
        SET @GC_POC_IS_EMP = 'true';
    END IF;

    IF (@GC_POC_PERSON_IDS IS NOT NULL AND TRIM(@GC_POC_PERSON_IDS) <> '') THEN
        SET @CRT_GRANT_CALL_POC_CRT = CONCAT('(
            ( ''', @GC_POC_IS_EMP, ''' = ''true''  AND EXISTS (
                SELECT 1 FROM GRANT_CALL_CONTACTS GCC
                WHERE GCC.GRANT_HEADER_ID = T1.GRANT_HEADER_ID
                  AND GCC.IS_EMPLOYEE = ''Y''
                  AND GCC.PERSON_ID IN (', @GC_POC_PERSON_IDS, ')
            ))
             OR
            ( ''', @GC_POC_IS_EMP, ''' = ''false'' AND EXISTS (
                SELECT 1 FROM GRANT_CALL_CONTACTS GCC
                WHERE GCC.GRANT_HEADER_ID = T1.GRANT_HEADER_ID
                  AND IFNULL(GCC.IS_EMPLOYEE, ''N'') <> ''Y''
                  AND GCC.PERSON_ID IN (', @GC_POC_PERSON_IDS, ')
            ))
        )');
    ELSE
        SET @CRT_GRANT_CALL_POC_CRT = CONCAT('(LOWER(GCJ.CONTACTS) LIKE LOWER(CONCAT("%",''', @GC_POC_VAL, ''',"%")))');
    END IF;

    SET @CRITERIA_MAP = JSON_OBJECT(
        'CRT_GRANT_CALL_ID', CONCAT('(CAST(T1.GRANT_HEADER_ID AS CHAR) LIKE CONCAT("%",''', @GC_ID_VAL, ''',"%"))'),
        'CRT_GRANT_CALL_TITLE', CONCAT('(T1.NAME LIKE CONCAT("%",''', @GC_TITLE_VAL, ''',"%"))'),
        'CRT_GRANT_CALL_TYPE', CONCAT('(', IFNULL(CONCAT('T1.GRANT_TYPE_CODE IN (', @GC_TYPE_CODES, ')'), '1=1'), ')'),
        'CRT_GRANT_CALL_UNIT', CONCAT('(', IFNULL(CONCAT('T1.HOME_UNIT_NUMBER IN (', @GC_UNITS, ')'), '1=1'), ')'),
        'CRT_GRANT_CALL_FUNDING_AGENCY', CONCAT('(', IFNULL(CONCAT('T1.SPONSOR_CODE IN (', @GC_FUNDING_AGENCY_CODES, ')'), '1=1'), ')'),
        'CRT_GRANT_CALL_PRIME_SPONSOR', CONCAT('(', IFNULL(CONCAT('T1.PRIME_SPONSOR_CODE IN (', @GC_PRIME_SPONSOR_CODES, ')'), '1=1'), ')'),
        'CRT_GRANT_CALL_OPEN_DATE', IFNULL(@GC_OPEN_DATE_CRT, '1=1'),
        'CRT_GRANT_CALL_CLOSE_DATE', IFNULL(@GC_CLOSE_DATE_CRT, '1=1'),
        'CRT_GRANT_CALL_INTERNAL_DEADLINE', IFNULL(@GC_INT_DATE_CRT, '1=1'),
        'CRT_GRANT_CALL_STATUS', CONCAT('(', IFNULL(CONCAT('T1.GRANT_STATUS_CODE IN (', @GC_STATUS_CODES, ')'), '1=1'), ')'),
        'CRT_GRANT_CALL_CLOSING_TIME', CONCAT('(DATE_FORMAT(T1.CLOSING_DATE, ''%H:%i:%s'') LIKE CONCAT("%",''', @GC_CLOSING_TIME_VAL, ''',"%"))'),
        'CRT_GRANT_CALL_TYPE_FUNDING', CONCAT('(', IFNULL(CONCAT('ST.SPONSOR_TYPE_CODE IN (', @GC_TYPE_FUNDING_CODES, ')'), '1=1'), ')'),
        'CRT_GRANT_CALL_FUNDING_SCHEME', CONCAT('(', IFNULL(CONCAT('T10.FUNDING_SCHEME_CODE IN (', @GC_FUNDING_SCHEME_CODES, ')'), '1=1'), ')'),
        'CRT_GRANT_CALL_MAX_BUDGET', IF(@GC_MAX_BUDGET_VAL IS NULL OR @GC_MAX_BUDGET_VAL = '', '1=1', CONCAT('(T1.MAX_BUDGET = ', CAST(@GC_MAX_BUDGET_VAL AS DECIMAL(20,2)), ')')),
        'CRT_GRANT_CALL_FUNDING_QUANTUM', CONCAT('(CAST(T1.QUANTUM AS CHAR) LIKE CONCAT("%",''', @GC_FUNDING_QUANTUM_VAL, ''',"%"))'),
        'CRT_GRANT_CALL_OVERHEAD_RATE_TYPE', CONCAT('(', IFNULL(CONCAT('T1.RATE_TYPE_CODE IN (', @GC_OVERHEAD_TYPES, ')'), '1=1'), ')'),
        'CRT_GRANT_CALL_OVERHEAD_RATE', CONCAT('(CAST(T1.OH_WAIVER_PERCENTAGE AS CHAR) LIKE CONCAT("%",''', @GC_OVERHEAD_RATE_VAL, ''',"%"))'),
        'CRT_GRANT_CALL_KEYWORD', CONCAT('(LOWER(GKJ.KEYWORDS) LIKE LOWER(CONCAT("%",''', @GC_KEYWORD_VAL, ''',"%")))'),
        'CRT_GRANT_CALL_POC', IFNULL(@CRT_GRANT_CALL_POC_CRT, '1=1'),
        'CRT_GRANT_CALL_AREA_OF_RESEARCH', CONCAT('(', IFNULL(CONCAT('EXISTS (SELECT 1 FROM GRANT_CALL_RESEARCH_AREAS GRA2 WHERE GRA2.GRANT_HEADER_ID = T1.GRANT_HEADER_ID AND GRA2.RESRCH_TYPE_AREA_CODE IN (', @GC_RESEARCH_AREA_CODES, '))'), CONCAT('LOWER(GRAJ.RESEARCH_AREAS) LIKE LOWER(CONCAT("%",''', @GC_AREA_VAL, ''',"%"))')), ')'),
        'CRT_GRANT_CALL_KPI', CONCAT('(LOWER(GKPIJ.KPI_DETAILS) LIKE LOWER(CONCAT("%",''', @GC_KPI_VAL, ''',"%")))'),
        'CRT_GRANT_CALL_WEBLINK', CONCAT('(T1.EXTERNAL_URL LIKE CONCAT("%",''', @GC_WEBLINK_VAL, ''',"%"))')
    );

    SELECT JSON_MERGE_PATCH(@CRITERIA_MAP, @CUST_CRITERIA_MAP) INTO @CRITERIA_MAP;
    SELECT FN_PREPARE_DASHBOARD_CRITERIA(AV_FILTER_JSON, @CRITERIA_MAP) INTO LS_FILTER_CONDITION;

    IF AV_SORT_TYPE IS NULL OR AV_SORT_TYPE = '' THEN
        SET AV_SORT_TYPE = 'T1.UPDATE_TIMESTAMP DESC';
    ELSE
        SET AV_SORT_TYPE = CONCAT(AV_SORT_TYPE, ',T1.UPDATE_TIMESTAMP DESC');
    END IF;

    SET LS_DYN_SQL = CONCAT(
        @DYNAMIC_CTE,
        CASE WHEN AV_IS_COUNT = TRUE
            THEN ' SELECT TOTAL_COUNT FROM (SELECT COUNT(DISTINCT T1.GRANT_HEADER_ID) AS TOTAL_COUNT'
            ELSE CONCAT(' SELECT ', IFNULL(@DISPLAY, '*'), ' FROM (SELECT DISTINCT ', IFNULL(@SELECT_STM, '*'))
        END,
        ' FROM GRANT_CALL_HEADER T1 ',
        IFNULL(@JOIN_QUERY, ''),
        ' WHERE 1=1 ',
        CASE WHEN @TAB_QUERY IS NOT NULL AND @TAB_QUERY <> '' THEN CONCAT(' AND ( ', @TAB_QUERY, ')') ELSE '' END,
        CASE WHEN LS_FILTER_CONDITION IS NOT NULL AND LS_FILTER_CONDITION <> '' THEN CONCAT(' AND ', LS_FILTER_CONDITION) ELSE '' END,
        IF(AV_IS_COUNT = FALSE, CONCAT(' ORDER BY ', AV_SORT_TYPE, ' '), ''),
        IF(AV_IS_COUNT = FALSE AND AV_IS_CALENDAR_VIEW = FALSE AND AV_LIMIT IS NOT NULL, CONCAT(' LIMIT ', AV_LIMIT, ' OFFSET ', IFNULL(AV_OFFSET, 0)), ''),
        ') T'
    );

    SET @QUERY_STATEMENT = LS_DYN_SQL;
    PREPARE EXECUTABLE_STATEMENT FROM @QUERY_STATEMENT;
    EXECUTE EXECUTABLE_STATEMENT;
    DEALLOCATE PREPARE EXECUTABLE_STATEMENT;
END
