-- `ADD_COLUMN_IN_AWARD_CUSTOM_DATA_RT`; 

CREATE PROCEDURE `ADD_COLUMN_IN_AWARD_CUSTOM_DATA_RT`(AV_CUSTOM_DATA_ELEMENTS_ID INT, AV_ACTYPE VARCHAR(5))
PROC:BEGIN
    DECLARE LS_MUTLI_ANS_INDEX LONGTEXT;
    DECLARE AV_DATATYPE VARCHAR(30);
    DECLARE AV_NEW_COLUMN_NAME VARCHAR(300);
    DECLARE LI_COUNT INT DEFAULT 0;
    DECLARE LS_COLUMN_NAME VARCHAR(300);
    DECLARE LI_DATA_LENGTH INT;
    DECLARE LI_CUT_CNT INT;
    DECLARE LS_IS_MULTI_SELECT_LOOKUP VARCHAR(1);
    DECLARE LS_DATA_TYPE_CODE VARCHAR(3);
    
    select count(1) into LI_CUT_CNT from custom_data_elements 
    where CUSTOM_DATA_ELEMENTS_ID = AV_CUSTOM_DATA_ELEMENTS_ID;
    
    IF LI_CUT_CNT < 1 THEN
    LEAVE PROC;
    END IF;
    
     IF AV_ACTYPE IN ('I', 'U') THEN
         SELECT DATA_TYPE, DATA_LENGTH, IS_MULTI_SELECT_LOOKUP INTO AV_DATATYPE, LI_DATA_LENGTH, LS_IS_MULTI_SELECT_LOOKUP
        FROM CUSTOM_DATA_ELEMENTS T1 
        WHERE T1.CUSTOM_DATA_ELEMENTS_ID = AV_CUSTOM_DATA_ELEMENTS_ID;

        SET LS_DATA_TYPE_CODE = AV_DATATYPE;
         IF AV_DATATYPE = 3 THEN
            SET AV_DATATYPE = 'DATE';
        ELSEIF AV_DATATYPE = 2 THEN
            IF LI_DATA_LENGTH < 120 THEN 
                SET AV_DATATYPE = CONCAT('INT(', LI_DATA_LENGTH, ')');
            ELSE
                SET AV_DATATYPE = 'INT';
            END IF;
        ELSEIF AV_DATATYPE IN (10, 8, 9, 4, 5) THEN 
            SET AV_DATATYPE = 'LONGTEXT';
        ELSEIF AV_DATATYPE = 1 THEN
        IF LI_DATA_LENGTH > 2000 THEN 
            SET AV_DATATYPE = CONCAT('TEXT');
        ELSE
            SET AV_DATATYPE = CONCAT('VARCHAR(', LI_DATA_LENGTH, ')');
        END IF; 
        ELSE 
            SET AV_DATATYPE = 'VARCHAR(500)';
        END IF;
         SET AV_NEW_COLUMN_NAME = CONCAT('CUST_ELEMENTS_ID_', AV_CUSTOM_DATA_ELEMENTS_ID);
        
     IF NOT EXISTS (
            SELECT 1
            FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_NAME = 'AWARD_CUSTOM_DATA_RT' 
            AND COLUMN_NAME = AV_NEW_COLUMN_NAME
                AND TABLE_SCHEMA = DATABASE()
        ) THEN 

            SET LS_MUTLI_ANS_INDEX = '';
            IF LS_IS_MULTI_SELECT_LOOKUP = "Y" AND LS_DATA_TYPE_CODE IN (4, 8, 9) THEN
                SET LS_MUTLI_ANS_INDEX = CONCAT(' , ADD FULLTEXT (',AV_NEW_COLUMN_NAME,')');
            END IF;

             SET @SQL = CONCAT('ALTER TABLE AWARD_CUSTOM_DATA_RT ADD COLUMN ', AV_NEW_COLUMN_NAME, ' ', AV_DATATYPE, ' AFTER AWARD_ID', LS_MUTLI_ANS_INDEX);
            PREPARE STMT FROM @SQL;
            EXECUTE STMT;
            DEALLOCATE PREPARE STMT;
       END IF;

       CALL UPDATE_DASHBOARD_LOOKUPS_FOR_CUSTOM_DATA(AV_CUSTOM_DATA_ELEMENTS_ID, 1, AV_ACTYPE, LS_DATA_TYPE_CODE);

    ELSEIF AV_ACTYPE = 'D' THEN

    CALL UPDATE_DASHBOARD_LOOKUPS_FOR_CUSTOM_DATA(AV_CUSTOM_DATA_ELEMENTS_ID, 1, AV_ACTYPE, NULL);

         SET LS_COLUMN_NAME = CONCAT('CUST_ELEMENTS_ID_', AV_CUSTOM_DATA_ELEMENTS_ID);
        
         SELECT COUNT(*) INTO LI_COUNT 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_NAME = 'AWARD_CUSTOM_DATA_RT' AND COLUMN_NAME = LS_COLUMN_NAME;
        IF LI_COUNT > 0 THEN 
            SET @SQL = CONCAT('ALTER TABLE AWARD_CUSTOM_DATA_RT DROP COLUMN ', LS_COLUMN_NAME);
            PREPARE STMT FROM @SQL;
            EXECUTE STMT;
            DEALLOCATE PREPARE STMT;
        END IF;
    END IF;
END PROC
